/**
 * Base class for Booking integration tests with shared setup and teardown
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-16 10:00:00
 * Purpose: Provide common test infrastructure for booking integration tests
 */
package com.se100.GymAndPTManagement.integration;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.test.web.servlet.MockMvc;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import com.se100.GymAndPTManagement.repository.*;
import com.se100.GymAndPTManagement.service.*;

/**
 * Base class for all Booking integration tests
 * 
 * Features:
 * - Uses H2 in-memory database for fast test execution
 * - Provides @SpringBootTest context with MockMvc
 * - Auto-configures transaction rollback after each test
 * - Injects all necessary repositories and services
 * - Provides utility methods for common operations
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Transactional
public class BookingIntegrationTestBase {

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper objectMapper;

    // Repository injections
    @Autowired
    protected UserRepository userRepository;

    @Autowired
    protected MemberRepository memberRepository;

    @Autowired
    protected PersonalTrainerRepository personalTrainerRepository;

    @Autowired
    protected ContractRepository contractRepository;

    @Autowired
    protected BookingRepository bookingRepository;

    @Autowired
    protected SlotRepository slotRepository;

    @Autowired
    protected AvailableSlotRepository availableSlotRepository;

    @Autowired
    protected ServicePackageRepository servicePackageRepository;

    @Autowired
    protected CheckinLogRepository checkinLogRepository;

    // Service injections
    @Autowired
    protected BookingService bookingService;

    @Autowired
    protected ContractService contractService;

    @Autowired
    protected MemberService memberService;

    @Autowired
    protected PersonalTrainerService personalTrainerService;

    @BeforeEach
    public void setUp() {
        // Clear all repositories to ensure clean test state
        clearAllData();
    }

    @AfterEach
    public void tearDown() {
        // Cleanup after test - transaction rollback handled by @Transactional
    }

    /**
     * Clear all data from repositories
     * Order matters: delete from tables with foreign keys first
     */
    private void clearAllData() {
        checkinLogRepository.deleteAll();
        bookingRepository.deleteAll();
        contractRepository.deleteAll();
        availableSlotRepository.deleteAll();
        slotRepository.deleteAll();
        servicePackageRepository.deleteAll();
        personalTrainerRepository.deleteAll();
        memberRepository.deleteAll();
        userRepository.deleteAll();
    }

    /**
     * Get all bookings - helper method
     */
    protected int countAllBookings() {
        return (int) bookingRepository.count();
    }

    /**
     * Get all contracts - helper method
     */
    protected int countAllContracts() {
        return (int) contractRepository.count();
    }

    /**
     * Get all members - helper method
     */
    protected int countAllMembers() {
        return (int) memberRepository.count();
    }

}
