/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: DailyDiet entity for daily diet plan management
 */

package com.se100.GymAndPTManagement.domain.table;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "daily_diet", indexes = {
    @Index(name = "idx_member_id", columnList = "member_id"),
    @Index(name = "idx_diet_date", columnList = "diet_date"),
    @Index(name = "idx_status", columnList = "status"),
    @Index(name = "unique_member_date", columnList = "member_id,diet_date", unique = true)
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DailyDiet {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotBlank(message = "Tên kế hoạch không được để trống")
    @Column(nullable = false, length = 255)
    private String planName;
    
    @NotNull(message = "ID hội viên không được để trống")
    @Column(nullable = false)
    private Long memberId;
    
    @NotNull(message = "Ngày ăn không được để trống")
    @Column(nullable = false)
    private LocalDate dietDate;
    
    @Column(nullable = false)
    @Builder.Default
    private Float totalCalories = 0F;
    
    @Column(nullable = false)
    @Builder.Default
    private Float totalProtein = 0F;
    
    @Column(nullable = false)
    @Builder.Default
    private Float totalFat = 0F;
    
    @Column(nullable = false)
    @Builder.Default
    private Float totalCarbohydrate = 0F;
    
    @Column(nullable = false)
    @Builder.Default
    private Integer waterIntake = 0;
    
    @Column(columnDefinition = "TEXT")
    private String notes;
    
    @Column(length = 50, nullable = false)
    @Builder.Default
    private String status = "ACTIVE";
    
    // Audit Fields
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    @Column(length = 255)
    @JsonProperty("created_by")
    private String createdBy;
    
    @Column(length = 255)
    @JsonProperty("updated_by")
    private String updatedBy;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}