package com.se100.GymAndPTManagement.domain.table;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 16:00:00
 * Purpose: Composite primary key for DietDetail entity
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DietDetailId implements Serializable {
    private Long dietId;
    private Long foodId;
}
