package com.se100.GymAndPTManagement.domain.table;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import com.se100.GymAndPTManagement.util.SecurityUtil;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-07 19:58:29
 * Purpose: Member entity for gym membership management
 */
@Entity
@Table(name = "members", indexes = {
        @Index(name = "idx_member_cccd", columnList = "cccd"),
        @Index(name = "idx_member_user_id", columnList = "user_id")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "member_id")
    private Long id;

    // Relationship: 1:1 with User
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    @Column(name = "cccd", length = 12, unique = true)
    private String cccd;

    @Column(name = "money_spent", precision = 15, scale = 2)
    private BigDecimal moneySpent;

    @Column(name = "money_debt", precision = 15, scale = 2)
    private BigDecimal moneyDebt;

    @Column(name = "join_date")
    private LocalDate joinDate;

    // Audit fields (bắt buộc)
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @Column(name = "created_by", length = 100)
    private String createdBy;

    @Column(name = "updated_by", length = 100)
    private String updatedBy;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        createdBy = SecurityUtil.getCurrentUserLogin().orElse("system");

        // Set default values
        if (moneySpent == null) {
            moneySpent = BigDecimal.ZERO;
        }
        if (moneyDebt == null) {
            moneyDebt = BigDecimal.ZERO;
        }
        if (joinDate == null) {
            joinDate = LocalDate.now();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
        updatedBy = SecurityUtil.getCurrentUserLogin().orElse("system");
    }
}
