/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: WorkoutImage entity for workout instruction images
 */

package com.se100.GymAndPTManagement.domain.table;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;

@Entity
@Table(name = "workout_image", indexes = {
    @Index(name = "idx_workout_id", columnList = "workout_id"),
    @Index(name = "idx_status", columnList = "status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WorkoutImage {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotNull(message = "ID bài tập không được để trống")
    @Column(nullable = false)
    private Long workoutId;
    
    @NotBlank(message = "URL hình ảnh không được để trống")
    @Column(nullable = false, length = 255)
    private String imageUrl;
    
    @Column(length = 255)
    private String imagePath;
    
    @Column(columnDefinition = "TEXT")
    private String description;
    
    @Min(value = 1, message = "Thứ tự hiển thị phải >= 1")
    @Column(nullable = false)
    @Builder.Default
    private Integer displayOrder = 1;
    
    @Column(length = 50, nullable = false)
    @Builder.Default
    private String status = "ACTIVE";
    
    // Audit Fields
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    @Column(length = 255)
    @JsonProperty("created_by")
    private String createdBy;
    
    @Column(length = 255)
    @JsonProperty("updated_by")
    private String updatedBy;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}






