/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutDevice entity for inventory management
 */

package com.se100.GymAndPTManagement.domain.table;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "workout_device", indexes = {
    @Index(name = "idx_name", columnList = "name"),
    @Index(name = "idx_equipment_type", columnList = "equipment_type"),
    @Index(name = "idx_status", columnList = "status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WorkoutDevice {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotBlank(message = "Tên thiết bị không được để trống")
    @Column(nullable = false, unique = true, length = 255)
    private String name;
    
    @Column(columnDefinition = "TEXT")
    private String description;
    
    @Column(length = 100)
    private String equipmentType;
    
    @Column(length = 255)
    @JsonProperty("equipment_photo")
    private String equipmentPhoto;
    
    @NotNull(message = "Số lượng không được để trống")
    @Min(value = 1, message = "Số lượng phải >= 1")
    @Column(nullable = false)
    @Builder.Default
    private Integer quantity = 1;
    
    @Column(precision = 10, scale = 2)
    @DecimalMin(value = "0.0", inclusive = false)
    @JsonProperty("purchase_price")
    private BigDecimal purchasePrice;
    
    @Column
    @JsonProperty("purchase_date")
    private LocalDate purchaseDate;
    
    @Column
    @JsonProperty("last_maintenance_date")
    private LocalDate lastMaintenanceDate;
    
    @Column
    @JsonProperty("next_maintenance_date")
    private LocalDate nextMaintenanceDate;
    
    @Column(length = 50, nullable = false)
    @Builder.Default
    private String status = "IN_STOCK";
    
    // Audit Fields
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    @Column(length = 255)
    @JsonProperty("created_by")
    private String createdBy;
    
    @Column(length = 255)
    @JsonProperty("updated_by")
    private String updatedBy;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}






