/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Workout entity for exercise library management
 */

package com.se100.GymAndPTManagement.domain.table;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.time.LocalDateTime;

@Entity
@Table(name = "workout", indexes = {
    @Index(name = "idx_name", columnList = "name"),
    @Index(name = "idx_difficulty_level", columnList = "difficulty_level"),
    @Index(name = "idx_status", columnList = "status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Workout {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotBlank(message = "Tên bài tập không được để trống")
    @Column(nullable = false, length = 255)
    private String name;
    
    @Column(columnDefinition = "TEXT")
    private String description;
    
    @Column
    @JsonProperty("duration_minutes")
    private Integer durationMinutes;
    
    @Column(length = 50)
    @JsonProperty("difficulty_level")
    private String difficultyLevel;
    
    @Column
    @JsonProperty("calories_burnt")
    private Float caloriesBurnt;
    
    @Column
    private Long deviceId;
    
    @Column(length = 50, nullable = false)
    @Builder.Default
    private String status = "ACTIVE";
    
    // Audit Fields
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    @Column(length = 255)
    @JsonProperty("created_by")
    private String createdBy;
    
    @Column(length = 255)
    @JsonProperty("updated_by")
    private String updatedBy;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}