package com.se100.GymAndPTManagement.service;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import com.se100.GymAndPTManagement.controller.AdditionalServiceController;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateAdditionalServiceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResAdditionalServiceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.AdditionalService;
import com.se100.GymAndPTManagement.repository.AdditionalServiceRepository;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;

import lombok.RequiredArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 19:48:37
 * Purpose: Service for AdditionalService management
 */
@Service
@RequiredArgsConstructor
public class AdditionalServiceService {

    private final AdditionalServiceRepository additionalServiceRepository;
    Logger logger = LoggerFactory.getLogger(AdditionalServiceService.class);

    /**
     * Create new additional service
     * 
     * @param request Request DTO containing additional service information
     * @return Response DTO with created additional service data
     */
    public ResAdditionalServiceDTO createAdditionalService(ReqCreateAdditionalServiceDTO request) {
        AdditionalService additionalService = AdditionalService.builder()
                .name(request.getName())
                .costPrice(request.getCostPrice())
                .suggestSellPrice(request.getSuggestSellPrice())
                .description(request.getDescription())
                .build();

        AdditionalService saved = additionalServiceRepository.save(additionalService);
        return ResAdditionalServiceDTO.fromEntity(saved);
    }

    /**
     * Get all additional services
     * 
     * @return List of all additional services
     */
    public List<ResAdditionalServiceDTO> getAllAdditionalServices() {
        return additionalServiceRepository.findAll()
                .stream()
                .map(ResAdditionalServiceDTO::fromEntity)
                .collect(Collectors.toList());
    }

    /**
     * Fetch additional services with pagination and filter
     * 
     * @param specification Filter specification
     * @param pageable      Pagination information
     * @return Paginated result with meta data
     */
    public ResultPaginationDTO handleFetchAdditionalServices(Specification<AdditionalService> specification,
            Pageable pageable) {
        Page<AdditionalService> pageAdditionalServices = additionalServiceRepository.findAll(specification, pageable);
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                .page(pageable.getPageNumber() + 1)
                .pageSize(pageable.getPageSize())
                .totalPages(pageAdditionalServices.getTotalPages())
                .totalItems(pageAdditionalServices.getTotalElements())
                .build();

        resultPaginationDTO.setMeta(meta);
        List<ResAdditionalServiceDTO> result = pageAdditionalServices.getContent()
                .stream()
                .map(ResAdditionalServiceDTO::fromEntity)
                .collect(Collectors.toList());
        resultPaginationDTO.setResult(result);
        return resultPaginationDTO;
    }

    /**
     * Get additional service by ID
     * 
     * @param id Additional service ID
     * @return Response DTO with additional service data
     * @throws IdInvalidException if additional service not found, which is an
     *                            superclass of RuntimeException
     */
    public ResAdditionalServiceDTO getAdditionalServiceById(Long id) {
        AdditionalService additionalService = additionalServiceRepository.findById(id)
                .orElseThrow(() -> {
                    logger.error(">>>ADDITIONAL-SERVICE SERVICE: service not found with ID: {}", id);
                    throw new IdInvalidException("Additional service not found with ID: " + id);
                });
        return ResAdditionalServiceDTO.fromEntity(additionalService);
    }

    /**
     * Get all active additional services
     * 
     * @return List of active additional services
     */
    public List<ResAdditionalServiceDTO> getAllActiveAdditionalServices() {
        return additionalServiceRepository.findByIsActive(true)
                .stream()
                .map(ResAdditionalServiceDTO::fromEntity)
                .collect(Collectors.toList());
    }

    /**
     * Activate additional service by ID
     * 
     * @param id Additional service ID
     * @return Response DTO with updated additional service data
     * @throws IdInvalidException if additional service not found
     */
    public ResAdditionalServiceDTO activateAdditionalService(Long id) {
        AdditionalService additionalService = additionalServiceRepository.findById(id)
                .orElseThrow(() -> {
                    logger.error(">>>ADDITIONAL-SERVICE SERVICE: service not found with ID: {}", id);
                    throw new IdInvalidException("Additional service not found with ID: " + id);
                });

        additionalService.setIsActive(true);
        AdditionalService updated = additionalServiceRepository.save(additionalService);
        return ResAdditionalServiceDTO.fromEntity(updated);
    }

    /**
     * Deactivate (soft delete) additional service by ID
     * 
     * @param id Additional service ID
     * @throws IdInvalidException if additional service not found
     * @return nothing
     */
    public void deleteAdditionalService(Long id) {
        AdditionalService additionalService = additionalServiceRepository.findById(id)
                .orElseThrow(() -> {
                    logger.error(">>>ADDITIONAL-SERVICE SERVICE: service not found with ID: {}", id);
                    throw new IdInvalidException("Additional service not found with ID: " + id);
                });

        additionalService.setIsActive(false);
        AdditionalService updated = additionalServiceRepository.save(additionalService);
    }
}