package com.se100.GymAndPTManagement.service;

import java.util.List;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateBodyMetricsDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateBodyMetricsDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResBodyMetricsDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.BodyMetrics;
import com.se100.GymAndPTManagement.domain.table.Member;
import com.se100.GymAndPTManagement.domain.table.User;
import com.se100.GymAndPTManagement.repository.BodyMetricsRepository;
import com.se100.GymAndPTManagement.repository.MemberRepository;
import com.se100.GymAndPTManagement.repository.UserRepository;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;

import lombok.RequiredArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-14 12:00:00
 * Purpose: Service for BodyMetrics entity
 */
@Service
@RequiredArgsConstructor
public class BodyMetricsService {

    private final BodyMetricsRepository bodyMetricsRepository;
    private final MemberRepository memberRepository;
    private final UserRepository userRepository;

    public ResBodyMetricsDTO createBodyMetrics(ReqCreateBodyMetricsDTO request) {
        // Validate member exists
        Member member = memberRepository.findById(request.getMemberId())
                .orElseThrow(() -> new IdInvalidException("Member not found with id: " + request.getMemberId()));

        // Validate measuredBy user exists (if provided)
        User measuredBy = null;
        if (request.getMeasuredByUserId() != null) {
            measuredBy = userRepository.findById(request.getMeasuredByUserId())
                    .orElseThrow(
                            () -> new IdInvalidException("User not found with id: " + request.getMeasuredByUserId()));
        }

        BodyMetrics bodyMetrics = BodyMetrics.builder()
                .member(member)
                .measuredBy(measuredBy)
                .measuredDate(request.getMeasuredDate())
                .weight(request.getWeight())
                .height(request.getHeight())
                .muscleMass(request.getMuscleMass())
                .bodyFatPercentage(request.getBodyFatPercentage())
                .build();

        BodyMetrics saved = bodyMetricsRepository.save(bodyMetrics);
        return ResBodyMetricsDTO.fromEntity(saved);
    }

    public List<ResBodyMetricsDTO> getAllBodyMetrics() {
        return bodyMetricsRepository.findAll().stream()
                .map(ResBodyMetricsDTO::fromEntity)
                .collect(Collectors.toList());
    }

    public ResBodyMetricsDTO getBodyMetricsById(Long id) {
        BodyMetrics bodyMetrics = bodyMetricsRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Body metrics not found with id: " + id));
        return ResBodyMetricsDTO.fromEntity(bodyMetrics);
    }

    public List<ResBodyMetricsDTO> getBodyMetricsByMemberId(Long memberId) {
        // Validate member exists
        if (!memberRepository.existsById(memberId)) {
            throw new IdInvalidException("Member not found with id: " + memberId);
        }

        return bodyMetricsRepository.findByMemberIdOrderByMeasuredDateDesc(memberId).stream()
                .map(ResBodyMetricsDTO::fromEntity)
                .collect(Collectors.toList());
    }

    public ResBodyMetricsDTO updateBodyMetrics(Long id, ReqUpdateBodyMetricsDTO request) {
        BodyMetrics bodyMetrics = bodyMetricsRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Body metrics not found with id: " + id));

        bodyMetrics.setMeasuredDate(request.getMeasuredDate());
        bodyMetrics.setWeight(request.getWeight());
        bodyMetrics.setHeight(request.getHeight());
        bodyMetrics.setMuscleMass(request.getMuscleMass());
        bodyMetrics.setBodyFatPercentage(request.getBodyFatPercentage());

        BodyMetrics updated = bodyMetricsRepository.save(bodyMetrics);
        return ResBodyMetricsDTO.fromEntity(updated);
    }

    public void deleteBodyMetrics(Long id) {
        BodyMetrics bodyMetrics = bodyMetricsRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Body metrics not found with id: " + id));
        bodyMetricsRepository.delete(bodyMetrics);
    }

    public ResultPaginationDTO handleFetchBodyMetrics(Specification<BodyMetrics> specification, Pageable pageable) {
        Page<BodyMetrics> bodyMetricsPage = bodyMetricsRepository.findAll(specification, pageable);

        ResultPaginationDTO result = new ResultPaginationDTO();
        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();

        meta.setPage(pageable.getPageNumber() + 1);
        meta.setPageSize(pageable.getPageSize());
        meta.setTotalPages(bodyMetricsPage.getTotalPages());
        meta.setTotalItems(bodyMetricsPage.getTotalElements());

        result.setMeta(meta);

        List<ResBodyMetricsDTO> bodyMetricsDTOs = bodyMetricsPage.getContent().stream()
                .map(ResBodyMetricsDTO::fromEntity)
                .collect(Collectors.toList());

        result.setResult(bodyMetricsDTOs);

        return result;
    }
}
