/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 11:10:00
 * Purpose: Service for Checkin Log management with business logic
 */
package com.se100.GymAndPTManagement.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.se100.GymAndPTManagement.domain.table.Booking;
import com.se100.GymAndPTManagement.domain.table.CheckinLog;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqCheckinDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResCheckinLogDTO;
import com.se100.GymAndPTManagement.repository.BookingRepository;
import com.se100.GymAndPTManagement.repository.CheckinLogRepository;

import lombok.RequiredArgsConstructor;
import java.time.LocalTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class CheckinLogService {

    private final CheckinLogRepository checkinLogRepository;
    private final BookingRepository bookingRepository;

    /**
     * Create check-in log when member arrives
     * 
     * Business Logic:
     * 1. Validate booking exists
     * 2. Check if booking already has active checkin (not cancelled)
     * 3. Create new checkin log with CHECKED_IN status
     * 
     * @param dto Check-in request DTO
     * @return Created checkin log response
     * @throws IllegalArgumentException if validation fails
     */
    @Transactional
    public ResCheckinLogDTO checkIn(ReqCheckinDTO dto) {
        // Step 1: Validate booking exists
        Booking booking = bookingRepository.findById(dto.getBookingId())
                .orElseThrow(() -> new IllegalArgumentException("Booking không tồn tại"));

        // Step 2: Check if booking already has active checkin
        if (checkinLogRepository.hasActiveCheckin(dto.getBookingId())) {
            throw new IllegalArgumentException("Booking này đã được check-in rồi");
        }

        // Step 3: Create new checkin log
        CheckinLog checkinLog = CheckinLog.builder()
                .booking(booking)
                .member(booking.getMember())
                .checkinTime(LocalTime.now())
                .status("CHECKED_IN")
                .checkoutTime(null)
                .build();

        CheckinLog savedLog = checkinLogRepository.save(checkinLog);

        // Step 4: Return response DTO
        return mapToResponseDTO(savedLog);
    }

    /**
     * Update check-out time when member finishes workout
     * 
     * Business Logic:
     * 1. Find active checkin log (CHECKED_IN status) by booking ID
     * 2. Update checkout_time and status to CHECKED_OUT
     * 3. Save changes
     * 
     * @param bookingId Booking ID to identify the checkin log
     * @return Updated checkin log response
     * @throws IllegalArgumentException if log not found or multiple logs found
     */
    @Transactional
    public ResCheckinLogDTO checkOut(Long bookingId) {
        // Step 1: Find active checkin log
        CheckinLog checkinLog = checkinLogRepository.findActiveCheckInByBookingId(bookingId)
                .orElseThrow(() -> new IllegalArgumentException(
                        "Không tìm thấy check-in log đang hoạt động cho booking này"));

        // Step 2: Update checkout time and status
        checkinLog.setCheckoutTime(LocalTime.now());
        checkinLog.setStatus("CHECKED_OUT");

        // Step 3: Save changes
        CheckinLog updatedLog = checkinLogRepository.save(checkinLog);

        // Step 4: Return response DTO
        return mapToResponseDTO(updatedLog);
    }

    /**
     * Cancel a checkin log when admin makes a mistake
     * 
     * Business Logic:
     * 1. Find latest checkin log by booking ID
     * 2. Update status to CANCELLED
     * 3. Save changes
     * 
     * @param bookingId Booking ID to identify the checkin log
     * @return Updated checkin log response
     * @throws IllegalArgumentException if log not found
     */
    @Transactional
    public ResCheckinLogDTO cancelCheckin(Long bookingId) {
        // Step 1: Find latest checkin log
        CheckinLog checkinLog = checkinLogRepository.findLatestByBookingId(bookingId)
                .orElseThrow(() -> new IllegalArgumentException(
                        "Không tìm thấy check-in log cho booking này"));

        // Step 2: Update status to CANCELLED
        checkinLog.setStatus("CANCELLED");

        // Step 3: Save changes
        CheckinLog updatedLog = checkinLogRepository.save(checkinLog);

        // Step 4: Return response DTO
        return mapToResponseDTO(updatedLog);
    }

    /**
     * Get all checkin logs by member ID
     */
    @Transactional(readOnly = true)
    public List<ResCheckinLogDTO> getCheckinsByMember(Long memberId) {
        return checkinLogRepository.findByMemberId(memberId)
                .stream()
                .map(this::mapToResponseDTO)
                .collect(Collectors.toList());
    }

    /**
     * Get all checkin logs by booking ID
     */
    @Transactional(readOnly = true)
    public List<ResCheckinLogDTO> getCheckinsByBooking(Long bookingId) {
        return checkinLogRepository.findByBookingId(bookingId)
                .stream()
                .map(this::mapToResponseDTO)
                .collect(Collectors.toList());
    }

    /**
     * Get checkin log by ID
     */
    @Transactional(readOnly = true)
    public ResCheckinLogDTO getCheckinById(Long checkinId) {
        CheckinLog checkinLog = checkinLogRepository.findById(checkinId)
                .orElseThrow(() -> new IllegalArgumentException("Checkin log không tồn tại"));
        return mapToResponseDTO(checkinLog);
    }

    /**
     * Map CheckinLog entity to response DTO
     */
    private ResCheckinLogDTO mapToResponseDTO(CheckinLog checkinLog) {
        return ResCheckinLogDTO.builder()
                .checkinId(checkinLog.getId())
                .bookingId(checkinLog.getBooking() != null ? checkinLog.getBooking().getId() : null)
                .memberId(checkinLog.getMember().getId())
                .memberName(checkinLog.getMember().getUser().getFullname())
                .checkinTime(checkinLog.getCheckinTime())
                .checkoutTime(checkinLog.getCheckoutTime())
                .status(checkinLog.getStatus())
                .createdBy(checkinLog.getCreatedBy())
                .build();
    }
}
