package com.se100.GymAndPTManagement.service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateDailyDietDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateDailyDietDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDailyDietDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDailyDietBasicDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDietDetailDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.DailyDiet;
import com.se100.GymAndPTManagement.domain.table.DietDetail;
import com.se100.GymAndPTManagement.domain.table.Food;
import com.se100.GymAndPTManagement.domain.table.Member;
import com.se100.GymAndPTManagement.domain.table.PersonalTrainer;
import com.se100.GymAndPTManagement.repository.DailyDietRepository;
import com.se100.GymAndPTManagement.repository.DietDetailRepository;
import com.se100.GymAndPTManagement.repository.MemberRepository;
import com.se100.GymAndPTManagement.repository.PersonalTrainerRepository;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 16:30:00
 * Purpose: DailyDiet service for business logic
 */
@Service
public class DailyDietService {

        private final DailyDietRepository dailyDietRepository;
        private final DietDetailRepository dietDetailRepository;
        private final MemberRepository memberRepository;
        private final PersonalTrainerRepository personalTrainerRepository;
        Logger logger = Logger.getLogger(DailyDietService.class.getName());

        public DailyDietService(DailyDietRepository dailyDietRepository,
                        DietDetailRepository dietDetailRepository,
                        MemberRepository memberRepository,
                        PersonalTrainerRepository personalTrainerRepository) {
                this.dailyDietRepository = dailyDietRepository;
                this.dietDetailRepository = dietDetailRepository;
                this.memberRepository = memberRepository;
                this.personalTrainerRepository = personalTrainerRepository;
        }

        // =========================================
        // Conversion Helpers
        // =========================================

        private ResDietDetailDTO convertDietDetailToDTO(DietDetail dietDetail) {
                Food food = dietDetail.getFood();
                BigDecimal amount = dietDetail.getAmount() != null ? dietDetail.getAmount() : BigDecimal.ZERO;

                // Calculate total nutrition based on amount
                // Formula: total = (nutritionPer100g / 100) * amount
                BigDecimal totalCalories = food.getCalories() != null
                                ? food.getCalories().divide(BigDecimal.valueOf(100), 2, java.math.RoundingMode.HALF_UP)
                                                .multiply(amount)
                                : null;

                BigDecimal totalProtein = food.getProtein() != null
                                ? food.getProtein().divide(BigDecimal.valueOf(100), 2, java.math.RoundingMode.HALF_UP)
                                                .multiply(amount)
                                : null;

                BigDecimal totalCarbs = food.getCarbohydrate() != null
                                ? food.getCarbohydrate()
                                                .divide(BigDecimal.valueOf(100), 2, java.math.RoundingMode.HALF_UP)
                                                .multiply(amount)
                                : null;

                BigDecimal totalFat = food.getFat() != null
                                ? food.getFat().divide(BigDecimal.valueOf(100), 2, java.math.RoundingMode.HALF_UP)
                                                .multiply(amount)
                                : null;

                return ResDietDetailDTO.builder()
                                .dietId(dietDetail.getDietId())
                                .foodId(dietDetail.getFoodId())
                                .foodName(food.getName())
                                .prepMethod(dietDetail.getPrepMethod())
                                .amount(dietDetail.getAmount())
                                .note(dietDetail.getNote())
                                // Nutrition per 100g from food
                                .caloriesPer100g(food.getCalories())
                                .proteinPer100g(food.getProtein())
                                .carbsPer100g(food.getCarbohydrate())
                                .fatPer100g(food.getFat())
                                // Calculated total nutrition
                                .totalCalories(totalCalories)
                                .totalProteinG(totalProtein)
                                .totalCarbsG(totalCarbs)
                                .totalFatG(totalFat)
                                .createdAt(dietDetail.getCreatedAt())
                                .updatedAt(dietDetail.getUpdatedAt())
                                .build();
        }

        private ResDailyDietDTO convertToDTO(DailyDiet dailyDiet) {
                // Load diet details
                List<ResDietDetailDTO> dietDetails = dietDetailRepository.findByDietId(dailyDiet.getId()).stream()
                                .map(this::convertDietDetailToDTO)
                                .collect(Collectors.toList());

                return ResDailyDietDTO.builder()
                                .id(dailyDiet.getId())
                                .memberId(dailyDiet.getMember().getId())
                                .memberName(dailyDiet.getMember().getUser().getFullname())
                                .ptId(dailyDiet.getPersonalTrainer() != null ? dailyDiet.getPersonalTrainer().getId()
                                                : null)
                                .ptName(dailyDiet.getPersonalTrainer() != null
                                                ? dailyDiet.getPersonalTrainer().getUser().getFullname()
                                                : null)
                                .dietDate(dailyDiet.getDietDate())
                                .waterLiters(dailyDiet.getWaterLiters())
                                .note(dailyDiet.getNote())
                                .dietDetails(dietDetails)
                                .createdAt(dailyDiet.getCreatedAt())
                                .updatedAt(dailyDiet.getUpdatedAt())
                                .build();
        }

        private ResDailyDietBasicDTO convertToBasicDTO(DailyDiet dailyDiet) {
                return ResDailyDietBasicDTO.builder()
                                .id(dailyDiet.getId())
                                .memberId(dailyDiet.getMember().getId())
                                .memberName(dailyDiet.getMember().getUser().getFullname())
                                .ptId(dailyDiet.getPersonalTrainer() != null ? dailyDiet.getPersonalTrainer().getId()
                                                : null)
                                .ptName(dailyDiet.getPersonalTrainer() != null
                                                ? dailyDiet.getPersonalTrainer().getUser().getFullname()
                                                : null)
                                .dietDate(dailyDiet.getDietDate())
                                .waterLiters(dailyDiet.getWaterLiters())
                                .note(dailyDiet.getNote())
                                .createdAt(dailyDiet.getCreatedAt())
                                .updatedAt(dailyDiet.getUpdatedAt())
                                .build();
        }

        // =========================================
        // CRUD Methods
        // =========================================

        /**
         * Create new daily diet
         * 
         * @param request DTO containing diet creation info
         * @return Response DTO with created diet data
         */
        @Transactional
        public ResDailyDietDTO createDailyDiet(ReqCreateDailyDietDTO request) {
                // Validate member exists
                Member member = memberRepository.findById(request.getMemberId())
                                .orElseThrow(() -> {
                                        logger.warning(">>>DAILY DIET SERVICE - CREATE: Member not found - ID: "
                                                        + request.getMemberId());
                                        return new NoSuchElementException(
                                                        "Không tìm thấy member với ID: " + request.getMemberId());
                                });

                // Check if diet already exists for this member on this date
                if (dailyDietRepository.existsByMemberIdAndDietDate(request.getMemberId(), request.getDietDate())) {
                        logger.warning(">>>DAILY DIET SERVICE - CREATE: Diet already exists for member "
                                        + request.getMemberId()
                                        + " on " + request.getDietDate());
                        throw new IllegalArgumentException("Thực đơn cho ngày này đã tồn tại");
                }

                // Validate PT if provided
                PersonalTrainer pt = null;
                if (request.getPtId() != null) {
                        pt = personalTrainerRepository.findById(request.getPtId())
                                        .orElseThrow(() -> {
                                                logger.warning(">>>DAILY DIET SERVICE - CREATE: PT not found - ID: "
                                                                + request.getPtId());
                                                return new NoSuchElementException(
                                                                "Không tìm thấy PT với ID: " + request.getPtId());
                                        });
                }

                // Create daily diet
                DailyDiet dailyDiet = DailyDiet.builder()
                                .member(member)
                                .personalTrainer(pt)
                                .dietDate(request.getDietDate())
                                .waterLiters(request.getWaterLiters())
                                .note(request.getNote())
                                .build();

                dailyDiet = dailyDietRepository.save(dailyDiet);
                logger.info(">>>DAILY DIET SERVICE - CREATE: Daily diet created successfully with ID "
                                + dailyDiet.getId());

                return convertToDTO(dailyDiet);
        }

        /**
         * Get daily diet by ID
         * 
         * @param id Diet ID
         * @return Response DTO with diet data
         */
        public ResDailyDietDTO getDailyDietById(Long id) {
                DailyDiet dailyDiet = dailyDietRepository.findById(id)
                                .orElseThrow(() -> {
                                        logger.warning(">>>DAILY DIET SERVICE - GET BY ID: Diet not found - ID: " + id);
                                        return new NoSuchElementException("Không tìm thấy thực đơn với ID: " + id);
                                });

                return convertToDTO(dailyDiet);
        }

        /**
         * Get all daily diets (basic info without diet details)
         * 
         * @param pageable Pagination info
         * @return Paginated result with basic diet info
         */
        public ResultPaginationDTO getAllDailyDietsBasic(Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findAll(pageable);

                List<ResDailyDietBasicDTO> diets = dietPage.getContent().stream()
                                .map(this::convertToBasicDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                ResultPaginationDTO result = new ResultPaginationDTO();
                result.setMeta(meta);
                result.setResult(diets);
                return result;
        }

        /**
         * Get all daily diets
         * 
         * @return List of all diets
         */
        public List<ResDailyDietDTO> getAllDailyDiets() {
                return dailyDietRepository.findAll().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());
        }

        /**
         * Get daily diets with filter and pagination
         * 
         * @param spec     Specification filter
         * @param pageable Pagination info
         * @return Paginated result
         */
        public ResultPaginationDTO handleFetchDailyDiets(Specification<DailyDiet> spec, Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findAll(spec, pageable);

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                List<ResDailyDietDTO> dietDTOs = dietPage.getContent().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO res = new ResultPaginationDTO();
                res.setMeta(meta);
                res.setResult(dietDTOs);
                return res;
        }

        /**
         * Get daily diets by member ID
         * 
         * @param memberId Member ID
         * @param pageable Pagination info
         * @return Paginated result
         */
        public ResultPaginationDTO getDailyDietsByMember(Long memberId, Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findByMemberId(memberId, pageable);

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                List<ResDailyDietDTO> dietDTOs = dietPage.getContent().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO res = new ResultPaginationDTO();
                res.setMeta(meta);
                res.setResult(dietDTOs);
                return res;
        }

        /**
         * Get daily diets by PT ID
         * 
         * @param ptId     PT ID
         * @param pageable Pagination info
         * @return Paginated result
         */
        public ResultPaginationDTO getDailyDietsByPT(Long ptId, Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findByPersonalTrainerId(ptId, pageable);

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                List<ResDailyDietDTO> dietDTOs = dietPage.getContent().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO res = new ResultPaginationDTO();
                res.setMeta(meta);
                res.setResult(dietDTOs);
                return res;
        }

        /**
         * Get daily diets by date range
         * 
         * @param startDate Start date
         * @param endDate   End date
         * @param pageable  Pagination info
         * @return Paginated result
         */
        public ResultPaginationDTO getDailyDietsByDateRange(LocalDate startDate, LocalDate endDate, Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findByDietDateBetween(startDate, endDate, pageable);

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                List<ResDailyDietDTO> dietDTOs = dietPage.getContent().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO res = new ResultPaginationDTO();
                res.setMeta(meta);
                res.setResult(dietDTOs);
                return res;
        }

        /**
         * Get daily diets by member and date range
         * 
         * @param memberId  Member ID
         * @param startDate Start date
         * @param endDate   End date
         * @param pageable  Pagination info
         * @return Paginated result
         */
        public ResultPaginationDTO getDailyDietsByMemberAndDateRange(Long memberId, LocalDate startDate,
                        LocalDate endDate,
                        Pageable pageable) {
                Page<DailyDiet> dietPage = dailyDietRepository.findByMemberIdAndDietDateBetween(memberId, startDate,
                                endDate,
                                pageable);

                ResultPaginationDTO.Meta meta = ResultPaginationDTO.Meta.builder()
                                .page(pageable.getPageNumber() + 1)
                                .pageSize(pageable.getPageSize())
                                .totalPages(dietPage.getTotalPages())
                                .totalItems(dietPage.getTotalElements())
                                .build();

                List<ResDailyDietDTO> dietDTOs = dietPage.getContent().stream()
                                .map(this::convertToDTO)
                                .collect(Collectors.toList());

                ResultPaginationDTO res = new ResultPaginationDTO();
                res.setMeta(meta);
                res.setResult(dietDTOs);
                return res;
        }

        /**
         * Get daily diet for specific member and date
         * 
         * @param memberId Member ID
         * @param date     Diet date
         * @return Response DTO with diet data
         */
        public ResDailyDietDTO getDailyDietByMemberAndDate(Long memberId, LocalDate date) {
                DailyDiet dailyDiet = dailyDietRepository.findByMemberIdAndDietDate(memberId, date)
                                .orElseThrow(() -> {
                                        logger.warning(">>>DAILY DIET SERVICE - GET BY MEMBER AND DATE: Diet not found for member "
                                                        + memberId + " on " + date);
                                        return new NoSuchElementException("Không tìm thấy thực đơn cho ngày này");
                                });

                return convertToDTO(dailyDiet);
        }

        /**
         * Update daily diet
         * 
         * @param id      Diet ID
         * @param request DTO containing update data
         * @return Response DTO with updated diet data
         */
        @Transactional
        public ResDailyDietDTO updateDailyDiet(Long id, ReqUpdateDailyDietDTO request) {
                DailyDiet dailyDiet = dailyDietRepository.findById(id)
                                .orElseThrow(() -> {
                                        logger.warning(">>>DAILY DIET SERVICE - UPDATE: Diet not found - ID: " + id);
                                        return new NoSuchElementException("Không tìm thấy thực đơn với ID: " + id);
                                });

                // Update PT if provided
                if (request.getPtId() != null) {
                        PersonalTrainer pt = personalTrainerRepository.findById(request.getPtId())
                                        .orElseThrow(() -> {
                                                logger.warning(">>>DAILY DIET SERVICE - UPDATE: PT not found - ID: "
                                                                + request.getPtId());
                                                return new NoSuchElementException(
                                                                "Không tìm thấy PT với ID: " + request.getPtId());
                                        });
                        dailyDiet.setPersonalTrainer(pt);
                }

                // Update other fields if provided
                if (request.getDietDate() != null) {
                        // Check if new date conflicts with existing diet
                        if (!dailyDiet.getDietDate().equals(request.getDietDate())
                                        && dailyDietRepository.existsByMemberIdAndDietDate(
                                                        dailyDiet.getMember().getId(), request.getDietDate())) {
                                logger.warning(">>>DAILY DIET SERVICE - UPDATE: Diet already exists for member "
                                                + dailyDiet.getMember().getId() + " on " + request.getDietDate());
                                throw new IllegalArgumentException("Thực đơn cho ngày này đã tồn tại");
                        }
                        dailyDiet.setDietDate(request.getDietDate());
                }

                if (request.getWaterLiters() != null) {
                        dailyDiet.setWaterLiters(request.getWaterLiters());
                }

                if (request.getNote() != null) {
                        dailyDiet.setNote(request.getNote());
                }

                dailyDiet = dailyDietRepository.save(dailyDiet);
                logger.info(">>>DAILY DIET SERVICE - UPDATE: Daily diet updated successfully - ID: " + id);

                return convertToDTO(dailyDiet);
        }

        /**
         * Delete daily diet
         * 
         * @param id Diet ID
         */
        @Transactional
        public void deleteDailyDiet(Long id) {
                if (!dailyDietRepository.existsById(id)) {
                        logger.warning(">>>DAILY DIET SERVICE - DELETE: Diet not found - ID: " + id);
                        throw new NoSuchElementException("Không tìm thấy thực đơn với ID: " + id);
                }

                dailyDietRepository.deleteById(id);
                logger.info(">>>DAILY DIET SERVICE - DELETE: Daily diet deleted successfully - ID: " + id);
        }
}
