/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: Food service interface defining business logic
 */

package com.se100.GymAndPTManagement.service;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqFoodDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResFoodDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface FoodService {
    
    /**
     * Tạo mới thực phẩm
     */
    ResFoodDTO createFood(ReqFoodDTO reqFoodDTO);
    
    /**
     * Cập nhật thực phẩm
     */
    ResFoodDTO updateFood(Long id, ReqFoodDTO reqFoodDTO);
    
    /**
     * Lấy thông tin thực phẩm theo ID
     */
    ResFoodDTO getFoodById(Long id);
    
    /**
     * Lấy tất cả thực phẩm (có phân trang)
     */
    Page<ResFoodDTO> getAllFoods(Pageable pageable);
    
    /**
     * Lấy thực phẩm theo trạng thái
     */
    List<ResFoodDTO> getFoodsByStatus(String status);
    
    /**
     * Xóa thực phẩm
     */
    void deleteFood(Long id);
    
    /**
     * Tìm thực phẩm theo tên
     */
    ResFoodDTO getFoodByName(String name);
    
    /**
     * Tìm thực phẩm theo khoảng calo
     */
    List<ResFoodDTO> getFoodsByCaloriesBetween(Float minCalories, Float maxCalories);
    
    /**
     * Lấy danh sách thực phẩm có protein cao nhất
     */
    List<ResFoodDTO> getTopProteinFoods(int limit);
}






