package com.se100.GymAndPTManagement.service;

import java.util.List;
import java.util.NoSuchElementException;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateMemberDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateMemberDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResMemberDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResUserDTO;
import com.se100.GymAndPTManagement.domain.table.Member;
import com.se100.GymAndPTManagement.domain.table.Role;
import com.se100.GymAndPTManagement.domain.table.User;
import com.se100.GymAndPTManagement.repository.MemberRepository;
import com.se100.GymAndPTManagement.repository.RoleRepository;
import com.se100.GymAndPTManagement.repository.UserRepository;
import com.se100.GymAndPTManagement.util.enums.UserStatusEnum;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-07 20:03:11
 * Purpose: Member service for business logic
 */
@Service
public class MemberService {

    private final MemberRepository memberRepository;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;

    // =========================================
    // Calculation Helpers
    // =========================================

    public MemberService(MemberRepository memberRepository, UserRepository userRepository,
            RoleRepository roleRepository, PasswordEncoder passwordEncoder) {
        this.memberRepository = memberRepository;
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.passwordEncoder = passwordEncoder;
    }

    private boolean isActiveMember(Member member) {
        return member.getUser().getStatus() == UserStatusEnum.ACTIVE;
    }

    // =========================================
    // CRUD Methods
    // =========================================

    @Transactional
    public ResMemberDTO createMember(ReqCreateMemberDTO request) {
        // Validate email không trùng
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email đã tồn tại trong hệ thống");
        }

        // Validate CCCD không trùng (nếu có)
        if (request.getCccd() != null && !request.getCccd().isEmpty()) {
            if (memberRepository.existsByCccd(request.getCccd())) {
                throw new RuntimeException("CCCD đã tồn tại trong hệ thống");
            }
        }

        System.out.println(">>>MEMBER SERVICE - CREATE MEMBER: Validation passed.");

        // Get MEMBER role
        Role memberRole = roleRepository.findByName("MEMBER");
        if (memberRole == null) {
            throw new IllegalArgumentException("MEMBER role not found in the system");
        }

        // Tạo User entity
        String finalPassword = (request.getPassword() == null || request.getPassword().trim().isEmpty())
                ? "12345678"
                : request.getPassword();

        User user = User.builder()
                .fullname(request.getFullname())
                .email(request.getEmail())
                .passwordHash(passwordEncoder.encode(finalPassword))
                .phoneNumber(request.getPhoneNumber())
                .avatarUrl(request.getAvatarUrl())
                .dob(request.getDob())
                .gender(request.getGender())
                .status(request.getStatus() != null ? request.getStatus() : UserStatusEnum.ACTIVE)
                .role(memberRole)
                .build();

        System.out.println(">>>MEMBER SERVICE - CREATE MEMBER: User entity created with MEMBER role.");
        // Save User
        User savedUser = userRepository.save(user);
        System.out.println(">>>MEMBER SERVICE - CREATE MEMBER: User saved with ID " + savedUser.getId());
        // Tạo Member entity
        Member member = Member.builder()
                .user(savedUser)
                .cccd(request.getCccd())
                .build();
        // moneySpent, moneyDebt, joinDate sẽ được set trong @PrePersist

        // Save Member
        Member savedMember = memberRepository.save(member);
        System.out.println(">>>MEMBER SERVICE - CREATE MEMBER: Member saved with ID " + savedMember.getId());

        // Convert to DTO
        return convertToDTO(savedMember);
    }

    @Transactional
    public List<ResMemberDTO> getAllMembers() {
        List<Member> members = memberRepository.findAll();
        System.out.println(">>>MEMBER SERVICE - GET ALL MEMBERS: Retrieved " + members.size() + " members.");
        return members.stream()
                .map(this::convertToDTO)
                .toList();
    }

    @Transactional
    public List<ResMemberDTO> getAllActiveMembers() {
        List<Member> members = memberRepository.findAll();
        System.out.println(">>>MEMBER SERVICE - GET ALL ACTIVE MEMBERS: Retrieved " + members.size() + " members.");
        return members.stream()
                .filter(this::isActiveMember)
                .map(this::convertToDTO)
                .toList();
    }

    @Transactional
    public ResMemberDTO getMemberById(Long memberId) {
        Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với ID: " + memberId));
        System.out.println(">>>MEMBER SERVICE - GET MEMBER BY ID: Found member with ID " + memberId);
        return convertToDTO(member);
    }

    @Transactional
    public ResMemberDTO getMemberByEmail(String email) {
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với email: " + email));
        Member member = memberRepository.findByUserId(user.getId())
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với email: " + email));
        System.out.println(">>>MEMBER SERVICE - GET MEMBER BY EMAIL: Found member with email " + email);
        return convertToDTO(member);
    }

    @Transactional
    public ResMemberDTO getMemberByCccd(String cccd) {
        Member member = memberRepository.findByCccd(cccd)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với CCCD: " + cccd));
        System.out.println(">>>MEMBER SERVICE - GET MEMBER BY CCCD: Found member with CCCD " + cccd);
        return convertToDTO(member);
    }

    @Transactional
    public ResMemberDTO updateMember(Long memberId, ReqUpdateMemberDTO request) {
        Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với ID: " + memberId));

        User user = member.getUser();

        // Cập nhật thông tin User
        if (request.getFullname() != null && !request.getFullname().isEmpty()) {
            user.setFullname(request.getFullname());
        }

        if (request.getEmail() != null && !request.getEmail().isEmpty()) {
            // Kiểm tra email mới không trùng với user khác
            if (!user.getEmail().equals(request.getEmail()) && userRepository.existsByEmail(request.getEmail())) {
                throw new RuntimeException("Email đã tồn tại trong hệ thống");
            }
            user.setEmail(request.getEmail());
        }

        if (request.getPhoneNumber() != null) {
            user.setPhoneNumber(request.getPhoneNumber());
        }

        if (request.getAvatarUrl() != null) {
            user.setAvatarUrl(request.getAvatarUrl());
        }

        if (request.getDob() != null) {
            user.setDob(request.getDob());
        }

        if (request.getGender() != null) {
            user.setGender(request.getGender());
        }

        System.out.println(">>>MEMBER SERVICE - UPDATE MEMBER: User information updated.");

        // Cập nhật thông tin Member
        if (request.getCccd() != null && !request.getCccd().isEmpty()) {
            // Kiểm tra CCCD mới không trùng với member khác
            if (!request.getCccd().equals(member.getCccd()) && memberRepository.existsByCccd(request.getCccd())) {
                throw new RuntimeException("CCCD đã tồn tại trong hệ thống");
            }
            member.setCccd(request.getCccd());
        }
        System.out.println(">>>MEMBER SERVICE - UPDATE MEMBER: Member information updated.");

        // Save User và Member
        userRepository.save(user);
        Member updatedMember = memberRepository.save(member);
        System.out.println(">>>MEMBER SERVICE - UPDATE MEMBER: Changes saved to database.");

        return convertToDTO(updatedMember);
    }

    @Transactional
    public void deleteMember(Long memberId) {
        Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy hội viên với ID: " + memberId));

        User user = member.getUser();
        user.setStatus(UserStatusEnum.INACTIVE);
        System.out.println(">>>MEMBER SERVICE - DELETE MEMBER: User status set to INACTIVE.");
        userRepository.save(user);
    }

    // =========================================
    // Mapper
    // =========================================
    private ResMemberDTO convertToDTO(Member member) {
        ResUserDTO userDTO = ResUserDTO.builder()
                .id(member.getUser().getId())
                .fullname(member.getUser().getFullname())
                .email(member.getUser().getEmail())
                .phoneNumber(member.getUser().getPhoneNumber())
                .avatarUrl(member.getUser().getAvatarUrl())
                .dob(member.getUser().getDob())
                .gender(member.getUser().getGender())
                .status(member.getUser().getStatus())
                .build();

        return ResMemberDTO.builder()
                .id(member.getId())
                .user(userDTO)
                .cccd(member.getCccd())
                .moneySpent(member.getMoneySpent())
                .moneyDebt(member.getMoneyDebt())
                .joinDate(member.getJoinDate())
                .createdAt(member.getCreatedAt())
                .updatedAt(member.getUpdatedAt())
                .build();
    }
}
