package com.se100.GymAndPTManagement.service;

import java.time.LocalDate;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.WorkoutDevice;
import com.se100.GymAndPTManagement.repository.WorkoutDeviceRepository;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15
 * Purpose: WorkoutDevice service for business logic
 */
@Service
public class WorkoutDeviceService {

    private final WorkoutDeviceRepository workoutDeviceRepository;
    Logger logger = Logger.getLogger(WorkoutDeviceService.class.getName());

    public WorkoutDeviceService(WorkoutDeviceRepository workoutDeviceRepository) {
        this.workoutDeviceRepository = workoutDeviceRepository;
    }

    // =========================================
    // Conversion Helpers
    // =========================================

    private ResWorkoutDeviceDTO convertToDTO(WorkoutDevice device) {
        return ResWorkoutDeviceDTO.builder()
                .id(device.getId())
                .name(device.getName())
                .type(device.getType())
                .price(device.getPrice())
                .dateImported(device.getDateImported())
                .dateMaintenance(device.getDateMaintenance())
                .imageUrl(device.getImageUrl())
                .createdAt(device.getCreatedAt())
                .updatedAt(device.getUpdatedAt())
                .createdBy(device.getCreatedBy())
                .updatedBy(device.getUpdatedBy())
                .build();
    }

    // =========================================
    // CRUD Operations
    // =========================================

    /**
     * Create a new workout device
     * Validates that device name is unique
     */
    @Transactional
    public ResWorkoutDeviceDTO createWorkoutDevice(ReqCreateWorkoutDeviceDTO dto) {
        logger.info("Creating new workout device: " + dto.getName());

        // Check if device name already exists
        if (workoutDeviceRepository.existsByName(dto.getName())) {
            throw new IllegalArgumentException("Thiết bị với tên này đã tồn tại");
        }

        WorkoutDevice device = WorkoutDevice.builder()
                .name(dto.getName())
                .type(dto.getType())
                .price(dto.getPrice())
                .dateImported(dto.getDateImported() != null ? dto.getDateImported() : LocalDate.now())
                .dateMaintenance(dto.getDateMaintenance())
                .imageUrl(dto.getImageUrl())
                .build();

        WorkoutDevice savedDevice = workoutDeviceRepository.save(device);
        logger.info("Created workout device with ID: " + savedDevice.getId());

        return convertToDTO(savedDevice);
    }

    /**
     * Get workout device by ID
     */
    public ResWorkoutDeviceDTO getWorkoutDeviceById(Long id) {
        logger.info("Fetching workout device with ID: " + id);

        WorkoutDevice device = workoutDeviceRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy thiết bị với ID: " + id));

        return convertToDTO(device);
    }

    /**
     * Search workout devices by name (contains keyword, case insensitive)
     */
    public List<ResWorkoutDeviceDTO> searchWorkoutDevicesByName(String name) {
        logger.info("Searching workout devices with name containing: " + name);

        List<WorkoutDevice> devices = workoutDeviceRepository.findByNameContainingIgnoreCase(name);

        return devices.stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }

    /**
     * Get all workout devices with SpringFilter specification and pagination
     */
    public ResultPaginationDTO handleFetchWorkoutDevices(Specification<WorkoutDevice> spec, Pageable pageable) {
        logger.info("Fetching workout devices with filter and pagination");

        Page<WorkoutDevice> page = workoutDeviceRepository.findAll(spec, pageable);

        List<ResWorkoutDeviceDTO> deviceDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());

        ResultPaginationDTO resDTO = new ResultPaginationDTO();
        resDTO.setMeta(meta);
        resDTO.setResult(deviceDTOs);
        return resDTO;
    }

    /**
     * Get devices by type
     */
    public ResultPaginationDTO getWorkoutDevicesByType(String type, Pageable pageable) {
        logger.info("Fetching workout devices by type: " + type);

        Page<WorkoutDevice> page = workoutDeviceRepository.findByType(type, pageable);

        List<ResWorkoutDeviceDTO> deviceDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());

        ResultPaginationDTO resDTO = new ResultPaginationDTO();
        resDTO.setMeta(meta);
        resDTO.setResult(deviceDTOs);
        return resDTO;
    }

    /**
     * Get devices requiring maintenance (dateMaintenance <= specified date)
     */
    public ResultPaginationDTO getDevicesRequiringMaintenance(LocalDate beforeDate, Pageable pageable) {
        logger.info("Fetching devices requiring maintenance before: " + beforeDate);

        Page<WorkoutDevice> page = workoutDeviceRepository.findByDateMaintenanceLessThanEqual(beforeDate, pageable);

        List<ResWorkoutDeviceDTO> deviceDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());

        ResultPaginationDTO resDTO = new ResultPaginationDTO();
        resDTO.setMeta(meta);
        resDTO.setResult(deviceDTOs);
        return resDTO;
    }

    /**
     * Get devices imported after a specific date
     */
    public ResultPaginationDTO getDevicesImportedAfter(LocalDate afterDate, Pageable pageable) {
        logger.info("Fetching devices imported after: " + afterDate);

        Page<WorkoutDevice> page = workoutDeviceRepository.findByDateImportedAfter(afterDate, pageable);

        List<ResWorkoutDeviceDTO> deviceDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());

        ResultPaginationDTO resDTO = new ResultPaginationDTO();
        resDTO.setMeta(meta);
        resDTO.setResult(deviceDTOs);
        return resDTO;
    }

    /**
     * Update workout device
     * Only updates fields that are not null in the DTO
     */
    @Transactional
    public ResWorkoutDeviceDTO updateWorkoutDevice(Long id, ReqUpdateWorkoutDeviceDTO dto) {
        logger.info("Updating workout device with ID: " + id);

        WorkoutDevice device = workoutDeviceRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy thiết bị với ID: " + id));

        // Check if new name conflicts with existing device
        if (dto.getName() != null && !dto.getName().equals(device.getName())) {
            if (workoutDeviceRepository.existsByName(dto.getName())) {
                throw new IllegalArgumentException("Thiết bị với tên này đã tồn tại");
            }
            device.setName(dto.getName());
        }

        if (dto.getType() != null) {
            device.setType(dto.getType());
        }

        if (dto.getPrice() != null) {
            device.setPrice(dto.getPrice());
        }

        if (dto.getDateImported() != null) {
            device.setDateImported(dto.getDateImported());
        }

        if (dto.getDateMaintenance() != null) {
            device.setDateMaintenance(dto.getDateMaintenance());
        }

        if (dto.getImageUrl() != null) {
            device.setImageUrl(dto.getImageUrl());
        }

        WorkoutDevice updatedDevice = workoutDeviceRepository.save(device);
        logger.info("Updated workout device with ID: " + updatedDevice.getId());

        return convertToDTO(updatedDevice);
    }

    /**
     * Delete workout device
     */
    @Transactional
    public void deleteWorkoutDevice(Long id) {
        logger.info("Deleting workout device with ID: " + id);

        if (!workoutDeviceRepository.existsById(id)) {
            throw new NoSuchElementException("Không tìm thấy thiết bị với ID: " + id);
        }

        workoutDeviceRepository.deleteById(id);
        logger.info("Deleted workout device with ID: " + id);
    }

    /**
     * Count devices by type
     */
    public long countDevicesByType(String type) {
        logger.info("Counting devices by type: " + type);
        return workoutDeviceRepository.countByType(type);
    }
}
