/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Workout service interface for exercise library
 */

package com.se100.GymAndPTManagement.service;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface WorkoutService {
    
    /**
     * Tạo bài tập mới
     */
    ResWorkoutDTO createWorkout(ReqWorkoutDTO reqWorkoutDTO);
    
    /**
     * Cập nhật bài tập
     */
    ResWorkoutDTO updateWorkout(Long id, ReqWorkoutDTO reqWorkoutDTO);
    
    /**
     * Lấy thông tin bài tập theo ID
     */
    ResWorkoutDTO getWorkoutById(Long id);
    
    /**
     * Lấy tất cả bài tập (phân trang)
     */
    Page<ResWorkoutDTO> getAllWorkouts(Pageable pageable);
    
    /**
     * Tìm bài tập theo tên
     */
    ResWorkoutDTO getWorkoutByName(String name);
    
    /**
     * Tìm bài tập theo độ khó
     */
    List<ResWorkoutDTO> getWorkoutsByDifficulty(String difficulty);
    
    /**
     * Tìm bài tập theo thiết bị
     */
    List<ResWorkoutDTO> getWorkoutsByDevice(Long deviceId);
    
    /**
     * Tìm bài tập (tên chứa)
     */
    List<ResWorkoutDTO> searchWorkouts(String name);
    
    /**
     * Xóa bài tập
     */
    void deleteWorkout(Long id);
}






