/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutImage service interface for image management
 */

package com.se100.GymAndPTManagement.service;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutImageDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutImageDTO;

import java.util.List;

public interface WorkoutImageService {
    
    /**
     * Thêm hình ảnh cho bài tập
     */
    ResWorkoutImageDTO addWorkoutImage(ReqWorkoutImageDTO reqWorkoutImageDTO);
    
    /**
     * Cập nhật hình ảnh
     */
    ResWorkoutImageDTO updateWorkoutImage(Long id, ReqWorkoutImageDTO reqWorkoutImageDTO);
    
    /**
     * Lấy hình ảnh theo ID
     */
    ResWorkoutImageDTO getWorkoutImageById(Long id);
    
    /**
     * Lấy danh sách hình ảnh của bài tập
     */
    List<ResWorkoutImageDTO> getImagesByWorkoutId(Long workoutId);
    
    /**
     * Lấy danh sách hình ảnh sắp xếp theo thứ tự hiển thị
     */
    List<ResWorkoutImageDTO> getImagesByWorkoutIdOrdered(Long workoutId);
    
    /**
     * Lấy hình ảnh theo trạng thái
     */
    List<ResWorkoutImageDTO> getImagesByStatus(String status);
    
    /**
     * Xóa hình ảnh
     */
    void deleteWorkoutImage(Long id);
}







