/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutDevice service interface for inventory management
 */

package com.se100.GymAndPTManagement.service;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDeviceDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface WorkoutDeviceService {
    
    /**
     * Tạo thiết bị mới
     */
    ResWorkoutDeviceDTO createWorkoutDevice(ReqWorkoutDeviceDTO reqWorkoutDeviceDTO);
    
    /**
     * Cập nhật thiết bị
     */
    ResWorkoutDeviceDTO updateWorkoutDevice(Long id, ReqWorkoutDeviceDTO reqWorkoutDeviceDTO);
    
    /**
     * Lấy thông tin thiết bị theo ID
     */
    ResWorkoutDeviceDTO getWorkoutDeviceById(Long id);
    
    /**
     * Lấy tất cả thiết bị (phân trang)
     */
    Page<ResWorkoutDeviceDTO> getAllWorkoutDevices(Pageable pageable);
    
    /**
     * Tìm thiết bị theo tên
     */
    ResWorkoutDeviceDTO getWorkoutDeviceByName(String name);
    
    /**
     * Tìm thiết bị theo loại
     */
    List<ResWorkoutDeviceDTO> getWorkoutDevicesByType(String equipmentType);
    
    /**
     * Tìm thiết bị theo trạng thái
     */
    List<ResWorkoutDeviceDTO> getWorkoutDevicesByStatus(String status);
    
    /**
     * Tìm thiết bị (tên chứa)
     */
    List<ResWorkoutDeviceDTO> searchWorkoutDevices(String name);
    
    /**
     * Lấy số lượng thiết bị theo trạng thái
     */
    Long getDeviceCountByStatus(String status);
    
    /**
     * Xóa thiết bị
     */
    void deleteWorkoutDevice(Long id);
}






