package com.se100.GymAndPTManagement.service;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateWorkoutDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateWorkoutDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.Workout;
import com.se100.GymAndPTManagement.repository.WorkoutRepository;
import com.se100.GymAndPTManagement.util.enums.WorkoutDifficultyEnum;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-16
 * Purpose: Workout service for exercise library management
 */
@Service
public class WorkoutService {

    private final WorkoutRepository workoutRepository;
    Logger logger = Logger.getLogger(WorkoutService.class.getName());

    public WorkoutService(WorkoutRepository workoutRepository) {
        this.workoutRepository = workoutRepository;
    }

    // =========================================
    // Conversion Helpers
    // =========================================

    private ResWorkoutDTO convertToDTO(Workout workout) {
        return ResWorkoutDTO.builder()
                .id(workout.getId())
                .name(workout.getName())
                .description(workout.getDescription())
                .duration(workout.getDuration())
                .difficulty(workout.getDifficulty())
                .type(workout.getType())
                .createdAt(workout.getCreatedAt())
                .updatedAt(workout.getUpdatedAt())
                .createdBy(workout.getCreatedBy())
                .updatedBy(workout.getUpdatedBy())
                .build();
    }

    // =========================================
    // CRUD Operations
    // =========================================

    /**
     * Create a new workout
     * Validates name uniqueness
     */
    @Transactional
    public ResWorkoutDTO createWorkout(ReqCreateWorkoutDTO dto) {
        logger.info("Creating new workout: " + dto.getName());

        // Check if workout name already exists
        if (workoutRepository.existsByName(dto.getName())) {
            throw new IllegalArgumentException("Bài tập với tên này đã tồn tại");
        }

        Workout workout = Workout.builder()
                .name(dto.getName())
                .description(dto.getDescription())
                .duration(dto.getDuration())
                .difficulty(dto.getDifficulty())
                .type(dto.getType())
                .build();

        Workout savedWorkout = workoutRepository.save(workout);
        logger.info("Created workout with ID: " + savedWorkout.getId());

        return convertToDTO(savedWorkout);
    }

    /**
     * Get workout by ID
     */
    public ResWorkoutDTO getWorkoutById(Long id) {
        logger.info("Fetching workout with ID: " + id);

        Workout workout = workoutRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy bài tập với ID: " + id));

        return convertToDTO(workout);
    }

    /**
     * Get workout by name
     */
    public ResWorkoutDTO getWorkoutByName(String name) {
        logger.info("Fetching workout with name: " + name);

        Workout workout = workoutRepository.findByName(name)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy bài tập với tên: " + name));

        return convertToDTO(workout);
    }

    /**
     * Search workouts by name (contains)
     */
    public ResultPaginationDTO searchWorkoutsByName(String name, Pageable pageable) {
        logger.info("Searching workouts by name: " + name);

        Page<Workout> page = workoutRepository.findByNameContainingIgnoreCase(name, pageable);

        List<ResWorkoutDTO> workoutDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        resultPaginationDTO.setMeta(meta);
        resultPaginationDTO.setResult(workoutDTOs);
        return resultPaginationDTO;
    }

    /**
     * Get all workouts with SpringFilter specification and pagination
     */
    public ResultPaginationDTO handleFetchWorkouts(Specification<Workout> spec, Pageable pageable) {
        logger.info("Fetching workouts with filter and pagination");

        Page<Workout> page = workoutRepository.findAll(spec, pageable);

        List<ResWorkoutDTO> workoutDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        resultPaginationDTO.setMeta(meta);
        resultPaginationDTO.setResult(workoutDTOs);
        return resultPaginationDTO;
    }

    /**
     * Get workouts by difficulty level
     */
    public ResultPaginationDTO getWorkoutsByDifficulty(WorkoutDifficultyEnum difficulty, Pageable pageable) {
        logger.info("Fetching workouts by difficulty: " + difficulty);

        Page<Workout> page = workoutRepository.findByDifficulty(difficulty, pageable);

        List<ResWorkoutDTO> workoutDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        resultPaginationDTO.setMeta(meta);
        resultPaginationDTO.setResult(workoutDTOs);
        return resultPaginationDTO;
    }

    /**
     * Get workouts by type (exact match)
     */
    public ResultPaginationDTO getWorkoutsByType(String type, Pageable pageable) {
        logger.info("Fetching workouts by type: " + type);

        Page<Workout> page = workoutRepository.findByType(type, pageable);

        List<ResWorkoutDTO> workoutDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        resultPaginationDTO.setMeta(meta);
        resultPaginationDTO.setResult(workoutDTOs);
        return resultPaginationDTO;
    }

    /**
     * Search workouts by type (contains)
     */
    public ResultPaginationDTO searchWorkoutsByType(String type, Pageable pageable) {
        logger.info("Searching workouts by type: " + type);

        Page<Workout> page = workoutRepository.findByTypeContainingIgnoreCase(type, pageable);

        List<ResWorkoutDTO> workoutDTOs = page.getContent().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());

        ResultPaginationDTO.Meta meta = new ResultPaginationDTO.Meta();
        meta.setPage(page.getNumber() + 1);
        meta.setPageSize(page.getSize());
        meta.setTotalPages(page.getTotalPages());
        meta.setTotalItems(page.getTotalElements());
        ResultPaginationDTO resultPaginationDTO = new ResultPaginationDTO();
        resultPaginationDTO.setMeta(meta);
        resultPaginationDTO.setResult(workoutDTOs);
        return resultPaginationDTO;
    }

    /**
     * Update workout
     * Only updates fields that are not null in the DTO
     */
    @Transactional
    public ResWorkoutDTO updateWorkout(Long id, ReqUpdateWorkoutDTO dto) {
        logger.info("Updating workout with ID: " + id);

        Workout workout = workoutRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException("Không tìm thấy bài tập với ID: " + id));

        // Check if new name conflicts with existing workout
        if (dto.getName() != null && !dto.getName().equals(workout.getName())) {
            if (workoutRepository.existsByName(dto.getName())) {
                throw new IllegalArgumentException("Bài tập với tên này đã tồn tại");
            }
            workout.setName(dto.getName());
        }

        if (dto.getDescription() != null) {
            workout.setDescription(dto.getDescription());
        }

        if (dto.getDuration() != null) {
            workout.setDuration(dto.getDuration());
        }

        if (dto.getDifficulty() != null) {
            workout.setDifficulty(dto.getDifficulty());
        }

        if (dto.getType() != null) {
            workout.setType(dto.getType());
        }

        Workout updatedWorkout = workoutRepository.save(workout);
        logger.info("Updated workout with ID: " + updatedWorkout.getId());

        return convertToDTO(updatedWorkout);
    }

    /**
     * Delete workout
     */
    @Transactional
    public void deleteWorkout(Long id) {
        logger.info("Deleting workout with ID: " + id);

        if (!workoutRepository.existsById(id)) {
            throw new NoSuchElementException("Không tìm thấy bài tập với ID: " + id);
        }

        workoutRepository.deleteById(id);
        logger.info("Deleted workout with ID: " + id);
    }

    /**
     * Count workouts by difficulty
     */
    public long countWorkoutsByDifficulty(WorkoutDifficultyEnum difficulty) {
        logger.info("Counting workouts by difficulty: " + difficulty);
        return workoutRepository.countByDifficulty(difficulty);
    }

    /**
     * Count workouts by type
     */
    public long countWorkoutsByType(String type) {
        logger.info("Counting workouts by type: " + type);
        return workoutRepository.countByType(type);
    }
}
