/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * CheckinLog Query Integration Tests
 */
package com.se100.GymAndPTManagement.integration.service;

import com.se100.GymAndPTManagement.domain.table.CheckinLog;
import com.se100.GymAndPTManagement.domain.table.Member;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("CheckinLog Query Integration Tests")
public class CheckinLogQueryIntegrationTest extends CheckinLogIntegrationTestBase {

    @Test
    @DisplayName("Test 1: Find check-in by ID should return correct record")
    public void testFindById() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        Optional<CheckinLog> found = checkinLogRepository.findById(checkin.getId());
        
        assertTrue(found.isPresent());
        assertEquals(checkin.getId(), found.get().getId());
        assertEquals("CHECKED_IN", found.get().getStatus());
    }

    @Test
    @DisplayName("Test 2: Find non-existent check-in should return empty")
    public void testFindByIdNotFound() {
        Optional<CheckinLog> found = checkinLogRepository.findById(99999L);
        
        assertFalse(found.isPresent());
    }

    @Test
    @DisplayName("Test 3: Find check-ins by booking ID should return all records")
    public void testFindByBookingId() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> results = checkinLogRepository.findByBookingId(testBooking.getId());
        
        assertTrue(results.size() >= 2);
        assertTrue(results.stream().anyMatch(c -> c.getId().equals(checkin1.getId())));
        assertTrue(results.stream().anyMatch(c -> c.getId().equals(checkin2.getId())));
    }

    @Test
    @DisplayName("Test 4: Find check-ins by non-existent booking should return empty")
    public void testFindByBookingIdNotFound() {
        List<CheckinLog> results = checkinLogRepository.findByBookingId(99999L);
        
        assertTrue(results.isEmpty());
    }

    @Test
    @DisplayName("Test 5: Find check-ins by member ID should return all records")
    public void testFindByMemberId() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> results = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertTrue(results.size() >= 2);
        assertTrue(results.stream().anyMatch(c -> c.getId().equals(checkin1.getId())));
        assertTrue(results.stream().anyMatch(c -> c.getId().equals(checkin2.getId())));
    }

    @Test
    @DisplayName("Test 6: Find active check-in by booking ID should return CHECKED_IN status")
    public void testFindActiveCheckinByBookingId() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        Optional<CheckinLog> active = checkinLogRepository.findActiveCheckInByBookingId(testBooking.getId());
        
        assertTrue(active.isPresent());
        assertEquals("CHECKED_IN", active.get().getStatus());
    }

    @Test
    @DisplayName("Test 7: Active check-in query should ignore CHECKED_OUT records")
    public void testActiveCheckinIgnoresCheckedOut() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        checkin.setStatus("CHECKED_OUT");
        checkinLogRepository.save(checkin);
        
        Optional<CheckinLog> active = checkinLogRepository.findActiveCheckInByBookingId(testBooking.getId());
        
        assertFalse(active.isPresent());
    }

    @Test
    @DisplayName("Test 8: Active check-in query should ignore CANCELLED records")
    public void testActiveCheckinIgnoresCancelled() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        checkin.setStatus("CANCELLED");
        checkinLogRepository.save(checkin);
        
        Optional<CheckinLog> active = checkinLogRepository.findActiveCheckInByBookingId(testBooking.getId());
        
        assertFalse(active.isPresent());
    }

    @Test
    @DisplayName("Test 9: Find by member ID should return empty for non-existent member")
    public void testFindByMemberIdNotFound() {
        List<CheckinLog> results = checkinLogRepository.findByMemberId(99999L);
        
        assertTrue(results.isEmpty());
    }

    @Test
    @DisplayName("Test 10: Multiple members should have separate check-in records")
    public void testMultipleMembersIsolation() {
        Member member2 = createMember();
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, member2, "CHECKED_IN");
        
        List<CheckinLog> member1Results = checkinLogRepository.findByMemberId(testMember.getId());
        List<CheckinLog> member2Results = checkinLogRepository.findByMemberId(member2.getId());
        
        assertTrue(member1Results.stream().anyMatch(c -> c.getId().equals(checkin1.getId())));
        assertTrue(member2Results.stream().anyMatch(c -> c.getId().equals(checkin2.getId())));
    }

    @Test
    @DisplayName("Test 11: Query results should preserve all fields")
    public void testQueryFieldPreservation() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        Optional<CheckinLog> found = checkinLogRepository.findById(checkin.getId());
        
        assertTrue(found.isPresent());
        assertEquals(checkin.getStatus(), found.get().getStatus());
        assertEquals(checkin.getCheckinTime(), found.get().getCheckinTime());
        assertEquals(checkin.getMember().getId(), found.get().getMember().getId());
    }

    @Test
    @DisplayName("Test 12: Count check-ins by member")
    public void testCountByMember() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        List<CheckinLog> results = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertTrue(results.size() >= 2);
    }

    @Test
    @DisplayName("Test 13: Query with different statuses")
    public void testQueryDifferentStatuses() {
        CheckinLog checkinIn = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkinOut = createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        CheckinLog cancelled = createCheckinLog(testBooking, testMember, "CANCELLED");
        
        List<CheckinLog> all = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertTrue(all.size() >= 3);
        assertTrue(all.stream().anyMatch(c -> "CHECKED_IN".equals(c.getStatus())));
        assertTrue(all.stream().anyMatch(c -> "CHECKED_OUT".equals(c.getStatus())));
        assertTrue(all.stream().anyMatch(c -> "CANCELLED".equals(c.getStatus())));
    }

    @Test
    @DisplayName("Test 14: Order preservation in query results")
    public void testOrderPreservation() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> results = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertFalse(results.isEmpty());
        assertTrue(results.size() >= 2);
    }

    @Test
    @DisplayName("Test 15: Query consistency across multiple calls")
    public void testQueryConsistency() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        Optional<CheckinLog> found1 = checkinLogRepository.findById(checkin.getId());
        Optional<CheckinLog> found2 = checkinLogRepository.findById(checkin.getId());
        
        assertTrue(found1.isPresent());
        assertTrue(found2.isPresent());
        assertEquals(found1.get().getId(), found2.get().getId());
        assertEquals(found1.get().getStatus(), found2.get().getStatus());
    }

    @Test
    @DisplayName("Test 16: Distinct members from check-ins")
    public void testDistinctMembers() {
        Member member2 = createMember();
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin3 = createCheckinLog(testBooking, member2, "CHECKED_IN");
        
        List<CheckinLog> member1Results = checkinLogRepository.findByMemberId(testMember.getId());
        List<CheckinLog> member2Results = checkinLogRepository.findByMemberId(member2.getId());
        
        assertTrue(member1Results.size() >= 2);
        assertTrue(member2Results.size() >= 1);
    }

    @Test
    @DisplayName("Test 17: Filter by status from query results")
    public void testFilterByStatus() {
        CheckinLog checkinIn = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkinOut = createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        List<CheckinLog> all = checkinLogRepository.findByMemberId(testMember.getId());
        List<CheckinLog> checkedIn = all.stream()
            .filter(c -> "CHECKED_IN".equals(c.getStatus()))
            .toList();
        
        assertTrue(checkedIn.stream().anyMatch(c -> c.getId().equals(checkinIn.getId())));
    }

    @Test
    @DisplayName("Test 18: Query with null booking should work")
    public void testQueryWithNullBooking() {
        CheckinLog checkin = new CheckinLog();
        checkin.setMember(testMember);
        checkin.setStatus("CHECKED_IN");
        checkin = checkinLogRepository.save(checkin);
        
        Optional<CheckinLog> found = checkinLogRepository.findById(checkin.getId());
        
        assertTrue(found.isPresent());
        assertNull(found.get().getBooking());
    }

    @Test
    @DisplayName("Test 19: Large dataset query performance")
    public void testLargeDatasetQuery() {
        for (int i = 0; i < 10; i++) {
            createCheckinLog(testBooking, testMember, "CHECKED_IN");
        }
        
        List<CheckinLog> results = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertTrue(results.size() >= 10);
    }

    @Test
    @DisplayName("Test 20: Find active check-in with multiple candidates")
    public void testFindActiveSingleResult() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        Optional<CheckinLog> active = checkinLogRepository.findActiveCheckInByBookingId(testBooking.getId());
        
        assertTrue(active.isPresent());
        assertEquals("CHECKED_IN", active.get().getStatus());
    }
}
