/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * CheckinLog Creation Integration Tests
 */
package com.se100.GymAndPTManagement.integration.service;

import com.se100.GymAndPTManagement.domain.table.CheckinLog;
import com.se100.GymAndPTManagement.domain.table.Member;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalTime;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("CheckinLog Creation Integration Tests")
public class CheckinLogCreationIntegrationTest extends CheckinLogIntegrationTestBase {

    @Test
    @DisplayName("Test 1: Create check-in successfully")
    public void testCreateCheckinSuccess() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getId());
        assertEquals("CHECKED_IN", checkin.getStatus());
        assertCheckinTimeSet(checkin);
        assertCheckoutTimeNull(checkin);
        assertMemberRelationship(checkin, testMember);
    }

    @Test
    @DisplayName("Test 2: Checkin time should be set on creation")
    public void testCheckinTimeSet() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getCheckinTime());
        assertTrue(checkin.getCheckinTime().isBefore(LocalTime.now().plusSeconds(1)));
    }

    @Test
    @DisplayName("Test 3: Status should match what was provided")
    public void testStatusValidation() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertCheckinStatus(checkin, "CHECKED_IN");
        assertEquals("CHECKED_IN", checkin.getStatus());
    }

    @Test
    @DisplayName("Test 4: Member relationship should be established")
    public void testMemberRelationship() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertMemberRelationship(checkin, testMember);
        assertNotNull(checkin.getMember().getId());
    }

    @Test
    @DisplayName("Test 5: Checkout time should be null on creation")
    public void testCheckoutTimeNull() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertCheckoutTimeNull(checkin);
        assertNull(checkin.getCheckoutTime());
    }

    @Test
    @DisplayName("Test 6: Multiple check-ins for same member should be allowed")
    public void testMultipleCheckinsPerMember() {
        CheckinLog checkin1 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        CheckinLog checkin2 = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin1.getId());
        assertNotNull(checkin2.getId());
        assertNotEquals(checkin1.getId(), checkin2.getId());
    }

    @Test
    @DisplayName("Test 7: Audit fields should be populated on creation")
    public void testAuditFieldsPopulated() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertAuditFieldsPopulated(checkin);
        assertNotNull(checkin.getCreatedAt());
        assertNotNull(checkin.getCreatedBy());
    }

    @Test
    @DisplayName("Test 8: All status values should be supported")
    public void testAllStatusValues() {
        String[] statuses = {"CHECKED_IN", "CHECKED_OUT", "CANCELLED"};
        
        for (String status : statuses) {
            CheckinLog checkin = createCheckinLog(testBooking, testMember, status);
            assertEquals(status, checkin.getStatus());
        }
    }

    @Test
    @DisplayName("Test 9: Check-in without booking should be allowed")
    public void testCheckinWithoutBooking() {
        CheckinLog checkin = new CheckinLog();
        checkin.setMember(testMember);
        checkin.setCheckinTime(LocalTime.now());
        checkin.setStatus("CHECKED_IN");
        checkin = checkinLogRepository.save(checkin);
        
        assertNotNull(checkin.getId());
        assertNull(checkin.getBooking());
        assertMemberRelationship(checkin, testMember);
    }

    @Test
    @DisplayName("Test 10: Booking relationship should be established when provided")
    public void testBookingRelationship() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertBookingRelationship(checkin, testBooking);
        assertNotNull(checkin.getBooking().getId());
    }

    @Test
    @DisplayName("Test 11: PT should be accessible through booking")
    public void testPTAccessThroughBooking() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getBooking());
        assertNotNull(checkin.getBooking().getRealPt());
        assertEquals(testPT.getId(), checkin.getBooking().getRealPt().getId());
    }

    @Test
    @DisplayName("Test 12: Contract should be accessible through booking")
    public void testContractAccessThroughBooking() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getBooking());
        assertNotNull(checkin.getBooking().getContract());
        assertEquals(testContract.getId(), checkin.getBooking().getContract().getId());
    }

    @Test
    @DisplayName("Test 13: Slot should be accessible through booking")
    public void testSlotAccessThroughBooking() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getBooking());
        assertNotNull(checkin.getBooking().getSlot());
        assertEquals(testSlot.getId(), checkin.getBooking().getSlot().getId());
    }

    @Test
    @DisplayName("Test 14: Check-in with minimal data should work")
    public void testMinimalDataCheckin() {
        CheckinLog checkin = new CheckinLog();
        checkin.setMember(testMember);
        checkin.setStatus("CHECKED_IN");
        checkin = checkinLogRepository.save(checkin);
        
        assertNotNull(checkin.getId());
        assertNotNull(checkin.getMember());
        assertEquals("CHECKED_IN", checkin.getStatus());
    }

    @Test
    @DisplayName("Test 15: Future bookings should allow check-in")
    public void testCheckinWithFutureBooking() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        assertNotNull(checkin.getId());
        assertBookingRelationship(checkin, testBooking);
        assertEquals("CHECKED_IN", checkin.getStatus());
    }
}
