/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * CheckinLog Attendance Tracking Integration Tests
 */
package com.se100.GymAndPTManagement.integration.service;

import com.se100.GymAndPTManagement.domain.table.CheckinLog;
import com.se100.GymAndPTManagement.domain.table.Member;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("CheckinLog Attendance Tracking Tests")
public class CheckinLogAttendanceIntegrationTest extends CheckinLogIntegrationTestBase {

    @Test
    @DisplayName("Test 1: Calculate attendance rate 100%")
    public void testAttendanceRate100Percent() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = (attended * 100.0) / total;
        assertEquals(100.0, rate);
    }

    @Test
    @DisplayName("Test 2: Calculate attendance rate 0%")
    public void testAttendanceRate0Percent() {
        createCheckinLog(testBooking, testMember, "CANCELLED");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = total > 0 ? (attended * 100.0) / total : 0.0;
        assertEquals(0.0, rate);
    }

    @Test
    @DisplayName("Test 3: Calculate attendance rate 50%")
    public void testAttendanceRate50Percent() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CANCELLED");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = total > 0 ? (attended * 100.0) / total : 0.0;
        assertEquals(50.0, rate, 0.01);
    }

    @Test
    @DisplayName("Test 4: Handle division by zero in attendance calculation")
    public void testAttendanceRateDivisionByZero() {
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        
        double rate = logs.isEmpty() ? 0.0 : 
            (logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count() * 100.0) / logs.size();
        
        assertEquals(0.0, rate);
    }

    @Test
    @DisplayName("Test 5: Ignored cancelled sessions in attendance calculation")
    public void testIgnoreCancelledInAttendance() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CANCELLED");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.stream().filter(c -> !"CANCELLED".equals(c.getStatus())).count();
        
        double rate = total > 0 ? (attended * 100.0) / total : 0.0;
        assertEquals(100.0, rate);
    }

    @Test
    @DisplayName("Test 6: Count total sessions for member")
    public void testCountTotalSessions() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        
        assertEquals(3, logs.size());
    }

    @Test
    @DisplayName("Test 7: Count attended sessions for member")
    public void testCountAttendedSessions() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        
        assertEquals(2, attended);
    }

    @Test
    @DisplayName("Test 8: Count pending sessions for member")
    public void testCountPendingSessions() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_IN");
        createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long pending = logs.stream().filter(c -> "CHECKED_IN".equals(c.getStatus())).count();
        
        assertEquals(2, pending);
    }

    @Test
    @DisplayName("Test 9: Count cancelled sessions for member")
    public void testCountCancelledSessions() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CANCELLED");
        createCheckinLog(testBooking, testMember, "CANCELLED");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long cancelled = logs.stream().filter(c -> "CANCELLED".equals(c.getStatus())).count();
        
        assertEquals(2, cancelled);
    }

    @Test
    @DisplayName("Test 10: Different members should have separate statistics")
    public void testMemberStatisticsIsolation() {
        Member member2 = createMember();
        
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        createCheckinLog(testBooking, member2, "CHECKED_IN");
        
        List<CheckinLog> member1Logs = checkinLogRepository.findByMemberId(testMember.getId());
        List<CheckinLog> member2Logs = checkinLogRepository.findByMemberId(member2.getId());
        
        long member1Attended = member1Logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long member2Attended = member2Logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        
        assertEquals(2, member1Attended);
        assertEquals(0, member2Attended);
    }

    @Test
    @DisplayName("Test 11: Single session attendance calculation")
    public void testSingleSessionAttendance() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = (attended * 100.0) / total;
        assertEquals(100.0, rate);
    }

    @Test
    @DisplayName("Test 12: Large dataset attendance calculation")
    public void testLargeDatasetAttendance() {
        for (int i = 0; i < 25; i++) {
            createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        }
        for (int i = 0; i < 25; i++) {
            createCheckinLog(testBooking, testMember, "CHECKED_IN");
        }
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = (attended * 100.0) / total;
        assertEquals(50.0, rate, 0.01);
    }

    @Test
    @DisplayName("Test 13: Cancellation updates should not affect attendance calculations")
    public void testCancellationUpdatesAttendance() {
        CheckinLog checkin = createCheckinLog(testBooking, testMember, "CHECKED_IN");
        checkin.setStatus("CANCELLED");
        checkinLogRepository.save(checkin);
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long cancelled = logs.stream().filter(c -> "CANCELLED".equals(c.getStatus())).count();
        
        assertEquals(0, attended);
        assertEquals(1, cancelled);
    }

    @Test
    @DisplayName("Test 14: Member-only tracking should exclude other members")
    public void testMemberOnlyTracking() {
        Member member2 = createMember();
        Member member3 = createMember();
        
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, member2, "CHECKED_OUT");
        createCheckinLog(testBooking, member3, "CHECKED_OUT");
        
        List<CheckinLog> memberLogs = checkinLogRepository.findByMemberId(testMember.getId());
        
        long memberAttended = memberLogs.stream()
            .filter(c -> "CHECKED_OUT".equals(c.getStatus()))
            .count();
        
        assertEquals(2, memberAttended);
    }

    @Test
    @DisplayName("Test 15: Attendance precision should handle decimal values")
    public void testAttendancePrecision() {
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_OUT");
        createCheckinLog(testBooking, testMember, "CHECKED_IN");
        
        List<CheckinLog> logs = checkinLogRepository.findByMemberId(testMember.getId());
        long attended = logs.stream().filter(c -> "CHECKED_OUT".equals(c.getStatus())).count();
        long total = logs.size();
        
        double rate = (attended * 100.0) / total;
        // 2/3 * 100 = 66.666...
        assertEquals(66.666, rate, 0.01);
    }
}
