/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Test infrastructure for CheckinLog integration tests
 */
package com.se100.GymAndPTManagement.integration.service;

import com.se100.GymAndPTManagement.domain.table.*;
import com.se100.GymAndPTManagement.repository.*;
import com.se100.GymAndPTManagement.util.enums.ContractStatusEnum;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
public abstract class CheckinLogIntegrationTestBase {

    @Autowired
    protected CheckinLogRepository checkinLogRepository;

    @Autowired
    protected BookingRepository bookingRepository;

    @Autowired
    protected MemberRepository memberRepository;

    @Autowired
    protected PersonalTrainerRepository personalTrainerRepository;

    @Autowired
    protected ServicePackageRepository servicePackageRepository;

    @Autowired
    protected SlotRepository slotRepository;

    @Autowired
    protected ContractRepository contractRepository;

    @Autowired
    protected UserRepository userRepository;

    // Test data counters
    protected int userCounter = 0;
    protected int cccdCounter = 0;
    protected int slotCounter = 0;
    protected int packageCounter = 0;

    // Test entities
    protected User testUser;
    protected User testPTUser;
    protected Member testMember;
    protected PersonalTrainer testPT;
    protected ServicePackage testPackage;
    protected Slot testSlot;
    protected Contract testContract;
    protected Booking testBooking;

    @BeforeEach
    public void setUp() {
        // Reset counters
        userCounter = 0;
        cccdCounter = 0;
        slotCounter = 0;
        packageCounter = 0;

        // Create test user
        testUser = createUser("member1@test.com");
        testMember = createMemberWithUser(testUser);

        // Create test PT user and PT
        testPTUser = createUser("pt1@test.com");
        testPT = createPersonalTrainerWithUser(testPTUser);

        // Create test service package
        testPackage = createServicePackage("Premium 10 Sessions", 10);

        // Create test slot
        testSlot = createSlot("Morning Slot", LocalTime.of(6, 0), LocalTime.of(7, 0));

        // Create test contract
        testContract = createContract(testMember, testPackage, testPT);

        // Create test booking
        testBooking = createBooking(testContract, testMember, testSlot, testPT);
    }

    // ==================== Factory Methods ====================

    protected User createUser(String email) {
        User user = new User();
        user.setEmail(email);
        user.setPasswordHash("hashedpassword123");
        user.setFullname("Test User " + (userCounter++));
        user.setPhoneNumber("098765432" + userCounter);
        user.setAvatarUrl("https://example.com/avatar.jpg");
        return userRepository.save(user);
    }

    protected Member createMemberWithUser(User user) {
        Member member = new Member();
        member.setUser(user);
        member.setCccd("CCCD" + (cccdCounter++));
        member.setMoneySpent(BigDecimal.ZERO);
        member.setMoneyDebt(BigDecimal.ZERO);
        return memberRepository.save(member);
    }

    protected Member createMember() {
        User memberUser = createUser("member" + (userCounter++) + "@test.com");
        return createMemberWithUser(memberUser);
    }

    protected PersonalTrainer createPersonalTrainerWithUser(User user) {
        PersonalTrainer pt = new PersonalTrainer();
        pt.setUser(user);
        pt.setSpecialization("General Fitness");
        return personalTrainerRepository.save(pt);
    }

    protected PersonalTrainer createPersonalTrainer() {
        User ptUser = createUser("pt" + (userCounter++) + "@test.com");
        return createPersonalTrainerWithUser(ptUser);
    }

    protected ServicePackage createServicePackage(String name, int sessions) {
        ServicePackage pkg = new ServicePackage();
        pkg.setPackageName(name);
        pkg.setPrice(new BigDecimal("5000000")); // 5M VND
        pkg.setDescription("Test package " + (packageCounter++));
        pkg.setNumberOfSessions(sessions);
        return servicePackageRepository.save(pkg);
    }

    protected Slot createSlot(String name, LocalTime start, LocalTime end) {
        Slot slot = new Slot();
        slot.setSlotName(name);
        slot.setStartTime(start);
        slot.setEndTime(end);
        slot.setIsActive(true);
        return slotRepository.save(slot);
    }

    protected Contract createContract(Member member, ServicePackage pkg, PersonalTrainer pt) {
        Contract contract = new Contract();
        contract.setMember(member);
        contract.setServicePackage(pkg);
        contract.setMainPt(pt);
        contract.setStartDate(LocalDate.now());
        contract.setEndDate(LocalDate.now().plusMonths(3));
        contract.setTotalSessions(pkg.getNumberOfSessions());
        contract.setRemainingSessions(pkg.getNumberOfSessions());
        contract.setStatus(ContractStatusEnum.ACTIVE);
        contract.setNotes("Test contract");
        contract.setSignedAt(Instant.now());
        return contractRepository.save(contract);
    }

    protected Booking createBooking(Contract contract, Member member, Slot slot, PersonalTrainer pt) {
        Booking booking = new Booking();
        booking.setContract(contract);
        booking.setMember(member);
        booking.setSlot(slot);
        booking.setRealPt(pt);
        booking.setBookingDate(LocalDate.now());
        return bookingRepository.save(booking);
    }

    protected CheckinLog createCheckinLog(Booking booking, Member member, String status) {
        CheckinLog checkinLog = new CheckinLog();
        checkinLog.setBooking(booking);
        checkinLog.setMember(member);
        checkinLog.setCheckinTime(LocalTime.now());
        checkinLog.setStatus(status);
        return checkinLogRepository.save(checkinLog);
    }

    // ==================== Assertion Helpers ====================

    protected void assertCheckinStatus(CheckinLog checkinLog, String expectedStatus) {
        assert checkinLog.getStatus().equals(expectedStatus) : "Status should be " + expectedStatus;
    }

    protected void assertCheckinTimeSet(CheckinLog checkinLog) {
        assert checkinLog.getCheckinTime() != null : "Checkin time should be set";
    }

    protected void assertCheckoutTimeSet(CheckinLog checkinLog) {
        assert checkinLog.getCheckoutTime() != null : "Checkout time should be set";
    }

    protected void assertCheckoutTimeNull(CheckinLog checkinLog) {
        assert checkinLog.getCheckoutTime() == null : "Checkout time should be null";
    }

    protected void assertAuditFieldsPopulated(CheckinLog checkinLog) {
        assert checkinLog.getCreatedAt() != null : "Created at should be set";
        assert checkinLog.getCreatedBy() != null : "Created by should be set";
    }

    protected void assertAuditFieldsUpdated(CheckinLog checkinLog) {
        assert checkinLog.getUpdatedAt() != null : "Updated at should be set";
        assert checkinLog.getUpdatedBy() != null : "Updated by should be set";
    }

    protected void assertMemberRelationship(CheckinLog checkinLog, Member expectedMember) {
        assert checkinLog.getMember() != null : "Member should not be null";
        assert checkinLog.getMember().getId().equals(expectedMember.getId()) : "Member ID should match";
    }

    protected void assertBookingRelationship(CheckinLog checkinLog, Booking expectedBooking) {
        assert checkinLog.getBooking() != null : "Booking should not be null";
        assert checkinLog.getBooking().getId().equals(expectedBooking.getId()) : "Booking ID should match";
    }

    protected void assertContractSessionsRestored(Contract contract, int expectedRemaining) {
        assert contract.getRemainingSessions() == expectedRemaining : 
            "Remaining sessions should be " + expectedRemaining + " but was " + contract.getRemainingSessions();
    }
}
