/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 10:05:00
 * Purpose: Response DTO for available slots
 */
package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.LocalTime;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResAvailableSlotDTO {

    private Long slotId;

    private LocalTime startTime;

    private LocalTime endTime;
}
