/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-15 15:00:00
 * Purpose: Response DTO for member attendance tracking statistics
 */
package com.se100.GymAndPTManagement.domain.responseDTO;

import lombok.*;
import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResAttendanceTrackingDTO {

    private Long memberId;

    private String memberName;

    private Integer totalSessions;

    private Integer remainingSessions;

    private Integer bookedSessions;

    private Integer attendedSessions;

    private BigDecimal attendanceRate;

    private String attendancePercentage;

    /**
     * Notes:
     * - totalSessions: Taken from Contract.totalSessions (original package sessions)
     * - remainingSessions: Taken from Contract.remainingSessions (sessions left to use)
     * - bookedSessions: Calculated as (totalSessions - remainingSessions)
     * - attendedSessions: Count of CheckinLog records with status = 'CHECKED_OUT' for this member
     * - attendanceRate: (attendedSessions / bookedSessions) * 100, or null if bookedSessions = 0
     * - attendancePercentage: String format like "85.50%"
     */
}
