package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.LocalDate;
import java.time.LocalTime;

import com.se100.GymAndPTManagement.util.enums.DayOfWeekEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-14
 * Purpose: Response DTO for available slots by PT and date range
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResAvailableSlotByDateRangeDTO {
    private DayOfWeekEnum dayOfWeek;
    private LocalDate date;
    private PT pt;
    private Slot slot;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class PT {
        private Long ptId;
        private String name;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Slot {
        private Long slotId;
        private String name;
        private LocalTime startTime;
        private LocalTime endTime;
    }
}
