package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.Instant;
import java.time.LocalTime;

import com.se100.GymAndPTManagement.domain.table.AvailableSlot;
import com.se100.GymAndPTManagement.util.enums.DayOfWeekEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-14 10:19:59
 * Purpose: Response DTO for available slot
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResAvailableSlotDTO {
    private Long id;
    private PT pt;
    private Slot slot;
    private DayOfWeekEnum dayOfWeek;
    private Boolean isAvailable;

    private Instant createdAt;
    private Instant updatedAt;
    private String createdBy;
    private String updatedBy;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class PT {
        private Long ptId;
        private String ptName;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Slot {
        private Long slotId;
        private String slotName;
        private LocalTime startTime;
        private LocalTime endTime;
    }

    public static ResAvailableSlotDTO fromEntity(AvailableSlot availableSlot) {
        return ResAvailableSlotDTO.builder()
                .id(availableSlot.getId())
                .pt(PT.builder()
                        .ptId(availableSlot.getPersonalTrainer().getId())
                        .ptName(availableSlot.getPersonalTrainer().getUser().getFullname())
                        .build())
                .slot(Slot.builder()
                        .slotId(availableSlot.getSlot().getId())
                        .slotName(availableSlot.getSlot().getSlotName())
                        .startTime(availableSlot.getSlot().getStartTime())
                        .endTime(availableSlot.getSlot().getEndTime())
                        .build())
                .dayOfWeek(availableSlot.getDayOfWeek())
                .isAvailable(availableSlot.getIsAvailable())
                .createdAt(availableSlot.getCreatedAt())
                .updatedAt(availableSlot.getUpdatedAt())
                .createdBy(availableSlot.getCreatedBy())
                .updatedBy(availableSlot.getUpdatedBy())
                .build();
    }
}
