/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 10:05:00
 * Purpose: Response DTO for booking details
 */
package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.LocalDate;
import java.time.LocalTime;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResBookingDTO {

    private Long id;

    private Long contractId;

    private Long memberId;

    private String memberName;

    private Long ptId;

    private String ptName;

    private Long slotId;

    private LocalTime slotStartTime;

    private LocalTime slotEndTime;

    private LocalDate bookingDate;

    private String createdBy;
}
