/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 11:05:00
 * Purpose: Response DTO for checkin log details
 */
package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.LocalTime;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResCheckinLogDTO {

    private Long checkinId;

    private Long bookingId;

    private Long memberId;

    private String memberName;

    private LocalTime checkinTime;

    private LocalTime checkoutTime;

    private String status;

    private String createdBy;
}
