/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-09 14:50:00
 * Purpose: Response DTO for contract information
 */
package com.se100.GymAndPTManagement.domain.responseDTO;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResContractDTO {
    
    private Long id;
    
    private Long memberId;
    
    private String memberName;
    
    private Long packageId;
    
    private String packageName;
    
    private BigDecimal packagePrice;
    
    private Long ptId;
    
    private String ptName;
    
    private LocalDate startDate;
    
    private LocalDate endDate;
    
    private Integer totalSessions;
    
    private Integer remainingSessions;
    
    private String status;
    
    private String notes;
    
    private Instant signedAt;
    
    private Instant createdAt;
}
