/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 14:05:17
 * Purpose: Response DTO for DailyDiet entity
 */

package com.se100.GymAndPTManagement.domain.responseDTO;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResDailyDietDTO {
    
    private Long id;
    
    @JsonProperty("plan_name")
    private String planName;
    
    @JsonProperty("member_id")
    private Long memberId;
    
    @JsonProperty("diet_date")
    private LocalDate dietDate;
    
    @JsonProperty("total_calories")
    private Float totalCalories;
    
    @JsonProperty("total_protein")
    private Float totalProtein;
    
    @JsonProperty("total_fat")
    private Float totalFat;
    
    @JsonProperty("total_carbohydrate")
    private Float totalCarbohydrate;
    
    @JsonProperty("water_intake")
    private Integer waterIntake;
    
    private String notes;
    
    private String status;
    
    @JsonProperty("created_at")
    private LocalDateTime createdAt;
    
    @JsonProperty("updated_at")
    private LocalDateTime updatedAt;
    
    @JsonProperty("created_by")
    private String createdBy;
    
    @JsonProperty("updated_by")
    private String updatedBy;
}