package com.se100.GymAndPTManagement.domain.responseDTO;

import java.math.BigDecimal;
import java.time.Instant;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 14:30:00
 * Purpose: Response DTO for food information
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResFoodDTO {

    private Long id;
    private String name;
    private String description;
    private BigDecimal calories; // Auto-calculated
    private BigDecimal proteinG; // Protein in grams per 100g
    private BigDecimal carbsG; // Carbs in grams per 100g
    private BigDecimal fatG; // Fat in grams per 100g
    private String note;
    private String type; // Auto-calculated: PROTEIN, CARBOHYDRATE, FAT
    private Instant createdAt;
    private Instant updatedAt;
}
