package com.se100.GymAndPTManagement.domain.responseDTO;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 02:44:02
 * Purpose: Response DTO for member information
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResMemberDTO {

    private Long id;
    private ResUserDTO user;
    private String cccd;
    private BigDecimal moneySpent;
    private BigDecimal moneyDebt;
    private LocalDate joinDate;
    private Instant createdAt;
    private Instant updatedAt;
}
