package com.se100.GymAndPTManagement.domain.responseDTO;

import java.math.BigDecimal;
import java.time.Instant;

import com.se100.GymAndPTManagement.util.enums.PTStatusEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 11:20:37
 * Purpose: Response DTO for Personal Trainer
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResPTDTO {
    private Long id;
    private ResUserDTO user;
    private String about;
    private String specialization;
    private String certifications;
    private Integer experienceYears;
    private BigDecimal rating;
    private PTStatusEnum status;
    private String note;
    private Instant createdAt;
    private Instant updatedAt;
}
