package com.se100.GymAndPTManagement.domain.responseDTO;

import java.math.BigDecimal;
import java.time.Instant;

import com.se100.GymAndPTManagement.domain.table.ServicePackage;
import com.se100.GymAndPTManagement.util.enums.PackageTypeEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 09:30:43
 * Purpose: Response DTO for service package
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResServicePackageDTO {
    private Long id;
    private String packageName;
    private BigDecimal price;
    private PackageTypeEnum type;
    private Boolean isActive;

    private String description;
    private Integer durationInDays;
    private Integer numberOfSessions;

    private Instant createdAt;
    private Instant updatedAt;
    private String createdBy;
    private String updatedBy;

    public static ResServicePackageDTO fromEntity(ServicePackage servicePackage) {
        return ResServicePackageDTO.builder()
                .id(servicePackage.getId())
                .packageName(servicePackage.getPackageName())
                .price(servicePackage.getPrice())
                .type(servicePackage.getType())
                .isActive(servicePackage.getIsActive())
                .createdAt(servicePackage.getCreatedAt())
                .updatedAt(servicePackage.getUpdatedAt())
                .createdBy(servicePackage.getCreatedBy())
                .updatedBy(servicePackage.getUpdatedBy())
                .description(servicePackage.getDescription())
                .durationInDays(servicePackage.getDurationInDays())
                .numberOfSessions(servicePackage.getNumberOfSessions())
                .build();
    }
}
