package com.se100.GymAndPTManagement.domain.responseDTO;

import java.time.LocalDate;

import com.se100.GymAndPTManagement.util.enums.GenderEnum;
import com.se100.GymAndPTManagement.util.enums.UserStatusEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 02:44:02
 * Purpose: Response DTO for user information
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResUserDTO {

    private Long id;
    private String fullname;
    private String email;
    private String phoneNumber;
    private String avatarUrl;
    private LocalDate dob;
    private GenderEnum gender;
    private UserStatusEnum status;
}
