/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Response DTO for WorkoutImage
 */

package com.se100.GymAndPTManagement.domain.responseDTO;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ResWorkoutImageDTO {
    
    private Long id;
    
    @JsonProperty("workout_id")
    private Long workoutId;
    
    @JsonProperty("image_url")
    private String imageUrl;
    
    @JsonProperty("image_path")
    private String imagePath;
    
    private String description;
    
    @JsonProperty("display_order")
    private Integer displayOrder;
    
    private String status;
    
    @JsonProperty("created_at")
    private LocalDateTime createdAt;
    
    @JsonProperty("updated_at")
    private LocalDateTime updatedAt;
    
    @JsonProperty("created_by")
    private String createdBy;
    
    @JsonProperty("updated_by")
    private String updatedBy;
}






