/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: Food service implementation with business logic
 */

package com.se100.GymAndPTManagement.service.impl;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqFoodDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResFoodDTO;
import com.se100.GymAndPTManagement.domain.table.Food;
import com.se100.GymAndPTManagement.repository.FoodRepository;
import com.se100.GymAndPTManagement.service.FoodService;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@AllArgsConstructor
public class FoodServiceImpl implements FoodService {
    
    private final FoodRepository foodRepository;
    
    @Override
    public ResFoodDTO createFood(ReqFoodDTO reqFoodDTO) {
        // Kiểm tra tên thực phẩm có tồn tại không
        if (foodRepository.existsByName(reqFoodDTO.getName())) {
            throw new IdInvalidException("Thực phẩm có tên '" + reqFoodDTO.getName() + "' đã tồn tại");
        }
        
        Food food = Food.builder()
                .name(reqFoodDTO.getName())
                .type(reqFoodDTO.getType())
                .calories(reqFoodDTO.getCalories())
                .protein(reqFoodDTO.getProtein())
                .fat(reqFoodDTO.getFat())
                .carbohydrate(reqFoodDTO.getCarbohydrate())
                .foodPhoto(reqFoodDTO.getFoodPhoto())
                .notes(reqFoodDTO.getNotes())
                .status("ACTIVE")
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
        
        Food savedFood = foodRepository.save(food);
        return convertToDTO(savedFood);
    }
    
    @Override
    public ResFoodDTO updateFood(Long id, ReqFoodDTO reqFoodDTO) {
        Food food = foodRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Thực phẩm với ID " + id + " không tồn tại"));
        
        // Kiểm tra tên mới có trùng không (ngoại trừ chính nó)
        if (!food.getName().equals(reqFoodDTO.getName()) && 
            foodRepository.existsByName(reqFoodDTO.getName())) {
            throw new IdInvalidException("Thực phẩm có tên '" + reqFoodDTO.getName() + "' đã tồn tại");
        }
        
        food.setName(reqFoodDTO.getName());
        food.setType(reqFoodDTO.getType());
        food.setCalories(reqFoodDTO.getCalories());
        food.setProtein(reqFoodDTO.getProtein());
        food.setFat(reqFoodDTO.getFat());
        food.setCarbohydrate(reqFoodDTO.getCarbohydrate());
        food.setFoodPhoto(reqFoodDTO.getFoodPhoto());
        food.setNotes(reqFoodDTO.getNotes());
        food.setUpdatedAt(LocalDateTime.now());
        
        Food updatedFood = foodRepository.save(food);
        return convertToDTO(updatedFood);
    }
    
    @Override
    public ResFoodDTO getFoodById(Long id) {
        Food food = foodRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Thực phẩm với ID " + id + " không tồn tại"));
        return convertToDTO(food);
    }
    
    @Override
    public Page<ResFoodDTO> getAllFoods(Pageable pageable) {
        Page<Food> foods = foodRepository.findAll(pageable);
        List<ResFoodDTO> dtos = foods.stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
        return new PageImpl<>(dtos, pageable, foods.getTotalElements());
    }
    
    @Override
    public List<ResFoodDTO> getFoodsByStatus(String status) {
        return foodRepository.findByStatus(status).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public void deleteFood(Long id) {
        if (!foodRepository.existsById(id)) {
            throw new IdInvalidException("Thực phẩm với ID " + id + " không tồn tại");
        }
        foodRepository.deleteById(id);
    }
    
    @Override
    public ResFoodDTO getFoodByName(String name) {
        Food food = foodRepository.findByName(name)
                .orElseThrow(() -> new IdInvalidException("Thực phẩm có tên '" + name + "' không tồn tại"));
        return convertToDTO(food);
    }
    
    @Override
    public List<ResFoodDTO> getFoodsByCaloriesBetween(Float minCalories, Float maxCalories) {
        return foodRepository.findByCaloriesBetween(minCalories, maxCalories).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResFoodDTO> getTopProteinFoods(int limit) {
        return foodRepository.findTopByProtein(limit).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    // Helper method
    private ResFoodDTO convertToDTO(Food food) {
        return ResFoodDTO.builder()
                .id(food.getId())
                .name(food.getName())
                .type(food.getType())
                .calories(food.getCalories())
                .protein(food.getProtein())
                .fat(food.getFat())
                .carbohydrate(food.getCarbohydrate())
                .foodPhoto(food.getFoodPhoto())
                .notes(food.getNotes())
                .status(food.getStatus())
                .createdAt(food.getCreatedAt())
                .updatedAt(food.getUpdatedAt())
                .createdBy(food.getCreatedBy())
                .updatedBy(food.getUpdatedBy())
                .build();
    }
}






