/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutDevice service implementation for inventory management
 */

package com.se100.GymAndPTManagement.service.impl;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDeviceDTO;
import com.se100.GymAndPTManagement.domain.table.WorkoutDevice;
import com.se100.GymAndPTManagement.repository.WorkoutDeviceRepository;
import com.se100.GymAndPTManagement.service.WorkoutDeviceService;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@AllArgsConstructor
public class WorkoutDeviceServiceImpl implements WorkoutDeviceService {
    
    private final WorkoutDeviceRepository workoutDeviceRepository;
    
    @Override
    public ResWorkoutDeviceDTO createWorkoutDevice(ReqWorkoutDeviceDTO reqWorkoutDeviceDTO) {
        if (workoutDeviceRepository.findByName(reqWorkoutDeviceDTO.getName()).isPresent()) {
            throw new IdInvalidException("Thiết bị có tên '" + reqWorkoutDeviceDTO.getName() + "' đã tồn tại");
        }
        
        WorkoutDevice workoutDevice = WorkoutDevice.builder()
                .name(reqWorkoutDeviceDTO.getName())
                .description(reqWorkoutDeviceDTO.getDescription())
                .equipmentType(reqWorkoutDeviceDTO.getEquipmentType())
                .equipmentPhoto(reqWorkoutDeviceDTO.getEquipmentPhoto())
                .quantity(reqWorkoutDeviceDTO.getQuantity() != null ? reqWorkoutDeviceDTO.getQuantity() : 1)
                .purchasePrice(reqWorkoutDeviceDTO.getPurchasePrice())
                .purchaseDate(reqWorkoutDeviceDTO.getPurchaseDate())
                .lastMaintenanceDate(reqWorkoutDeviceDTO.getLastMaintenanceDate())
                .nextMaintenanceDate(reqWorkoutDeviceDTO.getNextMaintenanceDate())
                .status("IN_STOCK")
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
        
        WorkoutDevice savedDevice = workoutDeviceRepository.save(workoutDevice);
        return convertToDTO(savedDevice);
    }
    
    @Override
    public ResWorkoutDeviceDTO updateWorkoutDevice(Long id, ReqWorkoutDeviceDTO reqWorkoutDeviceDTO) {
        WorkoutDevice workoutDevice = workoutDeviceRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Thiết bị với ID " + id + " không tồn tại"));
        
        workoutDevice.setName(reqWorkoutDeviceDTO.getName());
        workoutDevice.setDescription(reqWorkoutDeviceDTO.getDescription());
        workoutDevice.setEquipmentType(reqWorkoutDeviceDTO.getEquipmentType());
        workoutDevice.setEquipmentPhoto(reqWorkoutDeviceDTO.getEquipmentPhoto());
        workoutDevice.setQuantity(reqWorkoutDeviceDTO.getQuantity());
        workoutDevice.setPurchasePrice(reqWorkoutDeviceDTO.getPurchasePrice());
        workoutDevice.setPurchaseDate(reqWorkoutDeviceDTO.getPurchaseDate());
        workoutDevice.setLastMaintenanceDate(reqWorkoutDeviceDTO.getLastMaintenanceDate());
        workoutDevice.setNextMaintenanceDate(reqWorkoutDeviceDTO.getNextMaintenanceDate());
        workoutDevice.setUpdatedAt(LocalDateTime.now());
        
        WorkoutDevice updatedDevice = workoutDeviceRepository.save(workoutDevice);
        return convertToDTO(updatedDevice);
    }
    
    @Override
    public ResWorkoutDeviceDTO getWorkoutDeviceById(Long id) {
        WorkoutDevice workoutDevice = workoutDeviceRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Thiết bị với ID " + id + " không tồn tại"));
        return convertToDTO(workoutDevice);
    }
    
    @Override
    public Page<ResWorkoutDeviceDTO> getAllWorkoutDevices(Pageable pageable) {
        Page<WorkoutDevice> devices = workoutDeviceRepository.findAll(pageable);
        List<ResWorkoutDeviceDTO> dtos = devices.stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
        return new PageImpl<>(dtos, pageable, devices.getTotalElements());
    }
    
    @Override
    public ResWorkoutDeviceDTO getWorkoutDeviceByName(String name) {
        WorkoutDevice workoutDevice = workoutDeviceRepository.findByName(name)
                .orElseThrow(() -> new IdInvalidException("Thiết bị có tên '" + name + "' không tồn tại"));
        return convertToDTO(workoutDevice);
    }
    
    @Override
    public List<ResWorkoutDeviceDTO> getWorkoutDevicesByType(String equipmentType) {
        return workoutDeviceRepository.findByEquipmentType(equipmentType).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutDeviceDTO> getWorkoutDevicesByStatus(String status) {
        return workoutDeviceRepository.findByStatus(status).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutDeviceDTO> searchWorkoutDevices(String name) {
        return workoutDeviceRepository.findByNameContainingIgnoreCase(name).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public Long getDeviceCountByStatus(String status) {
        return switch(status.toUpperCase()) {
            case "IN_STOCK" -> workoutDeviceRepository.countAvailableDevices();
            case "IN_USE" -> workoutDeviceRepository.countInUseDevices();
            case "MAINTENANCE" -> workoutDeviceRepository.countMaintenanceDevices();
            default -> workoutDeviceRepository.countTotalDevices();
        };
    }
    
    @Override
    public void deleteWorkoutDevice(Long id) {
        if (!workoutDeviceRepository.existsById(id)) {
            throw new IdInvalidException("Thiết bị với ID " + id + " không tồn tại");
        }
        workoutDeviceRepository.deleteById(id);
    }
    
    private ResWorkoutDeviceDTO convertToDTO(WorkoutDevice workoutDevice) {
        return ResWorkoutDeviceDTO.builder()
                .id(workoutDevice.getId())
                .name(workoutDevice.getName())
                .description(workoutDevice.getDescription())
                .equipmentType(workoutDevice.getEquipmentType())
                .equipmentPhoto(workoutDevice.getEquipmentPhoto())
                .quantity(workoutDevice.getQuantity())
                .purchasePrice(workoutDevice.getPurchasePrice())
                .purchaseDate(workoutDevice.getPurchaseDate())
                .lastMaintenanceDate(workoutDevice.getLastMaintenanceDate())
                .nextMaintenanceDate(workoutDevice.getNextMaintenanceDate())
                .status(workoutDevice.getStatus())
                .createdAt(workoutDevice.getCreatedAt())
                .updatedAt(workoutDevice.getUpdatedAt())
                .createdBy(workoutDevice.getCreatedBy())
                .updatedBy(workoutDevice.getUpdatedBy())
                .build();
    }
}






