/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutImage service implementation for image management
 */

package com.se100.GymAndPTManagement.service.impl;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutImageDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutImageDTO;
import com.se100.GymAndPTManagement.domain.table.WorkoutImage;
import com.se100.GymAndPTManagement.repository.WorkoutImageRepository;
import com.se100.GymAndPTManagement.service.WorkoutImageService;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@AllArgsConstructor
public class WorkoutImageServiceImpl implements WorkoutImageService {
    
    private final WorkoutImageRepository workoutImageRepository;
    
    @Override
    public ResWorkoutImageDTO addWorkoutImage(ReqWorkoutImageDTO reqWorkoutImageDTO) {
        WorkoutImage workoutImage = WorkoutImage.builder()
                .workoutId(reqWorkoutImageDTO.getWorkoutId())
                .imageUrl(reqWorkoutImageDTO.getImageUrl())
                .imagePath(reqWorkoutImageDTO.getImagePath())
                .description(reqWorkoutImageDTO.getDescription())
                .displayOrder(reqWorkoutImageDTO.getDisplayOrder() != null ? reqWorkoutImageDTO.getDisplayOrder() : 1)
                .status("ACTIVE")
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
        
        WorkoutImage savedImage = workoutImageRepository.save(workoutImage);
        return convertToDTO(savedImage);
    }
    
    @Override
    public ResWorkoutImageDTO updateWorkoutImage(Long id, ReqWorkoutImageDTO reqWorkoutImageDTO) {
        WorkoutImage workoutImage = workoutImageRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Hình ảnh với ID " + id + " không tồn tại"));
        
        workoutImage.setImageUrl(reqWorkoutImageDTO.getImageUrl());
        workoutImage.setImagePath(reqWorkoutImageDTO.getImagePath());
        workoutImage.setDescription(reqWorkoutImageDTO.getDescription());
        workoutImage.setDisplayOrder(reqWorkoutImageDTO.getDisplayOrder());
        workoutImage.setUpdatedAt(LocalDateTime.now());
        
        WorkoutImage updatedImage = workoutImageRepository.save(workoutImage);
        return convertToDTO(updatedImage);
    }
    
    @Override
    public ResWorkoutImageDTO getWorkoutImageById(Long id) {
        WorkoutImage workoutImage = workoutImageRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Hình ảnh với ID " + id + " không tồn tại"));
        return convertToDTO(workoutImage);
    }
    
    @Override
    public List<ResWorkoutImageDTO> getImagesByWorkoutId(Long workoutId) {
        return workoutImageRepository.findByWorkoutId(workoutId).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutImageDTO> getImagesByWorkoutIdOrdered(Long workoutId) {
        return workoutImageRepository.findByWorkoutIdOrderByDisplayOrder(workoutId).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutImageDTO> getImagesByStatus(String status) {
        return workoutImageRepository.findByStatus(status).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public void deleteWorkoutImage(Long id) {
        if (!workoutImageRepository.existsById(id)) {
            throw new IdInvalidException("Hình ảnh với ID " + id + " không tồn tại");
        }
        workoutImageRepository.deleteById(id);
    }
    
    private ResWorkoutImageDTO convertToDTO(WorkoutImage workoutImage) {
        return ResWorkoutImageDTO.builder()
                .id(workoutImage.getId())
                .workoutId(workoutImage.getWorkoutId())
                .imageUrl(workoutImage.getImageUrl())
                .imagePath(workoutImage.getImagePath())
                .description(workoutImage.getDescription())
                .displayOrder(workoutImage.getDisplayOrder())
                .status(workoutImage.getStatus())
                .createdAt(workoutImage.getCreatedAt())
                .updatedAt(workoutImage.getUpdatedAt())
                .createdBy(workoutImage.getCreatedBy())
                .updatedBy(workoutImage.getUpdatedBy())
                .build();
    }
}






