/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Workout service implementation for exercise library
 */

package com.se100.GymAndPTManagement.service.impl;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutDTO;
import com.se100.GymAndPTManagement.domain.table.Workout;
import com.se100.GymAndPTManagement.repository.WorkoutRepository;
import com.se100.GymAndPTManagement.service.WorkoutService;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@AllArgsConstructor
public class WorkoutServiceImpl implements WorkoutService {
    
    private final WorkoutRepository workoutRepository;
    
    @Override
    public ResWorkoutDTO createWorkout(ReqWorkoutDTO reqWorkoutDTO) {
        Workout workout = Workout.builder()
                .name(reqWorkoutDTO.getName())
                .description(reqWorkoutDTO.getDescription())
                .durationMinutes(reqWorkoutDTO.getDurationMinutes())
                .difficultyLevel(reqWorkoutDTO.getDifficultyLevel())
                .caloriesBurnt(reqWorkoutDTO.getCaloriesBurnt())
                .deviceId(reqWorkoutDTO.getDeviceId())
                .status("ACTIVE")
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
        
        Workout savedWorkout = workoutRepository.save(workout);
        return convertToDTO(savedWorkout);
    }
    
    @Override
    public ResWorkoutDTO updateWorkout(Long id, ReqWorkoutDTO reqWorkoutDTO) {
        Workout workout = workoutRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Bài tập với ID " + id + " không tồn tại"));
        
        workout.setName(reqWorkoutDTO.getName());
        workout.setDescription(reqWorkoutDTO.getDescription());
        workout.setDurationMinutes(reqWorkoutDTO.getDurationMinutes());
        workout.setDifficultyLevel(reqWorkoutDTO.getDifficultyLevel());
        workout.setCaloriesBurnt(reqWorkoutDTO.getCaloriesBurnt());
        workout.setDeviceId(reqWorkoutDTO.getDeviceId());
        workout.setUpdatedAt(LocalDateTime.now());
        
        Workout updatedWorkout = workoutRepository.save(workout);
        return convertToDTO(updatedWorkout);
    }
    
    @Override
    public ResWorkoutDTO getWorkoutById(Long id) {
        Workout workout = workoutRepository.findById(id)
                .orElseThrow(() -> new IdInvalidException("Bài tập với ID " + id + " không tồn tại"));
        return convertToDTO(workout);
    }
    
    @Override
    public Page<ResWorkoutDTO> getAllWorkouts(Pageable pageable) {
        Page<Workout> workouts = workoutRepository.findAll(pageable);
        List<ResWorkoutDTO> dtos = workouts.stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
        return new PageImpl<>(dtos, pageable, workouts.getTotalElements());
    }
    
    @Override
    public ResWorkoutDTO getWorkoutByName(String name) {
        Workout workout = workoutRepository.findByName(name)
                .orElseThrow(() -> new IdInvalidException("Bài tập có tên '" + name + "' không tồn tại"));
        return convertToDTO(workout);
    }
    
    @Override
    public List<ResWorkoutDTO> getWorkoutsByDifficulty(String difficulty) {
        return workoutRepository.findByDifficultyLevel(difficulty).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutDTO> getWorkoutsByDevice(Long deviceId) {
        return workoutRepository.findByDeviceId(deviceId).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public List<ResWorkoutDTO> searchWorkouts(String name) {
        return workoutRepository.findByNameContainingIgnoreCase(name).stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    @Override
    public void deleteWorkout(Long id) {
        if (!workoutRepository.existsById(id)) {
            throw new IdInvalidException("Bài tập với ID " + id + " không tồn tại");
        }
        workoutRepository.deleteById(id);
    }
    
    private ResWorkoutDTO convertToDTO(Workout workout) {
        return ResWorkoutDTO.builder()
                .id(workout.getId())
                .name(workout.getName())
                .description(workout.getDescription())
                .durationMinutes(workout.getDurationMinutes())
                .difficultyLevel(workout.getDifficultyLevel())
                .caloriesBurnt(workout.getCaloriesBurnt())
                .deviceId(workout.getDeviceId())
                .status(workout.getStatus())
                .createdAt(workout.getCreatedAt())
                .updatedAt(workout.getUpdatedAt())
                .createdBy(workout.getCreatedBy())
                .updatedBy(workout.getUpdatedBy())
                .build();
    }
}






