/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-09 15:10:00
 * Purpose: Enum for Contract status values
 */
package com.se100.GymAndPTManagement.util.enums;

public enum ContractStatusEnum {
    ACTIVE("Đang hoạt động"),
    EXPIRED("Hết hạn"),
    CANCELLED("Đã hủy");
    
    private final String displayName;
    
    ContractStatusEnum(String displayName) {
        this.displayName = displayName;
    }
    
    public String getDisplayName() {
        return displayName;
    }
}
