/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-15 14:50:00
 * Purpose: Enum for Invoice payment status values
 */
package com.se100.GymAndPTManagement.util.enums;

public enum PaymentStatusEnum {
    UNPAID("Chưa thanh toán"),
    PAID("Đã thanh toán");
    
    private final String displayName;
    
    PaymentStatusEnum(String displayName) {
        this.displayName = displayName;
    }
    
    public String getDisplayName() {
        return displayName;
    }
}
