package com.se100.GymAndPTManagement.util.enums;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 04:00:20
 * Purpose: Enum for Personal Trainer status
 */
public enum PTStatusEnum {
    AVAILABLE,
    BUSY,
    INACTIVE
}
