package com.se100.GymAndPTManagement.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.AdditionalService;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 19:48:37
 * Purpose: Repository for AdditionalService entity
 */
@Repository
public interface AdditionalServiceRepository extends JpaRepository<AdditionalService, Long> {

    /**
     * Find all active additional services
     * 
     * @param isActive Active status
     * @return List of active additional services
     */
    List<AdditionalService> findByIsActive(Boolean isActive);

    /**
     * Find additional services by name containing keyword (case-insensitive)
     * 
     * @param name Keyword to search in service name
     * @return List of additional services matching the keyword
     */
    List<AdditionalService> findByNameContainingIgnoreCase(String name);
}
