package com.se100.GymAndPTManagement.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.AvailableSlot;
import com.se100.GymAndPTManagement.util.enums.DayOfWeekEnum;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-14 10:19:59
 * Purpose: Repository for AvailableSlot entity
 */
@Repository
public interface AvailableSlotRepository
        extends JpaRepository<AvailableSlot, Long>, JpaSpecificationExecutor<AvailableSlot> {
    List<AvailableSlot> findByIsAvailable(Boolean isAvailable);

    List<AvailableSlot> findByPersonalTrainerId(Long ptId);

    List<AvailableSlot> findByPersonalTrainerIdAndIsAvailable(Long ptId, Boolean isAvailable);

    Optional<AvailableSlot> findBySlotIdAndPersonalTrainerIdAndDayOfWeek(Long slotId, Long ptId,
            DayOfWeekEnum dayOfWeek);

    List<AvailableSlot> findBySlotIdAndDayOfWeekAndIsAvailable(Long slotId, DayOfWeekEnum dayOfWeek,
            Boolean isAvailable);
}
