/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 11:00:00
 * Purpose: Repository for CheckinLog entity with custom queries
 */
package com.se100.GymAndPTManagement.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.CheckinLog;

import java.util.List;
import java.util.Optional;

@Repository
public interface CheckinLogRepository extends JpaRepository<CheckinLog, Long> {

    /**
     * Find all checkin logs by member ID
     */
    List<CheckinLog> findByMemberId(Long memberId);

    /**
     * Find all checkin logs by booking ID
     */
    List<CheckinLog> findByBookingId(Long bookingId);

    /**
     * Find active checkin log (CHECKED_IN status) by booking ID
     */
    @Query("""
        SELECT cl FROM CheckinLog cl
        WHERE cl.booking.id = :bookingId
        AND cl.status = 'CHECKED_IN'
        ORDER BY cl.createdAt DESC
        LIMIT 1
    """)
    Optional<CheckinLog> findActiveCheckInByBookingId(@Param("bookingId") Long bookingId);

    /**
     * Find latest checkin log by booking ID (regardless of status)
     */
    @Query("""
        SELECT cl FROM CheckinLog cl
        WHERE cl.booking.id = :bookingId
        ORDER BY cl.createdAt DESC
        LIMIT 1
    """)
    Optional<CheckinLog> findLatestByBookingId(@Param("bookingId") Long bookingId);

    /**
     * Check if booking already has active checkin (not cancelled)
     */
    @Query("""
        SELECT COUNT(cl) > 0 FROM CheckinLog cl
        WHERE cl.booking.id = :bookingId
        AND cl.status != 'CANCELLED'
    """)
    boolean hasActiveCheckin(@Param("bookingId") Long bookingId);

    /**
     * Find checkin logs by booking ID and status
     */
    List<CheckinLog> findByBookingIdAndStatus(Long bookingId, String status);
}
