/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 11:00:00
 * Purpose: Repository for CheckinLog entity with custom queries
 */
package com.se100.GymAndPTManagement.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.CheckinLog;

import java.util.List;
import java.util.Optional;

@Repository
public interface CheckinLogRepository extends JpaRepository<CheckinLog, Long> {

    /**
     * Find all checkin logs by member ID
     * Used in CheckinLogService.getCheckinsByMember() and controller
     */
    List<CheckinLog> findByMemberId(Long memberId);

    /**
     * Find all checkin logs by booking ID
     * Used in CheckinLogService.getCheckinsByBooking() and controller
     */
    List<CheckinLog> findByBookingId(Long bookingId);

    /**
     * Find active checkin log (CHECKED_IN status) by booking ID
     * Used for checkout validation - checks if booking has active checkin
     * Note: Using fetchFirst() in query instead of LIMIT for JPQL compatibility
     */
    @Query("""
        SELECT cl FROM CheckinLog cl
        WHERE cl.booking.id = :bookingId
        AND cl.status = 'CHECKED_IN'
        ORDER BY cl.createdAt DESC
    """)
    Optional<CheckinLog> findActiveCheckInByBookingId(@Param("bookingId") Long bookingId);

    /**
     * Find latest checkin log by booking ID (regardless of status)
     * Used for cancel checkin operation
     * Note: Using ORDER BY DESC instead of LIMIT for JPQL compatibility
     */
    @Query("""
        SELECT cl FROM CheckinLog cl
        WHERE cl.booking.id = :bookingId
        ORDER BY cl.createdAt DESC
    """)
    Optional<CheckinLog> findLatestByBookingId(@Param("bookingId") Long bookingId);

    /**
     * Count attended sessions (CHECKED_OUT status) for a member
     * Used in CheckinLogService.getAttendanceTracking() for attendance statistics
     */
    @Query("""
        SELECT COUNT(cl) FROM CheckinLog cl
        WHERE cl.member.id = :memberId
        AND cl.status = 'CHECKED_OUT'
    """)
    Long countAttendedSessionsByMemberId(@Param("memberId") Long memberId);
}
