/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 14:05:17
 * Purpose: DailyDiet repository for data access layer
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.DailyDiet;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
public interface DailyDietRepository extends JpaRepository<DailyDiet, Long> {
    
    /**
     * Tìm tất cả diet của hội viên
     */
    List<DailyDiet> findByMemberId(Long memberId);
    
    /**
     * Tìm diet của hội viên vào ngày cụ thể
     */
    Optional<DailyDiet> findByMemberIdAndDietDate(Long memberId, LocalDate dietDate);
    
    /**
     * Tìm diet theo khoảng ngày
     */
    List<DailyDiet> findByDietDateBetween(LocalDate startDate, LocalDate endDate);
    
    /**
     * Tìm diet của hội viên trong khoảng ngày
     */
    List<DailyDiet> findByMemberIdAndDietDateBetween(Long memberId, LocalDate startDate, LocalDate endDate);
    
    /**
     * Tìm diet mới nhất của hội viên
     */
    @Query("SELECT d FROM DailyDiet d WHERE d.memberId = :memberId AND d.status = 'ACTIVE' ORDER BY d.dietDate DESC LIMIT 1")
    Optional<DailyDiet> findLatestByMemberId(@Param("memberId") Long memberId);
    
    /**
     * Tìm diet theo tên kế hoạch
     */
    List<DailyDiet> findByPlanNameContainingIgnoreCase(String planName);
    
    /**
     * Tìm diet theo trạng thái
     */
    List<DailyDiet> findByStatus(String status);
    
    /**
     * Kiểm tra diet có tồn tại không
     */
    boolean existsByMemberIdAndDietDate(Long memberId, LocalDate dietDate);
}






