/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: DietDetail repository for data access
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.DietDetail;
import com.se100.GymAndPTManagement.domain.table.DietDetailId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DietDetailRepository extends JpaRepository<DietDetail, DietDetailId> {
    
    List<DietDetail> findByDailyDietId(Long dailyDietId);
    
    List<DietDetail> findByMealType(String mealType);
    
    List<DietDetail> findByDailyDietIdAndMealType(Long dailyDietId, String mealType);
}






