package com.se100.GymAndPTManagement.repository;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.DietDetail;
import com.se100.GymAndPTManagement.domain.table.DietDetailId;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 16:00:00
 * Purpose: Repository for DietDetail entity with composite key support
 */
@Repository
public interface DietDetailRepository
        extends JpaRepository<DietDetail, DietDetailId>, JpaSpecificationExecutor<DietDetail> {

    // Find all diet details for a specific daily diet
    List<DietDetail> findByDietId(Long dietId);

    Page<DietDetail> findByDietId(Long dietId, Pageable pageable);

    // Find all diet details containing a specific food
    List<DietDetail> findByFoodId(Long foodId);

    Page<DietDetail> findByFoodId(Long foodId, Pageable pageable);

    // Delete all diet details for a specific daily diet
    void deleteByDietId(Long dietId);

    // Delete specific food from a daily diet
    void deleteByDietIdAndFoodId(Long dietId, Long foodId);

    // Check if food exists in a specific diet
    boolean existsByDietIdAndFoodId(Long dietId, Long foodId);

    // Count total foods in a diet
    long countByDietId(Long dietId);
}
