package com.se100.GymAndPTManagement.repository;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.Food;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 14:30:00
 * Purpose: Food repository for database operations
 */
@Repository
public interface FoodRepository extends JpaRepository<Food, Long>, JpaSpecificationExecutor<Food> {

    boolean existsByName(String name);

    Optional<Food> findByName(String name);

    // JPA supports BETWEEN automatically
    Page<Food> findByCaloriesBetween(BigDecimal minCalories, BigDecimal maxCalories, Pageable pageable);

    // Search by name or note
    Page<Food> findByNameContainingIgnoreCase(String nameKeyword, Pageable pageable);

    List<Food> findByStatus(String status);

    List<Food> findByType(String type);

    Page<Food> findByType(String type, Pageable pageable);
}
