/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: Food repository for data access layer
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.Food;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface FoodRepository extends JpaRepository<Food, Long> {
    
    /**
     * Tìm thực phẩm theo tên
     */
    Optional<Food> findByName(String name);
    
    /**
     * Tìm tất cả thực phẩm theo trạng thái
     */
    List<Food> findByStatus(String status);
    
    /**
     * Tìm thực phẩm theo khoảng calo
     */
    @Query("SELECT f FROM Food f WHERE f.calories BETWEEN :minCalories AND :maxCalories AND f.status = 'ACTIVE'")
    List<Food> findByCaloriesBetween(@Param("minCalories") Float minCalories, @Param("maxCalories") Float maxCalories);
    
    /**
     * Kiểm tra thực phẩm có tồn tại theo tên
     */
    boolean existsByName(String name);
    
    /**
     * Tìm thực phẩm theo protein cao nhất
     */
    @Query(value = "SELECT * FROM food WHERE status = 'ACTIVE' ORDER BY protein DESC LIMIT :limit", nativeQuery = true)
    List<Food> findTopByProtein(@Param("limit") int limit);
}






