package com.se100.GymAndPTManagement.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.Member;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-07 20:03:11
 * Purpose: Member repository for database operations
 */
@Repository
public interface MemberRepository extends JpaRepository<Member, Long> {
    boolean existsByCccd(String cccd);

    Optional<Member> findByCccd(String cccd);

    Optional<Member> findByUserId(Long userId);
}
