package com.se100.GymAndPTManagement.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.ServicePackage;
import com.se100.GymAndPTManagement.util.enums.PackageTypeEnum;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 09:30:43
 * Purpose: ServicePackage repository for database operations
 */
@Repository
public interface ServicePackageRepository extends JpaRepository<ServicePackage, Long> {
    Optional<ServicePackage> findByPackageName(String packageName);

    List<ServicePackage> findByIsActive(Boolean isActive);

    List<ServicePackage> findByType(PackageTypeEnum type);

    List<ServicePackage> findByTypeAndIsActive(PackageTypeEnum type, Boolean isActive);

    boolean existsByPackageName(String packageName);
}
