/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 10:20:00
 * Purpose: Repository for Slot entity
 */
package com.se100.GymAndPTManagement.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.se100.GymAndPTManagement.domain.table.Slot;

@Repository
public interface SlotRepository extends JpaRepository<Slot, Long> {
}
