/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: WorkoutImage repository for data access
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.WorkoutImage;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface WorkoutImageRepository extends JpaRepository<WorkoutImage, Long> {
    
    List<WorkoutImage> findByWorkoutId(Long workoutId);
    
    List<WorkoutImage> findByWorkoutIdOrderByDisplayOrder(Long workoutId);
    
    List<WorkoutImage> findByStatus(String status);
}






