/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: WorkoutDevice repository for inventory management
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.WorkoutDevice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface WorkoutDeviceRepository extends JpaRepository<WorkoutDevice, Long> {
    
    /**
     * Tìm thiết bị theo tên
     */
    Optional<WorkoutDevice> findByName(String name);
    
    /**
     * Tìm thiết bị theo loại
     */
    List<WorkoutDevice> findByEquipmentType(String equipmentType);
    
    /**
     * Tìm thiết bị theo trạng thái
     */
    List<WorkoutDevice> findByStatus(String status);
    
    /**
     * Tìm thiết bị theo tên (chứa)
     */
    List<WorkoutDevice> findByNameContainingIgnoreCase(String name);
    
    /**
     * Đếm tổng số thiết bị
     */
    @Query("SELECT COUNT(d) FROM WorkoutDevice d")
    Long countTotalDevices();
    
    /**
     * Đếm thiết bị có sẵn
     */
    @Query("SELECT COUNT(d) FROM WorkoutDevice d WHERE d.status = 'IN_STOCK'")
    Long countAvailableDevices();
    
    /**
     * Đếm thiết bị đang sử dụng
     */
    @Query("SELECT COUNT(d) FROM WorkoutDevice d WHERE d.status = 'IN_USE'")
    Long countInUseDevices();
    
    /**
     * Đếm thiết bị cần bảo trì
     */
    @Query("SELECT COUNT(d) FROM WorkoutDevice d WHERE d.status = 'MAINTENANCE'")
    Long countMaintenanceDevices();
}






