/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Workout repository for exercise library
 */

package com.se100.GymAndPTManagement.repository;

import com.se100.GymAndPTManagement.domain.table.Workout;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface WorkoutRepository extends JpaRepository<Workout, Long> {
    
    /**
     * Tìm bài tập theo tên
     */
    Optional<Workout> findByName(String name);
    
    /**
     * Tìm bài tập theo trạng thái
     */
    List<Workout> findByStatus(String status);
    
    /**
     * Tìm bài tập theo độ khó
     */
    List<Workout> findByDifficultyLevel(String difficultyLevel);
    
    /**
     * Tìm bài tập theo thiết bị
     */
    List<Workout> findByDeviceId(Long deviceId);
    
    /**
     * Tìm bài tập theo tên (chứa)
     */
    List<Workout> findByNameContainingIgnoreCase(String name);
}






