/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-09 14:50:00
 * Purpose: DTO for creating new contract with automatic invoice generation
 */
package com.se100.GymAndPTManagement.domain.requestDTO;

import jakarta.validation.constraints.*;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqCreateContractDTO {
    
    @NotNull(message = "Member ID cannot be null")
    private Long memberId;
    
    @NotNull(message = "Package ID cannot be null")
    private Long packageId;
    
    private Long ptId; // Optional
    
    @NotNull(message = "Start date cannot be null")
    @FutureOrPresent(message = "Start date must be present or future")
    private LocalDate startDate;
    
    /**
     * End date is OPTIONAL - will be automatically calculated as:
     * endDate = startDate + duration_in_days (from service package)
     * 
     * If provided by client, must match the calculated value exactly.
     * Otherwise, service will throw IllegalArgumentException.
     */
    private LocalDate endDate; // Optional - auto-calculated from duration_in_days
    
    @NotBlank(message = "Payment method cannot be blank")
    private String paymentMethod;
    
    private BigDecimal discountAmount; // Discount amount, default 0 if null
    
    private String notes;
}
