package com.se100.GymAndPTManagement.domain.requestDTO;

import com.se100.GymAndPTManagement.util.enums.DayOfWeekEnum;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-19
 * Purpose: Request DTO for creating available slot for current logged-in user
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqCreateAvailableSlotForCurrentUserDTO {

    @NotNull(message = "Slot ID is required")
    private Long slotId;

    @NotNull(message = "Day of week is required")
    private DayOfWeekEnum dayOfWeek;
}
