package com.se100.GymAndPTManagement.domain.requestDTO;

import java.time.LocalDate;

import com.se100.GymAndPTManagement.util.enums.GenderEnum;
import com.se100.GymAndPTManagement.util.enums.UserStatusEnum;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 11:20:37
 * Purpose: Request DTO for creating Personal Trainer
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReqCreatePTDTO {

    // User information
    @NotBlank(message = "Họ tên không được để trống")
    @Size(max = 150, message = "Họ tên không được vượt quá 150 ký tự")
    private String fullname;

    @NotBlank(message = "Email không được để trống")
    @Email(message = "Email không hợp lệ")
    @Size(max = 150, message = "Email không được vượt quá 150 ký tự")
    private String email;

    @Size(min = 8, message = "Password phải có ít nhất 8 ký tự")
    private String password;

    @Pattern(regexp = "^[0-9]{10,11}$", message = "Số điện thoại phải có 10-11 chữ số")
    private String phoneNumber;

    private String avatarUrl;

    @NotNull(message = "Ngày sinh không được để trống")
    private LocalDate dob;

    private GenderEnum gender;

    private UserStatusEnum status;

    // PT specific information
    private String about;

    private String specialization;

    private String certifications;

    @Min(value = 0, message = "Số năm kinh nghiệm không được âm")
    private Integer experienceYears;

    private String note;
}
