package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;

import com.se100.GymAndPTManagement.util.enums.PackageTypeEnum;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 09:30:43
 * Purpose: Request DTO for creating service package
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqCreateServicePackageDTO {

    @NotBlank(message = "Package name is required")
    private String packageName;

    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.0", inclusive = true, message = "Price must be greater than or equal to 0")
    private BigDecimal price;

    @NotNull(message = "Package type is required")
    private PackageTypeEnum type;

    private Boolean isActive; // Optional, defaults to true if not provided

    private String description;

    @Min(value = 1, message = "Duration in days must be at least 1")
    private Integer durationInDays;

    @Min(value = 0, message = "Number of sessions must be non-negative")
    private Integer numberOfSessions;
}
