package com.se100.GymAndPTManagement.domain.requestDTO;

import java.time.LocalDate;

import com.se100.GymAndPTManagement.util.enums.GenderEnum;
import com.se100.GymAndPTManagement.util.enums.UserStatusEnum;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 02:44:02
 * Purpose: Request DTO for creating new member
 */
@Data
public class ReqCreateMemberDTO {

    @NotBlank(message = "Fullname không được để trống")
    @Size(max = 100, message = "Fullname không được vượt quá 100 ký tự")
    private String fullname;

    @NotBlank(message = "Email không được để trống")
    @Email(message = "Email không hợp lệ")
    @Size(max = 150, message = "Email không được vượt quá 150 ký tự")
    private String email;

    @Size(min = 8, message = "Password phải có ít nhất 8 ký tự")
    private String password;

    @Size(max = 15, message = "Phone number không được vượt quá 15 ký tự")
    private String phoneNumber;

    @Size(max = 500, message = "Avatar URL không được vượt quá 500 ký tự")
    private String avatarUrl;

    private LocalDate dob;

    private GenderEnum gender;

    private UserStatusEnum status;

    @Size(min = 12, max = 12, message = "CCCD phải có đúng 12 ký tự")
    private String cccd;
}
