/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-19
 * Purpose: Request DTO for updating checkin log information
 */
package com.se100.GymAndPTManagement.domain.requestDTO;

import jakarta.validation.constraints.*;
import lombok.*;
import java.time.LocalTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqUpdateCheckinDTO {

    @NotNull(message = "Booking ID không được để trống")
    private Long bookingId;

    @NotNull(message = "Member ID không được để trống")
    private Long memberId;

    @NotNull(message = "Thời gian checkin không được để trống")
    private LocalTime checkinTime;

    private LocalTime checkoutTime;
}
