package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;

import jakarta.validation.constraints.DecimalMin;
import lombok.Data;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 17:00:00
 * Purpose: Request DTO for updating diet detail
 */
@Data
public class ReqUpdateDietDetailDTO {

    private String prepMethod;

    @DecimalMin(value = "0.0", inclusive = true, message = "Khối lượng phải >= 0")
    private BigDecimal amount;

    private String note;
}
