package com.se100.GymAndPTManagement.domain.requestDTO;

import java.time.LocalTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-13 23:53:21
 * Purpose: Request DTO for updating slot
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqUpdateSlotDTO {

    @NotBlank(message = "Slot name is required")
    private String slotName;

    @NotNull(message = "Start time is required")
    private LocalTime startTime;

    @NotNull(message = "End time is required")
    private LocalTime endTime;
}
