package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;

import com.se100.GymAndPTManagement.util.enums.PackageTypeEnum;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 09:30:43
 * Purpose: Request DTO for updating service package
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqUpdateServicePackageDTO {

    private String packageName;

    @DecimalMin(value = "0.0", inclusive = true, message = "Price must be greater than or equal to 0")
    private BigDecimal price;

    private PackageTypeEnum type;

    private Boolean isActive;

    private String description;

    @Min(value = 1, message = "Duration in days must be at least 1")
    private Integer durationInDays;

    @Min(value = 0, message = "Number of sessions must be non-negative")
    private Integer numberOfSessions;
}
