package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.validation.constraints.DecimalMin;
import lombok.Data;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 16:30:00
 * Purpose: Request DTO for updating daily diet
 */
@Data
public class ReqUpdateDailyDietDTO {

    private Long ptId; // Optional - có thể cập nhật PT phụ trách

    private LocalDate dietDate;

    @DecimalMin(value = "0.0", inclusive = true, message = "Lượng nước phải >= 0")
    private BigDecimal waterLiters;

    private String note;
}
