package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 14:30:00
 * Purpose: Request DTO for updating food
 */
@Data
public class ReqUpdateFoodDTO {

    @Size(max = 255, message = "Tên thực phẩm không được vượt quá 255 ký tự")
    private String name;

    private String description;

    @DecimalMin(value = "0.0", inclusive = true, message = "Protein phải >= 0")
    private BigDecimal proteinG;

    @DecimalMin(value = "0.0", inclusive = true, message = "Carbohydrate phải >= 0")
    private BigDecimal carbsG;

    @DecimalMin(value = "0.0", inclusive = true, message = "Fat phải >= 0")
    private BigDecimal fatG;

    private String note;
}
