/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-19
 * Purpose: Request DTO for updating invoice information and details
 */
package com.se100.GymAndPTManagement.domain.requestDTO;

import java.math.BigDecimal;
import java.util.List;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqUpdateInvoiceDTO {

    @NotNull(message = "Member ID không được để trống")
    private Long memberId;

    @NotNull(message = "Chiết khấu không được để trống")
    @DecimalMin(value = "0", message = "Chiết khấu phải >= 0")
    private BigDecimal discountAmount;

    @NotNull(message = "Phương thức thanh toán không được để trống")
    private String paymentMethod;

    @NotEmpty(message = "Chi tiết hóa đơn không được để trống")
    @Valid
    private List<ReqUpdateInvoiceDetailDTO> details;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ReqUpdateInvoiceDetailDTO {
        
        @NotNull(message = "Detail ID không được để trống")
        private Long detailId;

        private Long servicePackageId;

        private Long additionalServiceId;

        @NotNull(message = "Số lượng không được để trống")
        @Positive(message = "Số lượng phải lớn hơn 0")
        private Integer quantity;

        @NotNull(message = "Đơn giá không được để trống")
        @DecimalMin(value = "0", message = "Đơn giá phải >= 0")
        private BigDecimal unitPrice;
    }
}
