/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Request DTO for WorkoutImage
 */

package com.se100.GymAndPTManagement.domain.requestDTO;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqWorkoutImageDTO {
    
    @NotNull(message = "ID bài tập không được để trống")
    private Long workoutId;
    
    @NotBlank(message = "URL hình ảnh không được để trống")
    private String imageUrl;
    
    private String imagePath;
    
    private String description;
    
    @Min(value = 1, message = "Thứ tự hiển thị phải >= 1")
    private Integer displayOrder;
}






