/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: Request DTO for WorkoutDevice
 */

package com.se100.GymAndPTManagement.domain.requestDTO;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReqWorkoutDeviceDTO {
    
    @NotBlank(message = "Tên thiết bị không được để trống")
    private String name;
    
    private String description;
    
    private String equipmentType;
    
    private String equipmentPhoto;
    
    @NotNull(message = "Số lượng không được để trống")
    @Min(value = 1, message = "Số lượng phải >= 1")
    private Integer quantity;
    
    @DecimalMin(value = "0.0", inclusive = false, message = "Giá mua phải > 0")
    private BigDecimal purchasePrice;
    
    private LocalDate purchaseDate;
    
    private LocalDate lastMaintenanceDate;
    
    private LocalDate nextMaintenanceDate;
}






