package com.se100.GymAndPTManagement.controller;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateAvailableSlotDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateAvailableSlotDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateAvailableSlotByUserDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateAvailableSlotForCurrentUserDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateAvailableSlotByUserDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResAvailableSlotDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResAvailableSlotByUserDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.domain.table.AvailableSlot;
import com.se100.GymAndPTManagement.domain.table.PersonalTrainer;
import com.se100.GymAndPTManagement.domain.table.User;
import com.se100.GymAndPTManagement.repository.PersonalTrainerRepository;
import com.se100.GymAndPTManagement.repository.UserRepository;
import com.se100.GymAndPTManagement.service.AvailableSlotService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.se100.GymAndPTManagement.util.error.IdInvalidException;
import com.turkraft.springfilter.boot.Filter;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-14 10:19:59
 * Purpose: REST Controller for AvailableSlot management
 */
@RestController
@RequestMapping("/api/v1/available-slots")
@RequiredArgsConstructor
@Tag(name = "Available Slot Management", description = "APIs for managing personal trainer available time slots")
public class AvailableSlotController {

    private final AvailableSlotService availableSlotService;
    private final PersonalTrainerRepository personalTrainerRepository;
    private final UserRepository userRepository;
    Logger logger = LoggerFactory.getLogger(AvailableSlotController.class);

    @Operation(summary = "Create new available slot")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Available slot created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "PT or Slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PostMapping
    @ApiMessage("Create new available slot") // approved
    public ResponseEntity<ResAvailableSlotDTO> createAvailableSlot(
            @Valid @RequestBody ReqCreateAvailableSlotDTO request) {
        logger.info(">>AVAILABLE SLOT CONTROLLER: Creating new available slot for PT: {}, Slot: {}, Day: {}",
                request.getPtId(), request.getSlotId(), request.getDayOfWeek());
        ResAvailableSlotDTO created = availableSlotService.createAvailableSlot(request);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Created available slot with ID: {}", created.getId());
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @Operation(summary = "Get all available slots")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping
    @ApiMessage("Get all available slots") // approved
    public ResponseEntity<List<ResAvailableSlotDTO>> getAllAvailableSlots() {
        List<ResAvailableSlotDTO> slots = availableSlotService.getAllAvailableSlots();
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved all available slots, count: {}", slots.size());
        return ResponseEntity.ok(slots);
    }

    @Operation(
        summary = "Get my available slots",
        description = "Retrieve all available time slots for the currently authenticated personal trainer user. "
                    + "Validates user authentication, confirms user exists in database, and verifies user has a PT profile. "
                    + "Returns a list of all available slots assigned to this PT.\n\n"
                    + "**Authentication Required:** Yes\n"
                    + "**Authorization:** PT User (user must have PersonalTrainer profile)"
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success - returns available slots list for logged-in PT user"),
            @ApiResponse(responseCode = "401", description = "Unauthorized - user not authenticated or user ID not found in database"),
            @ApiResponse(responseCode = "403", description = "Forbidden - authenticated user is not a personal trainer"),
            @ApiResponse(responseCode = "500", description = "Internal server error during slot retrieval")
    })
    @GetMapping("/my-available-slots")
    @ApiMessage("Get my available slots (for logged-in PT user)")
    public ResponseEntity<?> getMyAvailableSlots() {
        try {
            // Get current authenticated user
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication == null || !authentication.isAuthenticated()) {
                logger.warn(">>AVAILABLE SLOT CONTROLLER: Unauthorized access to my-available-slots");
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                        .body(RestResponse.builder()
                                .statusCode(401)
                                .message("User not authenticated")
                                .build());
            }

            // Get username from authentication principal
            String username = authentication.getName();
            logger.info(">>AVAILABLE SLOT CONTROLLER: Getting available slots for username: {}", username);

            // Find user by email (username)
            User currentUser = userRepository.findByEmail(username).orElse(null);
            if (currentUser == null) {
                logger.error(">>AVAILABLE SLOT CONTROLLER: User with email {} not found in database", username);
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                        .body(RestResponse.builder()
                                .statusCode(401)
                                .message("User not found in database")
                                .build());
            }
            Long userId = currentUser.getId();
            logger.info(">>AVAILABLE SLOT CONTROLLER: Found user ID: {} for username: {}", userId, username);

            // Find PT profile for current user
            PersonalTrainer pt = personalTrainerRepository.findByUserId(userId)
                    .orElse(null);

            if (pt == null) {
                logger.warn(">>AVAILABLE SLOT CONTROLLER: PT profile not found for user: {}", userId);
                return ResponseEntity.status(HttpStatus.FORBIDDEN)
                        .body(RestResponse.builder()
                                .statusCode(403)
                                .message("User is not a personal trainer")
                                .build());
            }

            // Get all available slots for this PT
            List<ResAvailableSlotDTO> slots = availableSlotService.getMyAvailableSlots(pt.getId());
            logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved {} available slots for PT: {} (User: {})", 
                    slots.size(), pt.getId(), userId);

            return ResponseEntity.ok(
                    RestResponse.builder()
                            .statusCode(200)
                            .message("Available slots retrieved successfully")
                            .data(slots)
                            .build());

        } catch (Exception e) {
            logger.error(">>AVAILABLE SLOT CONTROLLER: Error retrieving my available slots", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(RestResponse.builder()
                            .statusCode(500)
                            .message("Internal server error: " + e.getMessage())
                            .build());
        }
    }

    @Operation(summary = "Fetch available slots with filter and pagination")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/fetch")
    @ApiMessage("Fetch available slots with filter") // approved
    public ResponseEntity<ResultPaginationDTO> fetchAvailableSlotsWithFilter(
            @Parameter(name = "filter", description = "Spring-Filter expression. VD: dayOfWeek=='MONDAY' and isAvailable==true", required = false, example = "dayOfWeek=='MONDAY'") @Filter Specification<AvailableSlot> specification,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO slots = availableSlotService.handleFetchAvailableSlots(specification, pageable);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Fetched available slots with pagination, page: {}, size: {}",
                pageable.getPageNumber() + 1, pageable.getPageSize());
        return ResponseEntity.ok(slots);
    }

    @Operation(summary = "Get available slot by ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Available slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/{id}")
    @ApiMessage("Get available slot by ID") // approved
    public ResponseEntity<ResAvailableSlotDTO> getAvailableSlotById(@PathVariable("id") Long id) {
        ResAvailableSlotDTO slot = availableSlotService.getAvailableSlotById(id);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slot with ID: {}", id);
        return ResponseEntity.ok(slot);
    }

    @Operation(summary = "Get available slots by PT ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "PT not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/pt/{ptId}")
    @ApiMessage("Get available slots by PT ID") // approved
    public ResponseEntity<List<ResAvailableSlotDTO>> getAvailableSlotsByPtId(@PathVariable("ptId") Long ptId) {
        List<ResAvailableSlotDTO> slots = availableSlotService.getAvailableSlotsByPtId(ptId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slots for PT: {}, count: {}", ptId, slots.size());
        return ResponseEntity.ok(slots);
    }

    @Operation(summary = "Get available slots by PT ID (only available)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "PT not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/pt/{ptId}/available")
    @ApiMessage("Get available slots by PT ID (only available)") // approved
    public ResponseEntity<List<ResAvailableSlotDTO>> getAvailableSlotsByPtIdAndAvailable(
            @PathVariable("ptId") Long ptId) {
        List<ResAvailableSlotDTO> slots = availableSlotService.getAvailableSlotsByPtIdAndAvailable(ptId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slots (available only) for PT: {}, count: {}",
                ptId, slots.size());
        return ResponseEntity.ok(slots);
    }

    @Operation(summary = "Get all available slots by status")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/status/{isAvailable}")
    @ApiMessage("Get all available slots by status") // approved
    public ResponseEntity<List<ResAvailableSlotDTO>> getAllAvailableSlotsByStatus(
            @PathVariable("isAvailable") Boolean isAvailable) {
        try {
            List<ResAvailableSlotDTO> slots = availableSlotService.getAllAvailableSlotsByStatus(isAvailable);
            logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slots with status: {}, count: {}", isAvailable,
                    slots.size());
            return ResponseEntity.ok(slots);
        } catch (Exception e) {
            logger.error(">>AVAILABLE SLOT CONTROLLER: Error retrieving slots by status: {}", isAvailable, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new java.util.ArrayList<>());
        }
    }

    @Operation(summary = "Update available slot")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot updated successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot or Slot not found"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{availableSlotId}")
    @ApiMessage("Update available slot") // approved
    public ResponseEntity<ResAvailableSlotDTO> updateAvailableSlot(
            @PathVariable("availableSlotId") Long availableSlotId,
            @Valid @RequestBody ReqUpdateAvailableSlotDTO request) {
        ResAvailableSlotDTO updated = availableSlotService.updateAvailableSlot(availableSlotId, request);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Updated available slot with ID: {}", availableSlotId);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Set available slot as available")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot set as available successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{availableSlotId}/set-available")
    @ApiMessage("Set available slot as available") // approved
    public ResponseEntity<ResAvailableSlotDTO> setAvailable(@PathVariable("availableSlotId") Long availableSlotId) {
        ResAvailableSlotDTO updated = availableSlotService.setAvailableStatus(availableSlotId, true);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Set available slot ID: {} as available", availableSlotId);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Set available slot as unavailable")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot set as unavailable successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{availableSlotId}/set-unavailable")
    @ApiMessage("Set available slot as unavailable") // approved
    public ResponseEntity<ResAvailableSlotDTO> setUnavailable(@PathVariable("availableSlotId") Long availableSlotId) {
        ResAvailableSlotDTO updated = availableSlotService.setAvailableStatus(availableSlotId, false);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Set available slot ID: {} as unavailable", availableSlotId);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Delete available slot (soft delete)")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Available slot deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/{availableSlotId}")
    @ApiMessage("Delete available slot") // approved
    public ResponseEntity<Void> deleteAvailableSlot(@PathVariable("availableSlotId") Long availableSlotId) {
        availableSlotService.deleteAvailableSlot(availableSlotId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Deleted available slot with ID: {}", availableSlotId);
        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
    }

    @Operation(summary = "Set available by slotId, ptId and dayOfWeek. dayOfWeek could be written in any case (e.g., MONDAY, monday, Monday)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot set as available successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot, PT or Slot not found"),
            @ApiResponse(responseCode = "400", description = "Invalid day of week"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/set-available/slot/{slotId}/pt/{ptId}/day/{dayOfWeek}")
    @ApiMessage("Set available by slotId, ptId and dayOfWeek")
    public ResponseEntity<ResAvailableSlotDTO> setAvailableBySlotPtDay(
            @PathVariable("slotId") Long slotId,
            @PathVariable("ptId") Long ptId,
            @PathVariable("dayOfWeek") String dayOfWeek) {
        ResAvailableSlotDTO updated = availableSlotService.setAvailableBySlotPtDay(slotId, ptId, dayOfWeek);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Set available for slotId: {}, ptId: {}, dayOfWeek: {}",
                slotId, ptId, dayOfWeek);
        return ResponseEntity.ok(updated);
    }

    // ==================== USER-BASED AVAILABLE SLOT ENDPOINTS ====================

    @Operation(summary = "Create new available slot by user ID")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Available slot created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "User or Slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PostMapping("/user")
    @ApiMessage("Create new available slot by user ID")
    public ResponseEntity<ResAvailableSlotByUserDTO> createAvailableSlotByUser(
            @Valid @RequestBody ReqCreateAvailableSlotByUserDTO request) {
        logger.info(">>AVAILABLE SLOT CONTROLLER: Creating new available slot for User: {}, Slot: {}, Day: {}",
                request.getUserId(), request.getSlotId(), request.getDayOfWeek());
        ResAvailableSlotByUserDTO created = availableSlotService.createAvailableSlotByUser(request);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Created available slot with ID: {} for User: {}", created.getId(), request.getUserId());
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    @Operation(
        summary = "Create new available slot for current logged-in user",
        description = "Create a new available time slot for the currently authenticated user. "
                    + "The slot will be assigned to the logged-in user's PT profile if they are a personal trainer. "
                    + "Requires authentication and validates that the requested slot exists.\n\n"
                    + "**Authentication Required:** Yes\n"
                    + "**Request Body:** slotId and dayOfWeek"
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Available slot created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "Slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized - user not authenticated or not found in database")
    })
    @PostMapping("/user/my-slot")
    @ApiMessage("Create new available slot for current logged-in user")
    public ResponseEntity<?> createAvailableSlotForCurrentUser(
            @Valid @RequestBody ReqCreateAvailableSlotForCurrentUserDTO request) {
        try {
            // Verify user is authenticated
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication == null || !authentication.isAuthenticated()) {
                logger.warn(">>AVAILABLE SLOT CONTROLLER: Unauthorized access to create my-slot");
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                        .body(RestResponse.builder()
                                .statusCode(401)
                                .message("User not authenticated")
                                .build());
            }

            logger.info(">>AVAILABLE SLOT CONTROLLER: Creating new available slot for current user, Slot: {}, Day: {}",
                    request.getSlotId(), request.getDayOfWeek());
            ResAvailableSlotByUserDTO created = availableSlotService.createAvailableSlotForCurrentUser(request);
            logger.info(">>AVAILABLE SLOT CONTROLLER: Created available slot with ID: {}", created.getId());
            return ResponseEntity.status(HttpStatus.CREATED).body(created);
        } catch (IdInvalidException e) {
            logger.error(">>AVAILABLE SLOT CONTROLLER: Invalid data - {}", e.getMessage());
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body(RestResponse.builder()
                            .statusCode(401)
                            .message(e.getMessage())
                            .build());
        } catch (Exception e) {
            logger.error(">>AVAILABLE SLOT CONTROLLER: Error creating available slot for current user", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(RestResponse.builder()
                            .statusCode(500)
                            .message("Internal server error: " + e.getMessage())
                            .build());
        }
    }

    @Operation(summary = "Get all available slots by user ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "User not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/user/{userId}")
    @ApiMessage("Get all available slots by user ID")
    public ResponseEntity<List<ResAvailableSlotByUserDTO>> getAvailableSlotsByUserId(
            @PathVariable("userId") Long userId) {
        List<ResAvailableSlotByUserDTO> slots = availableSlotService.getAllAvailableSlotsByUserId(userId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slots for User: {}, count: {}", userId, slots.size());
        return ResponseEntity.ok(slots);
    }

    @Operation(summary = "Get available slots by user ID (only available)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "User not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/user/{userId}/available")
    @ApiMessage("Get available slots by user ID (only available)")
    public ResponseEntity<List<ResAvailableSlotByUserDTO>> getAvailableSlotsByUserIdAndAvailable(
            @PathVariable("userId") Long userId) {
        List<ResAvailableSlotByUserDTO> slots = availableSlotService.getAvailableSlotsByUserIdAndAvailable(userId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Retrieved available slots (available only) for User: {}, count: {}",
                userId, slots.size());
        return ResponseEntity.ok(slots);
    }

    @Operation(summary = "Update available slot by user ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot updated successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot or Slot not found"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/user/{availableSlotId}")
    @ApiMessage("Update available slot by user ID")
    public ResponseEntity<ResAvailableSlotByUserDTO> updateAvailableSlotByUser(
            @PathVariable("availableSlotId") Long availableSlotId,
            @Valid @RequestBody ReqUpdateAvailableSlotByUserDTO request) {
        ResAvailableSlotByUserDTO updated = availableSlotService.updateAvailableSlotByUser(availableSlotId, request);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Updated available slot with ID: {}", availableSlotId);
        return ResponseEntity.ok(updated);
    }

    @Operation(summary = "Delete available slot by user ID (soft delete)")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Available slot deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/user/{availableSlotId}")
    @ApiMessage("Delete available slot by user ID")
    public ResponseEntity<Void> deleteAvailableSlotByUser(@PathVariable("availableSlotId") Long availableSlotId) {
        availableSlotService.deleteAvailableSlotByUser(availableSlotId);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Deleted available slot with ID: {}", availableSlotId);
        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
    }

    @Operation(summary = "Set available by slotId, userId and dayOfWeek. dayOfWeek could be written in any case (e.g., MONDAY, monday, Monday)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Available slot set as available successfully"),
            @ApiResponse(responseCode = "404", description = "Available slot, User or Slot not found"),
            @ApiResponse(responseCode = "400", description = "Invalid day of week"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/user/set-available/slot/{slotId}/user/{userId}/day/{dayOfWeek}")
    @ApiMessage("Set available by slotId, userId and dayOfWeek")
    public ResponseEntity<ResAvailableSlotByUserDTO> setAvailableBySlotUserDay(
            @PathVariable("slotId") Long slotId,
            @PathVariable("userId") Long userId,
            @PathVariable("dayOfWeek") String dayOfWeek) {
        ResAvailableSlotByUserDTO updated = availableSlotService.setAvailableBySlotUserDay(slotId, userId, dayOfWeek);
        logger.info(">>AVAILABLE SLOT CONTROLLER: Set available for slotId: {}, userId: {}, dayOfWeek: {}",
                slotId, userId, dayOfWeek);
        return ResponseEntity.ok(updated);
    }
}
