/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 10:15:00
 * Purpose: REST Controller for Booking management with dynamic filtering endpoints
 */
package com.se100.GymAndPTManagement.controller;

import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateBookingDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateBookingPTDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.domain.responseDTO.ResBookingDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResAvailableSlotDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResAvailablePTDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.service.BookingService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/v1/bookings")
@RequiredArgsConstructor
public class BookingController {

    private final BookingService bookingService;

    /**
     * Get all bookings with pagination
     * 
     * @param pageable Pagination parameters (page, size, sort)
     * @return Paginated list of all bookings
     */
    @GetMapping
    @ApiMessage("Lấy danh sách tất cả lịch đặt")
    public ResponseEntity<ResultPaginationDTO> getAllBookings(@ParameterObject Pageable pageable) {

        ResultPaginationDTO result = bookingService.getAllBookings(pageable);

        return ResponseEntity.ok(result);
    }

    /**
     * Get available slots for a PT on a specific date (Flow 1: Choose PT -> Get Slots)
     * 
     * @param ptId Personal Trainer ID
     * @param date Booking date (format: yyyy-MM-dd)
     * @return List of available slots
     */
    @GetMapping("/available-slots")
    @ApiMessage("Lấy danh sách khung giờ còn trống cho PT")
    public ResponseEntity<RestResponse<List<ResAvailableSlotDTO>>> getAvailableSlotsForPT(
            @RequestParam Long ptId,
            @RequestParam LocalDate date) {

        List<ResAvailableSlotDTO> availableSlots = bookingService.getAvailableSlotsForPT(ptId, date);

        return ResponseEntity.ok(
                RestResponse.<List<ResAvailableSlotDTO>>builder()
                        .statusCode(200)
                        .message("Lấy danh sách khung giờ thành công")
                        .data(availableSlots)
                        .build());
    }

    /**
     * Get available PTs for a specific slot on a specific date (Flow 2: Choose Slot -> Get PTs)
     * 
     * @param slotId Slot ID
     * @param date Booking date (format: yyyy-MM-dd)
     * @return List of available PTs
     */
    @GetMapping("/available-pts")
    @ApiMessage("Lấy danh sách PT còn trống cho khung giờ")
    public ResponseEntity<RestResponse<List<ResAvailablePTDTO>>> getAvailablePTsForSlot(
            @RequestParam Long slotId,
            @RequestParam LocalDate date) {

        List<ResAvailablePTDTO> availablePTs = bookingService.getAvailablePTsForSlot(slotId, date);

        return ResponseEntity.ok(
                RestResponse.<List<ResAvailablePTDTO>>builder()
                        .statusCode(200)
                        .message("Lấy danh sách PT thành công")
                        .data(availablePTs)
                        .build());
    }

    /**
     * Create a new booking
     * 
     * @param dto Create booking request DTO
     * @return Created booking details
     */
    @PostMapping
    @ApiMessage("Tạo lịch đặt mới")
    public ResponseEntity<RestResponse<ResBookingDTO>> createBooking(
            @Valid @RequestBody ReqCreateBookingDTO dto) {

        try {
            ResBookingDTO createdBooking = bookingService.createBooking(dto);

            return ResponseEntity.ok(
                    RestResponse.<ResBookingDTO>builder()
                            .statusCode(200)
                            .message("Tạo lịch đặt thành công")
                            .data(createdBooking)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResBookingDTO>builder()
                            .statusCode(400)
                            .error("VALIDATION_ERROR")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Get all bookings for a specific member with pagination
     * 
     * @param memberId Member ID
     * @param pageable Pagination parameters
     * @return Paginated list of member's bookings
     */
    @GetMapping("/member/{memberId}")
    @ApiMessage("Lấy danh sách lịch đặt của thành viên")
    public ResponseEntity<ResultPaginationDTO> getBookingsByMember(
            @PathVariable Long memberId,
            @ParameterObject Pageable pageable) {

        ResultPaginationDTO result = bookingService.getBookingsByMember(memberId, pageable);

        return ResponseEntity.ok(result);
    }

    /**
     * Get all bookings for a specific PT with pagination
     * 
     * @param ptId Personal Trainer ID
     * @param pageable Pagination parameters
     * @return Paginated list of PT's bookings
     */
    @GetMapping("/pt/{ptId}")
    @ApiMessage("Lấy danh sách lịch đặt của PT")
    public ResponseEntity<ResultPaginationDTO> getBookingsByPT(
            @PathVariable Long ptId,
            @ParameterObject Pageable pageable) {

        ResultPaginationDTO result = bookingService.getBookingsByPT(ptId, pageable);

        return ResponseEntity.ok(result);
    }

    /**
     * Get booking details by ID
     * 
     * @param bookingId Booking ID
     * @return Booking details
     */
    @GetMapping("/{bookingId}")
    @ApiMessage("Lấy chi tiết lịch đặt")
    public ResponseEntity<RestResponse<ResBookingDTO>> getBookingById(
            @PathVariable Long bookingId) {

        try {
            ResBookingDTO booking = bookingService.getBookingById(bookingId);

            return ResponseEntity.ok(
                    RestResponse.<ResBookingDTO>builder()
                            .statusCode(200)
                            .message("Lấy chi tiết lịch đặt thành công")
                            .data(booking)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResBookingDTO>builder()
                            .statusCode(400)
                            .error("NOT_FOUND")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Update personal trainer for a booking
     * PUT /api/v1/bookings/{bookingId}/pt
     * 
     * @param bookingId Booking ID
     * @param newPtId New PT ID (from request body)
     * @return Updated booking details
     */
    @PutMapping("/{bookingId}/pt")
    @ApiMessage("Cập nhật PT cho lịch đặt")
    public ResponseEntity<RestResponse<ResBookingDTO>> updateBookingPT(
            @PathVariable Long bookingId,
            @RequestParam Long ptId) {

        try {
            ResBookingDTO updatedBooking = bookingService.updateBookingPT(bookingId, ptId);

            return ResponseEntity.ok(
                    RestResponse.<ResBookingDTO>builder()
                            .statusCode(200)
                            .message("Cập nhật PT thành công")
                            .data(updatedBooking)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResBookingDTO>builder()
                            .statusCode(400)
                            .error("VALIDATION_ERROR")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Delete a booking
     * 
     * @param bookingId Booking ID
     */
    @DeleteMapping("/{bookingId}")
    @ApiMessage("Xóa lịch đặt")
    public ResponseEntity<RestResponse<Void>> deleteBooking(
            @PathVariable Long bookingId) {

        try {
            bookingService.deleteBooking(bookingId);

            return ResponseEntity.ok(
                    RestResponse.<Void>builder()
                            .statusCode(200)
                            .message("Xóa lịch đặt thành công")
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<Void>builder()
                            .statusCode(400)
                            .error("NOT_FOUND")
                            .message(e.getMessage())
                            .build());
        }
    }
}
