/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-14 11:15:00
 * Purpose: REST Controller for Checkin Log management
 */
package com.se100.GymAndPTManagement.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCheckinDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.domain.responseDTO.ResCheckinLogDTO;
import com.se100.GymAndPTManagement.service.CheckinLogService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

import java.util.List;

@RestController
@RequestMapping("/api/v1/checkins")
@RequiredArgsConstructor
public class CheckinLogController {

    private final CheckinLogService checkinLogService;

    /**
     * Check-in: Create a new checkin log when member arrives
     * 
     * @param dto Check-in request with booking ID
     * @return Created checkin log details
     */
    @PostMapping
    @ApiMessage("Tạo check-in log khi thành viên đến tập")
    public ResponseEntity<RestResponse<ResCheckinLogDTO>> checkIn(
            @Valid @RequestBody ReqCheckinDTO dto) {

        try {
            ResCheckinLogDTO createdLog = checkinLogService.checkIn(dto);

            return ResponseEntity.ok(
                    RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(200)
                            .message("Check-in thành công")
                            .data(createdLog)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(400)
                            .error("VALIDATION_ERROR")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Check-out: Update checkin log when member finishes workout
     * 
     * @param bookingId Booking ID to identify the checkin log
     * @return Updated checkin log details
     */
    @PutMapping("/checkout/{bookingId}")
    @ApiMessage("Cập nhật check-out khi thành viên kết thúc buổi tập")
    public ResponseEntity<RestResponse<ResCheckinLogDTO>> checkOut(
            @PathVariable Long bookingId) {

        try {
            ResCheckinLogDTO updatedLog = checkinLogService.checkOut(bookingId);

            return ResponseEntity.ok(
                    RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(200)
                            .message("Check-out thành công")
                            .data(updatedLog)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(400)
                            .error("NOT_FOUND")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Cancel: Cancel a checkin log when admin makes a mistake
     * 
     * @param bookingId Booking ID to identify the checkin log
     * @return Updated checkin log with CANCELLED status
     */
    @PutMapping("/cancel/{bookingId}")
    @ApiMessage("Hủy check-in khi admin thao tác nhầm")
    public ResponseEntity<RestResponse<ResCheckinLogDTO>> cancelCheckin(
            @PathVariable Long bookingId) {

        try {
            ResCheckinLogDTO cancelledLog = checkinLogService.cancelCheckin(bookingId);

            return ResponseEntity.ok(
                    RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(200)
                            .message("Hủy check-in thành công")
                            .data(cancelledLog)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(400)
                            .error("NOT_FOUND")
                            .message(e.getMessage())
                            .build());
        }
    }

    /**
     * Get all checkin logs for a specific member
     * 
     * @param memberId Member ID
     * @return List of checkin logs
     */
    @GetMapping("/member/{memberId}")
    @ApiMessage("Lấy danh sách check-in của thành viên")
    public ResponseEntity<RestResponse<List<ResCheckinLogDTO>>> getCheckinsByMember(
            @PathVariable Long memberId) {

        List<ResCheckinLogDTO> logs = checkinLogService.getCheckinsByMember(memberId);

        return ResponseEntity.ok(
                RestResponse.<List<ResCheckinLogDTO>>builder()
                        .statusCode(200)
                        .message("Lấy danh sách check-in thành công")
                        .data(logs)
                        .build());
    }

    /**
     * Get all checkin logs for a specific booking
     * 
     * @param bookingId Booking ID
     * @return List of checkin logs
     */
    @GetMapping("/booking/{bookingId}")
    @ApiMessage("Lấy danh sách check-in của lịch đặt")
    public ResponseEntity<RestResponse<List<ResCheckinLogDTO>>> getCheckinsByBooking(
            @PathVariable Long bookingId) {

        List<ResCheckinLogDTO> logs = checkinLogService.getCheckinsByBooking(bookingId);

        return ResponseEntity.ok(
                RestResponse.<List<ResCheckinLogDTO>>builder()
                        .statusCode(200)
                        .message("Lấy danh sách check-in thành công")
                        .data(logs)
                        .build());
    }

    /**
     * Get checkin log by ID
     * 
     * @param checkinId Checkin log ID
     * @return Checkin log details
     */
    @GetMapping("/{checkinId}")
    @ApiMessage("Lấy chi tiết check-in log")
    public ResponseEntity<RestResponse<ResCheckinLogDTO>> getCheckinById(
            @PathVariable Long checkinId) {

        try {
            ResCheckinLogDTO log = checkinLogService.getCheckinById(checkinId);

            return ResponseEntity.ok(
                    RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(200)
                            .message("Lấy chi tiết check-in thành công")
                            .data(log)
                            .build());

        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest()
                    .body(RestResponse.<ResCheckinLogDTO>builder()
                            .statusCode(400)
                            .error("NOT_FOUND")
                            .message(e.getMessage())
                            .build());
        }
    }
}
