/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-09 14:50:00
 * Purpose: REST Controller for Contract entity endpoints
 */
package com.se100.GymAndPTManagement.controller;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateContractDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResContractDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.domain.table.Contract;
import com.se100.GymAndPTManagement.service.ContractService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.se100.GymAndPTManagement.util.FormatRestResponse;
import com.se100.GymAndPTManagement.util.enums.ContractStatusEnum;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/v1/contracts")
public class ContractController {
    
    private final ContractService contractService;
    
    public ContractController(ContractService contractService) {
        this.contractService = contractService;
    }
    
    @PostMapping
    @ApiMessage("Create new contract with automatic invoice generation")
    public ResponseEntity<RestResponse<ResContractDTO>> createContract(@Valid @RequestBody ReqCreateContractDTO request) {
        try {
            ResContractDTO contract = contractService.createContractWithInvoice(request);
            return ResponseEntity.status(HttpStatus.CREATED)
                .body(FormatRestResponse.success(contract, "Contract created successfully"));
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(FormatRestResponse.error(e.getMessage()));
        }
    }
    
    @GetMapping
    @ApiMessage("Get all contracts")
    public ResponseEntity<RestResponse<List<ResContractDTO>>> getAllContracts() {
        List<Contract> contracts = contractService.getAllContracts();
        List<ResContractDTO> result = contracts.stream()
            .map(this::mapContractToDTO)
            .toList();
        return ResponseEntity.ok(FormatRestResponse.success(result));
    }
    
    @GetMapping("/{id}")
    @ApiMessage("Get contract by ID")
    public ResponseEntity<RestResponse<ResContractDTO>> getContractById(@PathVariable Long id) {
        return contractService.getContractById(id)
            .map(contract -> {
                ResContractDTO dto = mapContractToDTO(contract);
                return ResponseEntity.ok(FormatRestResponse.success(dto));
            })
            .orElse(ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(FormatRestResponse.error("Contract not found")));
    }
    
    @GetMapping("/member/{memberId}")
    @ApiMessage("Get contracts by member ID")
    public ResponseEntity<RestResponse<List<ResContractDTO>>> getContractsByMember(@PathVariable Long memberId) {
        List<Contract> contracts = contractService.getContractsByMember(memberId);
        List<ResContractDTO> result = contracts.stream()
            .map(this::mapContractToDTO)
            .toList();
        return ResponseEntity.ok(FormatRestResponse.success(result));
    }
    
    @GetMapping("/pt/{ptId}")
    @ApiMessage("Get contracts by personal trainer ID")
    public ResponseEntity<RestResponse<List<ResContractDTO>>> getContractsByPt(@PathVariable Long ptId) {
        List<Contract> contracts = contractService.getContractsByPt(ptId);
        List<ResContractDTO> result = contracts.stream()
            .map(this::mapContractToDTO)
            .toList();
        return ResponseEntity.ok(FormatRestResponse.success(result));
    }
    
    @GetMapping("/status/{status}")
    @ApiMessage("Get contracts by status")
    public ResponseEntity<RestResponse<List<ResContractDTO>>> getContractsByStatus(@PathVariable String status) {
        try {
            // Convert String to ContractStatusEnum with validation
            ContractStatusEnum statusEnum = ContractStatusEnum.valueOf(status.toUpperCase());
            List<Contract> contracts = contractService.getContractsByStatus(statusEnum);
            List<ResContractDTO> result = contracts.stream()
                .map(this::mapContractToDTO)
                .toList();
            return ResponseEntity.ok(FormatRestResponse.success(result));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(FormatRestResponse.error("Invalid status: " + status + ". Valid values: ACTIVE, EXPIRED, CANCELLED"));
        }
    }
    
    // =========================================
    // Mapper
    // =========================================
    private ResContractDTO mapContractToDTO(Contract contract) {
        return ResContractDTO.builder()
                .id(contract.getId())
                .memberId(contract.getMember().getId())
                .memberName(contract.getMember().getUser().getFullname())
                .packageId(contract.getServicePackage().getId())
                .packageName(contract.getServicePackage().getPackageName())
                .packagePrice(contract.getServicePackage().getPrice())
                .ptId(contract.getMainPt() != null ? contract.getMainPt().getId() : null)
                .ptName(contract.getMainPt() != null ? contract.getMainPt().getUser().getFullname() : null)
                .startDate(contract.getStartDate())
                .endDate(contract.getEndDate())
                .status(contract.getStatus())
                .notes(contract.getNotes())
                .signedAt(contract.getSignedAt())
                .createdAt(contract.getCreatedAt())
                .build();
    }
}
