package com.se100.GymAndPTManagement.controller;

import java.time.LocalDate;

import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.web.PageableDefault;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateDailyDietDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateDailyDietDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDailyDietDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDailyDietBasicDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.DailyDiet;
import com.se100.GymAndPTManagement.service.DailyDietService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.turkraft.springfilter.boot.Filter;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 16:30:00
 * Purpose: DailyDiet controller for daily nutrition plan management
 */
@RestController
@RequestMapping("/api/v1/daily-diets")
@Tag(name = "Daily Diet Management", description = "APIs for managing daily nutrition diets and details")
public class DailyDietController {

    private final DailyDietService dailyDietService;

    public DailyDietController(DailyDietService dailyDietService) {
        this.dailyDietService = dailyDietService;
    }

    @PostMapping
    @Operation(summary = "Create new daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Daily diet created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data or diet already exists"),
            @ApiResponse(responseCode = "404", description = "Member or PT not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @ApiMessage("Tạo thực đơn hàng ngày mới")
    public ResponseEntity<ResDailyDietDTO> createDailyDiet(@Valid @RequestBody ReqCreateDailyDietDTO request) {
        ResDailyDietDTO diet = dailyDietService.createDailyDiet(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(diet);
    }

    @GetMapping
    @Operation(summary = "Get all daily diets (basic info only)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @ApiMessage("Lấy danh sách tất cả thực đơn (không kèm chi tiết)")
    public ResponseEntity<ResultPaginationDTO> getAllDailyDiets(
            @ParameterObject
            @PageableDefault(size = 10, page = 0)
            Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.getAllDailyDietsBasic(pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diet by ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Daily diet not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/{id}")
    @ApiMessage("Lấy thông tin thực đơn theo ID")
    public ResponseEntity<ResDailyDietDTO> getDailyDietById(@PathVariable("id") Long id) {
        ResDailyDietDTO diet = dailyDietService.getDailyDietById(id);
        return ResponseEntity.ok(diet);
    }

    @Operation(summary = "Get daily diets with filter and pagination using SpringFilter")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/fetch")
    @ApiMessage("Lấy danh sách thực đơn với filter và pagination")
    public ResponseEntity<ResultPaginationDTO> fetchDailyDiets(
            @Parameter(description = "Filter expression using SpringFilter syntax") @Filter Specification<DailyDiet> spec,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.handleFetchDailyDiets(spec, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diets by member ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-member/{memberId}")
    @ApiMessage("Lấy danh sách thực đơn theo member")
    public ResponseEntity<ResultPaginationDTO> getDailyDietsByMember(
            @PathVariable("memberId") Long memberId,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.getDailyDietsByMember(memberId, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diets by PT ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-pt/{ptId}")
    @ApiMessage("Lấy danh sách thực đơn do PT tạo")
    public ResponseEntity<ResultPaginationDTO> getDailyDietsByPT(
            @PathVariable("ptId") Long ptId,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.getDailyDietsByPT(ptId, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diets by date range")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-date-range")
    @ApiMessage("Lấy danh sách thực đơn theo khoảng thời gian")
    public ResponseEntity<ResultPaginationDTO> getDailyDietsByDateRange(
            @RequestParam("startDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam("endDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.getDailyDietsByDateRange(startDate, endDate, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diets by member and date range")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-member/{memberId}/date-range")
    @ApiMessage("Lấy thực đơn của member theo khoảng ngày")
    public ResponseEntity<ResultPaginationDTO> getDailyDietsByMemberAndDateRange(
            @PathVariable("memberId") Long memberId,
            @RequestParam("startDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam("endDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dailyDietService.getDailyDietsByMemberAndDateRange(memberId, startDate, endDate,
                pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get daily diet for specific member and date")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Daily diet not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-member/{memberId}/date/{date}")
    @ApiMessage("Lấy thực đơn của member theo ngày cụ thể")
    public ResponseEntity<ResDailyDietDTO> getDailyDietByMemberAndDate(
            @PathVariable("memberId") Long memberId,
            @PathVariable("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        ResDailyDietDTO diet = dailyDietService.getDailyDietByMemberAndDate(memberId, date);
        return ResponseEntity.ok(diet);
    }

    @Operation(summary = "Update daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Daily diet updated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "Daily diet or PT not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}")
    @ApiMessage("Cập nhật thông tin thực đơn")
    public ResponseEntity<ResDailyDietDTO> updateDailyDiet(
            @PathVariable("id") Long id,
            @Valid @RequestBody ReqUpdateDailyDietDTO request) {
        ResDailyDietDTO diet = dailyDietService.updateDailyDiet(id, request);
        return ResponseEntity.ok(diet);
    }

    @Operation(summary = "Delete daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Daily diet deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Daily diet not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/{id}")
    @ApiMessage("Xóa thực đơn")
    public ResponseEntity<Void> deleteDailyDiet(@PathVariable("id") Long id) {
        dailyDietService.deleteDailyDiet(id);
        return ResponseEntity.noContent().build();
    }
}
