/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 14:05:17
 * Purpose: REST Controller for DailyDiet entity management with role-based authorization
 */

package com.se100.GymAndPTManagement.controller;

import java.time.LocalDate;
import java.util.List;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import com.se100.GymAndPTManagement.repository.ResDailyDietDTO;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;

import lombok.AllArgsConstructor;
import main.java.com.se100.GymAndPTManagement.domain.requestDTO.ReqDailyDietDTO;
import main.java.com.se100.GymAndPTManagement.service.DailyDietService;

@RestController
@RequestMapping("/api/v1/daily-diets")
@AllArgsConstructor
@Validated
public class DailyDietController {
    
    private final DailyDietService dailyDietService;
    
    @PostMapping
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Tạo kế hoạch ăn mới (PT)")
    public ResponseEntity<ResDailyDietDTO> createDailyDiet(@Valid @RequestBody ReqDailyDietDTO reqDailyDietDTO) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.createDailyDiet(reqDailyDietDTO);
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.CREATED);
    }
    
    @GetMapping("/{id}")
    @ApiMessage("Lấy thông tin kế hoạch ăn theo ID")
    public ResponseEntity<ResDailyDietDTO> getDailyDietById(@PathVariable Long id) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.getDailyDietById(id);
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.OK);
    }
    
    @GetMapping
    @ApiMessage("Lấy danh sách tất cả kế hoạch ăn (phân trang)")
    public ResponseEntity<Page<ResDailyDietDTO>> getAllDailyDiets(Pageable pageable) {
        Page<ResDailyDietDTO> dailyDiets = dailyDietService.getAllDailyDiets(pageable);
        return new ResponseEntity<>(dailyDiets, HttpStatus.OK);
    }
    
    @GetMapping("/by-member/{memberId}")
    @ApiMessage("Lấy danh sách kế hoạch ăn của hội viên")
    public ResponseEntity<List<ResDailyDietDTO>> getDailyDietsByMemberId(@PathVariable Long memberId) {
        List<ResDailyDietDTO> dailyDiets = dailyDietService.getDailyDietsByMemberId(memberId);
        return new ResponseEntity<>(dailyDiets, HttpStatus.OK);
    }
    
    @GetMapping("/by-member/{memberId}/date/{dietDate}")
    @ApiMessage("Lấy kế hoạch ăn của hội viên vào ngày cụ thể")
    public ResponseEntity<ResDailyDietDTO> getDailyDietByMemberIdAndDate(
            @PathVariable Long memberId,
            @PathVariable String dietDate) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.getDailyDietByMemberIdAndDate(
                memberId, 
                LocalDate.parse(dietDate));
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.OK);
    }
    
    @GetMapping("/by-date-range")
    @ApiMessage("Lấy kế hoạch ăn trong khoảng ngày")
    public ResponseEntity<List<ResDailyDietDTO>> getDailyDietsByDateRange(
            @RequestParam String startDate,
            @RequestParam String endDate) {
        List<ResDailyDietDTO> dailyDiets = dailyDietService.getDailyDietsByDateRange(
                LocalDate.parse(startDate),
                LocalDate.parse(endDate));
        return new ResponseEntity<>(dailyDiets, HttpStatus.OK);
    }
    
    @GetMapping("/by-member/{memberId}/date-range")
    @ApiMessage("Lấy kế hoạch ăn của hội viên trong khoảng ngày")
    public ResponseEntity<List<ResDailyDietDTO>> getDailyDietsByMemberAndDateRange(
            @PathVariable Long memberId,
            @RequestParam String startDate,
            @RequestParam String endDate) {
        List<ResDailyDietDTO> dailyDiets = dailyDietService.getDailyDietsByMemberAndDateRange(
                memberId,
                LocalDate.parse(startDate),
                LocalDate.parse(endDate));
        return new ResponseEntity<>(dailyDiets, HttpStatus.OK);
    }
    
    @GetMapping("/latest/{memberId}")
    @ApiMessage("Lấy kế hoạch ăn mới nhất của hội viên")
    public ResponseEntity<ResDailyDietDTO> getLatestDailyDietByMemberId(@PathVariable Long memberId) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.getLatestDailyDietByMemberId(memberId);
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.OK);
    }
    
    @GetMapping("/search")
    @ApiMessage("Tìm kế hoạch ăn theo tên")
    public ResponseEntity<List<ResDailyDietDTO>> searchDailyDietByPlanName(@RequestParam String planName) {
        List<ResDailyDietDTO> dailyDiets = dailyDietService.searchDailyDietByPlanName(planName);
        return new ResponseEntity<>(dailyDiets, HttpStatus.OK);
    }
    
    @PutMapping("/{id}")
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Cập nhật kế hoạch ăn (PT)")
    public ResponseEntity<ResDailyDietDTO> updateDailyDiet(
            @PathVariable Long id,
            @Valid @RequestBody ReqDailyDietDTO reqDailyDietDTO) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.updateDailyDiet(id, reqDailyDietDTO);
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.OK);
    }
    
    @PutMapping("/{id}/water-intake")
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Cập nhật lượng nước uống (PT)")
    public ResponseEntity<ResDailyDietDTO> updateWaterIntake(
            @PathVariable Long id,
            @RequestParam Integer waterIntake) {
        ResDailyDietDTO resDailyDietDTO = dailyDietService.updateWaterIntake(id, waterIntake);
        return new ResponseEntity<>(resDailyDietDTO, HttpStatus.OK);
    }
    
    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Xóa kế hoạch ăn (PT)")
    public ResponseEntity<Void> deleteDailyDiet(@PathVariable Long id) {
        dailyDietService.deleteDailyDiet(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}






