package com.se100.GymAndPTManagement.controller;

import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateDietDetailDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateDietDetailDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDietDetailDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.DietDetail;
import com.se100.GymAndPTManagement.service.DietDetailService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.turkraft.springfilter.boot.Filter;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;

import java.util.List;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-15 17:00:00
 * Purpose: DietDetail controller for managing food items in daily diets
 */
@RestController
@RequestMapping("/api/v1/diet-details")
public class DietDetailController {

    private final DietDetailService dietDetailService;

    public DietDetailController(DietDetailService dietDetailService) {
        this.dietDetailService = dietDetailService;
    }

    @Operation(summary = "Add food to daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Food added to diet successfully"),
            @ApiResponse(responseCode = "400", description = "Food already exists in diet"),
            @ApiResponse(responseCode = "404", description = "Daily diet or food not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PostMapping
    @ApiMessage("Thêm thực phẩm vào thực đơn")
    public ResponseEntity<ResDietDetailDTO> addFoodToDiet(@Valid @RequestBody ReqCreateDietDetailDTO request) {
        ResDietDetailDTO dietDetail = dietDetailService.addFoodToDiet(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(dietDetail);
    }

    @Operation(summary = "Get diet detail by composite key")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Diet detail not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/diet/{dietId}/food/{foodId}")
    @ApiMessage("Lấy chi tiết thực phẩm trong thực đơn")
    public ResponseEntity<ResDietDetailDTO> getDietDetail(
            @PathVariable("dietId") Long dietId,
            @PathVariable("foodId") Long foodId) {
        ResDietDetailDTO dietDetail = dietDetailService.getDietDetail(dietId, foodId);
        return ResponseEntity.ok(dietDetail);
    }

    @Operation(summary = "Get all foods in a daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-diet/{dietId}")
    @ApiMessage("Lấy danh sách thực phẩm trong thực đơn")
    public ResponseEntity<List<ResDietDetailDTO>> getDietDetailsByDiet(@PathVariable("dietId") Long dietId) {
        List<ResDietDetailDTO> dietDetails = dietDetailService.getDietDetailsByDiet(dietId);
        return ResponseEntity.ok(dietDetails);
    }

    @Operation(summary = "Get foods in a daily diet with pagination")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-diet/{dietId}/paginated")
    @ApiMessage("Lấy danh sách thực phẩm trong thực đơn với phân trang")
    public ResponseEntity<ResultPaginationDTO> getDietDetailsByDietPaginated(
            @PathVariable("dietId") Long dietId,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dietDetailService.getDietDetailsByDietPaginated(dietId, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get diet details with filter and pagination using SpringFilter")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/fetch")
    @ApiMessage("Lấy danh sách chi tiết thực đơn với filter và pagination")
    public ResponseEntity<ResultPaginationDTO> fetchDietDetails(
            @Parameter(description = "Filter expression using SpringFilter syntax") @Filter Specification<DietDetail> spec,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dietDetailService.handleFetchDietDetails(spec, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Get all diets containing a specific food")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-food/{foodId}")
    @ApiMessage("Lấy danh sách thực đơn chứa thực phẩm")
    public ResponseEntity<ResultPaginationDTO> getDietDetailsByFood(
            @PathVariable("foodId") Long foodId,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO result = dietDetailService.getDietDetailsByFood(foodId, pageable);
        return ResponseEntity.ok(result);
    }

    @Operation(summary = "Update diet detail")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Diet detail updated successfully"),
            @ApiResponse(responseCode = "404", description = "Diet detail not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/diet/{dietId}/food/{foodId}")
    @ApiMessage("Cập nhật chi tiết thực phẩm trong thực đơn")
    public ResponseEntity<ResDietDetailDTO> updateDietDetail(
            @PathVariable("dietId") Long dietId,
            @PathVariable("foodId") Long foodId,
            @Valid @RequestBody ReqUpdateDietDetailDTO request) {
        ResDietDetailDTO dietDetail = dietDetailService.updateDietDetail(dietId, foodId, request);
        return ResponseEntity.ok(dietDetail);
    }

    @Operation(summary = "Remove food from daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Food removed successfully"),
            @ApiResponse(responseCode = "404", description = "Diet detail not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/diet/{dietId}/food/{foodId}")
    @ApiMessage("Xóa thực phẩm khỏi thực đơn")
    public ResponseEntity<Void> removeFoodFromDiet(
            @PathVariable("dietId") Long dietId,
            @PathVariable("foodId") Long foodId) {
        dietDetailService.removeFoodFromDiet(dietId, foodId);
        return ResponseEntity.noContent().build();
    }

    @Operation(summary = "Remove all foods from daily diet")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "All foods removed successfully"),
            @ApiResponse(responseCode = "404", description = "Daily diet not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/by-diet/{dietId}")
    @ApiMessage("Xóa tất cả thực phẩm khỏi thực đơn")
    public ResponseEntity<Void> removeAllFoodsFromDiet(@PathVariable("dietId") Long dietId) {
        dietDetailService.removeAllFoodsFromDiet(dietId);
        return ResponseEntity.noContent().build();
    }
}
