/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 14:05:17
 * Purpose: REST Controller for DietDetail management with role-based authorization
 */

package com.se100.GymAndPTManagement.controller;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqDietDetailDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResDietDetailDTO;
import com.se100.GymAndPTManagement.service.DietDetailService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@RestController
@RequestMapping("/api/v1/diet-details")
@AllArgsConstructor
@Validated
public class DietDetailController {
    
    private final DietDetailService dietDetailService;
    
    @PostMapping
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Thêm thực phẩm vào kế hoạch ăn (PT)")
    public ResponseEntity<ResDietDetailDTO> addFoodToDiet(@Valid @RequestBody ReqDietDetailDTO reqDietDetailDTO) {
        ResDietDetailDTO resDietDetailDTO = dietDetailService.addFoodToDiet(reqDietDetailDTO);
        return new ResponseEntity<>(resDietDetailDTO, HttpStatus.CREATED);
    }
    
    @GetMapping("/by-diet/{dailyDietId}")
    @ApiMessage("Lấy danh sách thực phẩm trong kế hoạch ăn")
    public ResponseEntity<List<ResDietDetailDTO>> getFoodsByDailyDiet(@PathVariable Long dailyDietId) {
        List<ResDietDetailDTO> dietDetails = dietDetailService.getFoodsByDailyDiet(dailyDietId);
        return new ResponseEntity<>(dietDetails, HttpStatus.OK);
    }
    
    @GetMapping("/by-diet/{dailyDietId}/meal-type/{mealType}")
    @ApiMessage("Lấy thực phẩm theo loại bữa ăn")
    public ResponseEntity<List<ResDietDetailDTO>> getFoodsByMealType(
            @PathVariable Long dailyDietId,
            @PathVariable String mealType) {
        List<ResDietDetailDTO> dietDetails = dietDetailService.getFoodsByMealType(dailyDietId, mealType);
        return new ResponseEntity<>(dietDetails, HttpStatus.OK);
    }
    
    @PutMapping("/by-diet/{dailyDietId}/food/{foodId}")
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Cập nhật thực phẩm trong kế hoạch ăn (PT)")
    public ResponseEntity<ResDietDetailDTO> updateDietDetail(
            @PathVariable Long dailyDietId,
            @PathVariable Long foodId,
            @Valid @RequestBody ReqDietDetailDTO reqDietDetailDTO) {
        ResDietDetailDTO resDietDetailDTO = dietDetailService.updateDietDetail(dailyDietId, foodId, reqDietDetailDTO);
        return new ResponseEntity<>(resDietDetailDTO, HttpStatus.OK);
    }
    
    @DeleteMapping("/by-diet/{dailyDietId}/food/{foodId}")
    @PreAuthorize("hasRole('PERSONAL_TRAINER')")
    @ApiMessage("Xóa thực phẩm khỏi kế hoạch ăn (PT)")
    public ResponseEntity<Void> removeFoodFromDiet(
            @PathVariable Long dailyDietId,
            @PathVariable Long foodId) {
        dietDetailService.removeFoodFromDiet(dailyDietId, foodId);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}






