/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 08:06:55
 * Purpose: REST Controller for Food entity management
 */

package com.se100.GymAndPTManagement.controller;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqFoodDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResFoodDTO;
import com.se100.GymAndPTManagement.service.FoodService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@RestController
@RequestMapping("/api/v1/foods")
@AllArgsConstructor
@Validated
public class FoodController {
    
    private final FoodService foodService;
    
    @PostMapping
    @ApiMessage("Tạo mới thực phẩm")
    public ResponseEntity<ResFoodDTO> createFood(@Valid @RequestBody ReqFoodDTO reqFoodDTO) {
        ResFoodDTO resFoodDTO = foodService.createFood(reqFoodDTO);
        return new ResponseEntity<>(resFoodDTO, HttpStatus.CREATED);
    }
    
    @GetMapping("/{id}")
    @ApiMessage("Lấy thông tin thực phẩm theo ID")
    public ResponseEntity<ResFoodDTO> getFoodById(@PathVariable Long id) {
        ResFoodDTO resFoodDTO = foodService.getFoodById(id);
        return new ResponseEntity<>(resFoodDTO, HttpStatus.OK);
    }
    
    @GetMapping
    @ApiMessage("Lấy danh sách tất cả thực phẩm (phân trang)")
    public ResponseEntity<Page<ResFoodDTO>> getAllFoods(Pageable pageable) {
        Page<ResFoodDTO> foods = foodService.getAllFoods(pageable);
        return new ResponseEntity<>(foods, HttpStatus.OK);
    }
    
    @GetMapping("/by-status/{status}")
    @ApiMessage("Lấy danh sách thực phẩm theo trạng thái")
    public ResponseEntity<List<ResFoodDTO>> getFoodsByStatus(@PathVariable String status) {
        List<ResFoodDTO> foods = foodService.getFoodsByStatus(status);
        return new ResponseEntity<>(foods, HttpStatus.OK);
    }
    
    @GetMapping("/by-name/{name}")
    @ApiMessage("Tìm thực phẩm theo tên")
    public ResponseEntity<ResFoodDTO> getFoodByName(@PathVariable String name) {
        ResFoodDTO resFoodDTO = foodService.getFoodByName(name);
        return new ResponseEntity<>(resFoodDTO, HttpStatus.OK);
    }
    
    @GetMapping("/by-calories")
    @ApiMessage("Tìm thực phẩm theo khoảng calo")
    public ResponseEntity<List<ResFoodDTO>> getFoodsByCaloriesBetween(
            @RequestParam Float minCalories,
            @RequestParam Float maxCalories) {
        List<ResFoodDTO> foods = foodService.getFoodsByCaloriesBetween(minCalories, maxCalories);
        return new ResponseEntity<>(foods, HttpStatus.OK);
    }
    
    @GetMapping("/top-protein/{limit}")
    @ApiMessage("Lấy danh sách thực phẩm có protein cao nhất")
    public ResponseEntity<List<ResFoodDTO>> getTopProteinFoods(@PathVariable int limit) {
        List<ResFoodDTO> foods = foodService.getTopProteinFoods(limit);
        return new ResponseEntity<>(foods, HttpStatus.OK);
    }
    
    @PutMapping("/{id}")
    @ApiMessage("Cập nhật thông tin thực phẩm")
    public ResponseEntity<ResFoodDTO> updateFood(@PathVariable Long id, 
                                                   @Valid @RequestBody ReqFoodDTO reqFoodDTO) {
        ResFoodDTO resFoodDTO = foodService.updateFood(id, reqFoodDTO);
        return new ResponseEntity<>(resFoodDTO, HttpStatus.OK);
    }
    
    @DeleteMapping("/{id}")
    @ApiMessage("Xóa thực phẩm")
    public ResponseEntity<Void> deleteFood(@PathVariable Long id) {
        foodService.deleteFood(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}






