/**
 * Generated by: GitHub Copilot (Claude Haiku 4.5)
 * Created by: KStuv
 * Created at: 2026-01-16
 * Purpose: Controller for invoice operations and additional service order processing
 */
package com.se100.GymAndPTManagement.controller;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateAdditionalServiceInvoiceDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResInvoiceDTO;
import com.se100.GymAndPTManagement.service.InvoiceService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.se100.GymAndPTManagement.util.FormatRestResponse;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.util.enums.PaymentStatusEnum;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import jakarta.validation.Valid;
import java.util.List;

@RestController
@RequestMapping("/api/v1/invoices")
public class InvoiceController {
    
    private static final Logger logger = LoggerFactory.getLogger(InvoiceController.class);
    private final InvoiceService invoiceService;
    
    public InvoiceController(InvoiceService invoiceService) {
        this.invoiceService = invoiceService;
    }
    
    /**
     * Create invoice for additional service order
     * POST /api/v1/invoices/additional-service
     * 
     * @param request - ReqCreateAdditionalServiceInvoiceDTO with additionalServiceId, memberId, quantity, discount, paymentMethod
     * @return - ResInvoiceDTO with invoice details
     */
    @PostMapping("/additional-service")
    @ApiMessage("Create invoice for additional service")
    public ResponseEntity<RestResponse<ResInvoiceDTO>> createInvoiceForAdditionalService(
            @Valid @RequestBody ReqCreateAdditionalServiceInvoiceDTO request) {
        
        logger.info("POST /api/v1/invoices/additional-service - Creating invoice for service ID: {}, Member ID: {}",
                   request.getAdditionalServiceId(), request.getMemberId());
        
        try {
            ResInvoiceDTO invoice = invoiceService.createInvoiceForAdditionalService(request);
            
            logger.info("Invoice created successfully with ID: {}", invoice.getInvoiceId());
            
            return ResponseEntity.status(HttpStatus.CREATED)
                .body(FormatRestResponse.success(invoice, "Invoice created successfully for additional service"));
                
        } catch (IllegalArgumentException e) {
            logger.warn("Invalid request for creating invoice: {}", e.getMessage());
            return ResponseEntity.badRequest()
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(400)
                    .message("Invalid request: " + e.getMessage())
                    .build());
        } catch (Exception e) {
            logger.error("Error creating invoice", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(500)
                    .message("Internal server error")
                    .build());
        }
    }
    
    /**
     * Get invoice by ID
     * GET /api/v1/invoices/{id}
     * 
     * @param id - Invoice ID
     * @return - ResInvoiceDTO
     */
    @GetMapping("/{id}")
    @ApiMessage("Get invoice by ID")
    public ResponseEntity<RestResponse<ResInvoiceDTO>> getInvoiceById(@PathVariable Long id) {
        
        logger.debug("GET /api/v1/invoices/{} - Fetching invoice", id);
        
        try {
            ResInvoiceDTO invoice = invoiceService.getInvoiceById(id);
            
            return ResponseEntity.ok(
                RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(200)
                    .message("Invoice retrieved successfully")
                    .data(invoice)
                    .build());
                    
        } catch (IllegalArgumentException e) {
            logger.warn("Invoice not found with ID: {}", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(404)
                    .message("Invoice not found")
                    .build());
        } catch (Exception e) {
            logger.error("Error retrieving invoice with ID: {}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(500)
                    .message("Internal server error")
                    .build());
        }
    }
    
    /**
     * Get all invoices
     * GET /api/v1/invoices
     * 
     * @return - List of ResInvoiceDTO
     */
    @GetMapping
    @ApiMessage("Get all invoices")
    public ResponseEntity<RestResponse<List<ResInvoiceDTO>>> getAllInvoices() {
        
        logger.debug("GET /api/v1/invoices - Fetching all invoices");
        
        try {
            List<ResInvoiceDTO> invoices = invoiceService.getAllInvoices();
            
            return ResponseEntity.ok(
                RestResponse.<List<ResInvoiceDTO>>builder()
                    .statusCode(200)
                    .message("All invoices retrieved successfully")
                    .data(invoices)
                    .build());
                    
        } catch (Exception e) {
            logger.error("Error retrieving all invoices", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(RestResponse.<List<ResInvoiceDTO>>builder()
                    .statusCode(500)
                    .message("Internal server error")
                    .build());
        }
    }
    
    /**
     * Get all invoices for a member
     * GET /api/v1/invoices/member/{memberId}
     * 
     * @param memberId - Member ID
     * @return - List of ResInvoiceDTO
     */
    @GetMapping("/member/{memberId}")
    @ApiMessage("Get invoices by member ID")
    public ResponseEntity<RestResponse<List<ResInvoiceDTO>>> getInvoicesByMemberId(
            @PathVariable Long memberId) {
        
        logger.debug("GET /api/v1/invoices/member/{} - Fetching invoices", memberId);
        
        try {
            List<ResInvoiceDTO> invoices = invoiceService.getInvoicesByMemberId(memberId);
            
            return ResponseEntity.ok(
                RestResponse.<List<ResInvoiceDTO>>builder()
                    .statusCode(200)
                    .message("Invoices retrieved successfully")
                    .data(invoices)
                    .build());
                    
        } catch (IllegalArgumentException e) {
            logger.warn("Invalid member ID: {}", memberId);
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(RestResponse.<List<ResInvoiceDTO>>builder()
                    .statusCode(404)
                    .message("Member not found")
                    .build());
        } catch (Exception e) {
            logger.error("Error retrieving invoices for member ID: {}", memberId, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(RestResponse.<List<ResInvoiceDTO>>builder()
                    .statusCode(500)
                    .message("Internal server error")
                    .build());
        }
    }
    
    /**
     * Update payment status for invoice
     * PUT /api/v1/invoices/{id}/payment-status
     * 
     * @param id - Invoice ID
     * @param paymentStatus - New PaymentStatusEnum (UNPAID or PAID)
     * @return - Updated ResInvoiceDTO
     */
    @PutMapping("/{id}/payment-status")
    @ApiMessage("Update invoice payment status")
    public ResponseEntity<RestResponse<ResInvoiceDTO>> updatePaymentStatus(
            @PathVariable Long id,
            @RequestParam PaymentStatusEnum paymentStatus) {
        
        logger.info("PUT /api/v1/invoices/{}/payment-status - Updating to: {}", id, paymentStatus);
        
        try {
            ResInvoiceDTO updatedInvoice = invoiceService.updatePaymentStatus(id, paymentStatus);
            
            logger.info("Payment status updated successfully for invoice ID: {}", id);
            
            return ResponseEntity.ok(
                RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(200)
                    .message("Payment status updated successfully")
                    .data(updatedInvoice)
                    .build());
                    
        } catch (IllegalArgumentException e) {
            logger.warn("Invoice not found with ID: {}", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(404)
                    .message("Invoice not found")
                    .build());
        } catch (Exception e) {
            logger.error("Error updating payment status for invoice ID: {}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(RestResponse.<ResInvoiceDTO>builder()
                    .statusCode(500)
                    .message("Internal server error")
                    .build());
        }
    }
}
