package com.se100.GymAndPTManagement.controller;

import java.time.LocalDate;
import java.util.List;

import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreatePTDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdatePTDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResMemberDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResPTDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.PersonalTrainer;
import com.se100.GymAndPTManagement.service.PersonalTrainerService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.turkraft.springfilter.boot.Filter;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 11:20:37
 * Purpose: PersonalTrainer controller for PT management endpoints
 */
@RestController
@RequestMapping("/api/v1/pts")
public class PersonalTrainerController {

    private final PersonalTrainerService ptService;

    public PersonalTrainerController(PersonalTrainerService ptService) {
        this.ptService = ptService;
    }

    @Operation(summary = "Create new personal trainer")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Personal trainer created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PostMapping
    @ApiMessage("Tạo Personal Trainer mới")
    public ResponseEntity<ResPTDTO> createPT(@Valid @RequestBody ReqCreatePTDTO request) {
        ResPTDTO pt = ptService.createPT(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(pt);
    }

    @Operation(summary = "Get all personal trainers")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping
    @ApiMessage("Lấy danh sách các Personal Trainer")
    public ResponseEntity<List<ResPTDTO>> getAllPTs() {
        List<ResPTDTO> pts = ptService.getAllPTs();
        return ResponseEntity.ok(pts);
    }

    @Operation(summary = "Fetch personal trainers with filter and pagination")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/fetch")
    @ApiMessage("Fetch personal trainers with filter")
    public ResponseEntity<ResultPaginationDTO> fetchPTsWithFilter(
            @Parameter(name = "filter", description = "Spring-Filter expression. VD: name=='Yoga' and active==true", required = false, example = "name=='Yoga' and active==true") @Filter Specification<PersonalTrainer> specification,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO pts = ptService.handleFetchPTs(specification, pageable);
        return ResponseEntity.ok(pts);
    }

    @Operation(summary = "Get all active personal trainers")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/active")
    @ApiMessage("Lấy danh sách các Personal Trainer đang hoạt động")
    public ResponseEntity<List<ResPTDTO>> getAllActivePTs() {
        List<ResPTDTO> pts = ptService.getAllActivePTs();
        return ResponseEntity.ok(pts);
    }

    @Operation(summary = "Search personal trainer by ID or email")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Personal trainer not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "400", description = "Invalid search parameters")
    })
    @GetMapping("/search")
    @ApiMessage("Lấy Personal Trainer theo ID hoặc email")
    public ResponseEntity<ResPTDTO> searchPT(
            @RequestParam(value = "ptId", required = false) Long ptId,
            @RequestParam(value = "email", required = false) String email) {

        if (ptId == null && (email == null || email.isEmpty())) {
            throw new IllegalArgumentException(
                    "Phải cung cấp ít nhất một trong các tham số: ptId hoặc email");
        }

        ResPTDTO pt;
        if (ptId != null) {
            pt = ptService.getPTById(ptId);
        } else {
            pt = ptService.getPTByEmail(email);
        }

        return ResponseEntity.ok(pt);
    }

    @Operation(summary = "Update personal trainer information")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Personal trainer updated successfully"),
            @ApiResponse(responseCode = "404", description = "Personal trainer not found"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}")
    @ApiMessage("Cập nhật thông tin Personal Trainer")
    public ResponseEntity<ResPTDTO> updatePT(
            @PathVariable("id") Long ptId,
            @Valid @RequestBody ReqUpdatePTDTO request) {
        ResPTDTO pt = ptService.updatePT(ptId, request);
        return ResponseEntity.ok(pt);
    }

    @Operation(summary = "Delete personal trainer (set status to INACTIVE)")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Personal trainer deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Personal trainer not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/{id}")
    @ApiMessage("Xóa Personal Trainer (chuyển trạng thái thành INACTIVE)")
    public ResponseEntity<Void> deletePT(@PathVariable("id") Long ptId) {
        ptService.deletePT(ptId);
        return ResponseEntity.noContent().build();
    }

    @Operation(summary = "Activate personal trainer (set status to AVAILABLE)")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Personal trainer activated successfully"),
            @ApiResponse(responseCode = "404", description = "Personal trainer not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}/go-available")
    @ApiMessage("Kích hoạt lại Personal Trainer (chuyển trạng thái thành AVAILABLE)")
    public ResponseEntity<ResPTDTO> activatePT(@PathVariable("id") Long ptId) {
        ResPTDTO pt = ptService.setAvailablePT(ptId);
        return ResponseEntity.ok(pt);
    }

    @Operation(summary = "Set personal trainer status to BUSY")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Personal trainer status updated successfully"),
            @ApiResponse(responseCode = "404", description = "Personal trainer not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}/go-busy")
    @ApiMessage("Đặt trạng thái Personal Trainer thành BUSY")
    public ResponseEntity<ResPTDTO> setBusyPT(@PathVariable("id") Long ptId) {
        ResPTDTO pt = ptService.setBusyPT(ptId);
        return ResponseEntity.ok(pt);
    }

    @Operation(summary = "Get all available PTs by time slot and date")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Slot not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/available-by-slot")
    @ApiMessage("Lấy danh sách PT rảnh theo slot và ngày") // approved
    public ResponseEntity<List<ResPTDTO>> getAvailablePTsBySlotAndDate(
            @Parameter(description = "ID của slot", required = true, example = "1") @RequestParam("slotId") Long slotId,
            @Parameter(description = "Ngày cần kiểm tra (yyyy-MM-dd)", required = true, example = "2026-01-20") @RequestParam("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        List<ResPTDTO> pts = ptService.getAvailablePTsBySlotAndDate(slotId, date);
        return ResponseEntity.ok(pts);
    }

    @Operation(summary = "Search members by name keyword")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/by-name")
    @ApiMessage("Tìm kiếm PT theo tên")
    public ResponseEntity<List<ResPTDTO>> searchMembersByName(
            @RequestParam("name") String name) {
        List<ResPTDTO> pts = ptService.searchPTsByName(name);
        return ResponseEntity.ok(pts);
    }
}
