package com.se100.GymAndPTManagement.controller;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreatePTDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdatePTDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResPTDTO;
import com.se100.GymAndPTManagement.service.PersonalTrainerService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;

import jakarta.validation.Valid;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-08 11:20:37
 * Purpose: PersonalTrainer controller for PT management endpoints
 */
@RestController
@RequestMapping("/api/v1/pts")
public class PersonalTrainerController {

    private final PersonalTrainerService ptService;

    public PersonalTrainerController(PersonalTrainerService ptService) {
        this.ptService = ptService;
    }

    @PostMapping
    @ApiMessage("Tạo Personal Trainer mới")
    public ResponseEntity<ResPTDTO> createPT(@Valid @RequestBody ReqCreatePTDTO request) {
        ResPTDTO pt = ptService.createPT(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(pt);
    }

    @GetMapping
    @ApiMessage("Lấy danh sách các Personal Trainer")
    public ResponseEntity<List<ResPTDTO>> getAllPTs() {
        List<ResPTDTO> pts = ptService.getAllPTs();
        return ResponseEntity.ok(pts);
    }

    @GetMapping("/active")
    @ApiMessage("Lấy danh sách các Personal Trainer đang hoạt động")
    public ResponseEntity<List<ResPTDTO>> getAllActivePTs() {
        List<ResPTDTO> pts = ptService.getAllActivePTs();
        return ResponseEntity.ok(pts);
    }

    @GetMapping("/search")
    @ApiMessage("Lấy Personal Trainer theo ID hoặc email")
    public ResponseEntity<ResPTDTO> searchPT(
            @RequestParam(value = "ptId", required = false) Long ptId,
            @RequestParam(value = "email", required = false) String email) {

        if (ptId == null && (email == null || email.isEmpty())) {
            throw new IllegalArgumentException(
                    "Phải cung cấp ít nhất một trong các tham số: ptId hoặc email");
        }

        ResPTDTO pt;
        if (ptId != null) {
            pt = ptService.getPTById(ptId);
        } else {
            pt = ptService.getPTByEmail(email);
        }

        return ResponseEntity.ok(pt);
    }

    @PutMapping("/{id}")
    @ApiMessage("Cập nhật thông tin Personal Trainer")
    public ResponseEntity<ResPTDTO> updatePT(
            @PathVariable("id") Long ptId,
            @Valid @RequestBody ReqUpdatePTDTO request) {
        ResPTDTO pt = ptService.updatePT(ptId, request);
        return ResponseEntity.ok(pt);
    }

    @DeleteMapping("/{id}")
    @ApiMessage("Xóa Personal Trainer (chuyển trạng thái thành INACTIVE)")
    public ResponseEntity<Void> deletePT(@PathVariable("id") Long ptId) {
        ptService.deletePT(ptId);
        return ResponseEntity.noContent().build();
    }

    @PutMapping("/{id}/go-available")
    @ApiMessage("Kích hoạt lại Personal Trainer (chuyển trạng thái thành AVAILABLE)")
    public ResponseEntity<ResPTDTO> activatePT(@PathVariable("id") Long ptId) {
        ResPTDTO pt = ptService.setAvailablePT(ptId);
        return ResponseEntity.ok(pt);
    }

    @PutMapping("/{id}/go-busy")
    @ApiMessage("Đặt trạng thái Personal Trainer thành BUSY")
    public ResponseEntity<ResPTDTO> setBusyPT(@PathVariable("id") Long ptId) {
        ResPTDTO pt = ptService.setBusyPT(ptId);
        return ResponseEntity.ok(pt);
    }
}
