package com.se100.GymAndPTManagement.controller;

import java.util.List;
// import java.util.logging.Logger;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqCreateServicePackageDTO;
import com.se100.GymAndPTManagement.domain.requestDTO.ReqUpdateServicePackageDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResServicePackageDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.RestResponse;
import com.se100.GymAndPTManagement.domain.responseDTO.ResultPaginationDTO;
import com.se100.GymAndPTManagement.domain.table.ServicePackage;
import com.se100.GymAndPTManagement.service.ServicePackageService;
import com.se100.GymAndPTManagement.util.FormatRestResponse;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import com.se100.GymAndPTManagement.util.enums.PackageTypeEnum;
import com.turkraft.springfilter.boot.Filter;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: PhDuy2005
 * Created at: 2026-01-11 09:30:43
 * Purpose: REST Controller for ServicePackage management
 */
@RestController
@RequestMapping("/api/v1/service-packages")
@RequiredArgsConstructor
public class ServicePackageController {

    private final ServicePackageService servicePackageService;
    Logger logger = LoggerFactory.getLogger(ServicePackageController.class);

    @Operation(summary = "Create new service package")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Service package created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PostMapping
    @ApiMessage("Create new service package") // approved
    public ResponseEntity<ResServicePackageDTO> createServicePackage(
            @Valid @RequestBody ReqCreateServicePackageDTO request) {
        logger.info(">>SERVICE PACKAGE CONTROLLER: Creating new service package with name: {}",
                request.getPackageName());
        ResServicePackageDTO createdPackage = servicePackageService.createServicePackage(request);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Created service package with ID: {}", createdPackage.getId());
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(createdPackage);
    }

    @Operation(summary = "Get all service packages")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping
    @ApiMessage("Get all service packages") // approved
    public ResponseEntity<List<ResServicePackageDTO>> getAllServicePackages() {
        List<ResServicePackageDTO> packages = servicePackageService.getAllServicePackages();
        logger.info(">>SERVICE PACKAGE CONTROLLER: Retrieved all service packages, count: {}", packages.size());
        return ResponseEntity.ok(packages);
    }

    @Operation(summary = "Fetch service packages with filter and pagination")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/fetch")
    @ApiMessage("Fetch service packages with filter")
    public ResponseEntity<ResultPaginationDTO> fetchServicePackagesWithFilter(
            @Parameter(name = "filter", description = "Spring-Filter expression. VD: name=='Yoga' and active==true", required = false, example = "name=='Yoga' and active==true") @Filter Specification<ServicePackage> specification,
            @ParameterObject Pageable pageable) {
        ResultPaginationDTO packages = servicePackageService.handleFetchServicePackages(specification, pageable);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Fetched service packages with pagination, page: {}, size: {}",
                pageable.getPageNumber() + 1, pageable.getPageSize());
        return ResponseEntity.ok(packages);
    }

    @Operation(summary = "Get all active service packages")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/active")
    @ApiMessage("Get all active service packages") // approved
    public ResponseEntity<List<ResServicePackageDTO>> getAllActiveServicePackages() {
        List<ResServicePackageDTO> packages = servicePackageService.getAllActiveServicePackages();
        logger.info(">>SERVICE PACKAGE CONTROLLER: Retrieved all active service packages, count: {}", packages.size());
        return ResponseEntity.ok(packages);
    }

    @Operation(summary = "Get service packages by type")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/type/{type}")
    @ApiMessage("Get service packages by type") // approved
    public ResponseEntity<List<ResServicePackageDTO>> getServicePackagesByType(
            @PathVariable(value = "type") PackageTypeEnum type,
            @RequestParam(required = false, defaultValue = "false", value = "activeOnly") boolean activeOnly) {
        List<ResServicePackageDTO> packages = activeOnly
                ? servicePackageService.getActiveServicePackagesByType(type)
                : servicePackageService.getServicePackagesByType(type);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Retrieved service packages by type: {}, activeOnly: {}, count: {}",
                type, activeOnly, packages.size());
        return ResponseEntity.ok(packages);
    }

    @Operation(summary = "Get service package by ID")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @GetMapping("/{id}")
    @ApiMessage("Get service package by ID") // approved
    public ResponseEntity<ResServicePackageDTO> getServicePackageById(@PathVariable(value = "id") Long id) {
        ResServicePackageDTO servicePackage = servicePackageService.getServicePackageById(id);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Retrieved service package by ID: {}", id);
        return ResponseEntity.ok(servicePackage);
    }

    @Operation(summary = "Search service package by name")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "400", description = "Invalid search parameters")
    })
    @GetMapping("/search")
    @ApiMessage("Search service package by name") // approved
    public ResponseEntity<ResServicePackageDTO> searchServicePackage(
            @RequestParam(required = false, value = "packageName") String packageName) {
        if (packageName != null && !packageName.trim().isEmpty()) {
            ResServicePackageDTO servicePackage = servicePackageService.getServicePackageByName(packageName);
            logger.info(">>SERVICE PACKAGE CONTROLLER: Retrieved service package by name: {}", packageName);
            return ResponseEntity.ok(servicePackage);
        }
        logger.error(">>SERVICE PACKAGE CONTROLLER: Package name is required for search",
                IllegalArgumentException.class);
        throw new IllegalArgumentException("Package name is required");
    }

    @Operation(summary = "Update service package")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Service package updated successfully"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}")
    @ApiMessage("Update service package")
    public ResponseEntity<ResServicePackageDTO> updateServicePackage(
            @PathVariable("id") Long id,
            @Valid @RequestBody ReqUpdateServicePackageDTO request) {
        ResServicePackageDTO updatedPackage = servicePackageService.updateServicePackage(id, request);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Updated service package with ID: {}", id);
        return ResponseEntity.ok(updatedPackage);
    }

    @Operation(summary = "Delete service package")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Service package deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @DeleteMapping("/{id}")
    @ApiMessage("Delete service package")
    public ResponseEntity<Void> deleteServicePackage(@PathVariable Long id) {
        servicePackageService.deleteServicePackage(id);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Deleted service package with ID: {}", id);
        return ResponseEntity.noContent().build();
    }

    @Operation(summary = "Activate service package")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Service package activated successfully"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}/activate")
    @ApiMessage("Activate service package")
    public ResponseEntity<ResServicePackageDTO> activateServicePackage(@PathVariable Long id) {
        ResServicePackageDTO activatedPackage = servicePackageService.activateServicePackage(id);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Activated service package with ID: {}", id);
        return ResponseEntity.ok(activatedPackage);
    }

    @Operation(summary = "Deactivate service package")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Service package deactivated successfully"),
            @ApiResponse(responseCode = "404", description = "Service package not found"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
    })
    @PutMapping("/{id}/deactivate")
    @ApiMessage("Deactivate service package")
    public ResponseEntity<ResServicePackageDTO> deactivateServicePackage(@PathVariable Long id) {
        ResServicePackageDTO deactivatedPackage = servicePackageService.deactivateServicePackage(id);
        logger.info(">>SERVICE PACKAGE CONTROLLER: Deactivated service package with ID: {}", id);
        return ResponseEntity.ok(deactivatedPackage);
    }
}
