/**
 * Generated by: GitHub Copilot (Claude Sonnet 4.5)
 * Created by: Danh
 * Created at: 2026-01-10 15:18:57
 * Purpose: REST Controller for WorkoutImage management
 */

package com.se100.GymAndPTManagement.controller;

import com.se100.GymAndPTManagement.domain.requestDTO.ReqWorkoutImageDTO;
import com.se100.GymAndPTManagement.domain.responseDTO.ResWorkoutImageDTO;
import com.se100.GymAndPTManagement.service.WorkoutImageService;
import com.se100.GymAndPTManagement.util.annotation.ApiMessage;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@RestController
@RequestMapping("/api/v1/workout-images")
@AllArgsConstructor
@Validated
public class WorkoutImageController {
    
    private final WorkoutImageService workoutImageService;
    
    @PostMapping
    @PreAuthorize("hasAnyRole('ADMIN', 'PERSONAL_TRAINER')")
    @ApiMessage("Thêm hình ảnh cho bài tập (Admin/PT)")
    public ResponseEntity<ResWorkoutImageDTO> addWorkoutImage(@Valid @RequestBody ReqWorkoutImageDTO reqWorkoutImageDTO) {
        ResWorkoutImageDTO resWorkoutImageDTO = workoutImageService.addWorkoutImage(reqWorkoutImageDTO);
        return new ResponseEntity<>(resWorkoutImageDTO, HttpStatus.CREATED);
    }
    
    @GetMapping("/{id}")
    @ApiMessage("Lấy thông tin hình ảnh theo ID")
    public ResponseEntity<ResWorkoutImageDTO> getWorkoutImageById(@PathVariable Long id) {
        ResWorkoutImageDTO resWorkoutImageDTO = workoutImageService.getWorkoutImageById(id);
        return new ResponseEntity<>(resWorkoutImageDTO, HttpStatus.OK);
    }
    
    @GetMapping("/by-workout/{workoutId}")
    @ApiMessage("Lấy danh sách hình ảnh của bài tập")
    public ResponseEntity<List<ResWorkoutImageDTO>> getImagesByWorkoutId(@PathVariable Long workoutId) {
        List<ResWorkoutImageDTO> images = workoutImageService.getImagesByWorkoutId(workoutId);
        return new ResponseEntity<>(images, HttpStatus.OK);
    }
    
    @GetMapping("/by-workout/{workoutId}/ordered")
    @ApiMessage("Lấy danh sách hình ảnh sắp xếp theo thứ tự")
    public ResponseEntity<List<ResWorkoutImageDTO>> getImagesByWorkoutIdOrdered(@PathVariable Long workoutId) {
        List<ResWorkoutImageDTO> images = workoutImageService.getImagesByWorkoutIdOrdered(workoutId);
        return new ResponseEntity<>(images, HttpStatus.OK);
    }
    
    @GetMapping("/by-status/{status}")
    @ApiMessage("Lấy hình ảnh theo trạng thái")
    public ResponseEntity<List<ResWorkoutImageDTO>> getImagesByStatus(@PathVariable String status) {
        List<ResWorkoutImageDTO> images = workoutImageService.getImagesByStatus(status);
        return new ResponseEntity<>(images, HttpStatus.OK);
    }
    
    @PutMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'PERSONAL_TRAINER')")
    @ApiMessage("Cập nhật hình ảnh (Admin/PT)")
    public ResponseEntity<ResWorkoutImageDTO> updateWorkoutImage(@PathVariable Long id,
                                                                  @Valid @RequestBody ReqWorkoutImageDTO reqWorkoutImageDTO) {
        ResWorkoutImageDTO resWorkoutImageDTO = workoutImageService.updateWorkoutImage(id, reqWorkoutImageDTO);
        return new ResponseEntity<>(resWorkoutImageDTO, HttpStatus.OK);
    }
    
    @DeleteMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN', 'PERSONAL_TRAINER')")
    @ApiMessage("Xóa hình ảnh (Admin/PT)")
    public ResponseEntity<Void> deleteWorkoutImage(@PathVariable Long id) {
        workoutImageService.deleteWorkoutImage(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }
}






